
[
  {
    "Name": "Sport Dog Food",
    "Slug": "premium-sport-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "647ddb9037101ce399b344e9",
    "canonical": "alternative-to-sport-dog-food",
    "recordId": "recao7fahUye64b6M",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "sport-dog-food",
    "brandName": "Sport Dog Food",
    "keys": "Sport, Sport Dog, Sport Dog Food",
    "data-five": "1000",
    "data-sort": 1,
    "data-one": "sport",
    "data-brand": "Sport Dog Food",
    "brandId": "1000",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "Dock",
    "img-data-fives": [
      "Cub Puppy",
      "Dock Dog",
      "Herding Dog"
    ],
    "ing-data-fives": [
      "C6HRL",
      "K5VFA",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP",
      "KEB4Z"
    ],
    "cont-data-fives": [
      "K5VFA"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "ci-data-fives": [
      "28979",
      "29280",
      "29099"
    ],
    "cf-data-fives": []
  },
  {
    "Name": "Blue Buffalo",
    "Slug": "alternative-to-blue-buffalo-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd40a044a7623d9a019e",
    "canonical": "alternative-to-blue-buffalo-dog-food",
    "recordId": "recLjhZ5fL70NyuKP",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "blue-buffalo",
    "brandName": "Blue Buffalo",
    "keys": "blue buffalo, blue, buffalo, bluebuffalo, blue-buffalo, blu buffalo, blue bufflo",
    "data-five": "6526",
    "data-sort": 12,
    "data-one": "blue",
    "data-brand": "Blue Buffalo",
    "brandId": "6526",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "383368",
    "img-data-fives": [],
    "ing-data-fives": [],
    "cont-data-fives": [],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [],
    "cf-data-fives": []
  },
  {
    "Name": "Dr Tims",
    "Slug": "alternative-to-dr-tims-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd40c832bba3986afaa0",
    "canonical": "alternative-to-dr-tims-dog-food",
    "recordId": "recQo3fvuovVubA1W",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "dr-tims",
    "brandName": "Dr Tims",
    "keys": "dr tims, dr. tims, drtims, dr tim’s, drtim’s, dr tim, dr tims formula",
    "data-five": "6697",
    "data-sort": 4,
    "data-one": "drtims",
    "data-brand": "Dr Tims",
    "brandId": "6697",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313fba4e5c590be4bb982ce5f2791570cb6?version=1.0&width=2046&height=1536",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "119068",
    "img-data-fives": [
      "119068",
      "37811"
    ],
    "ing-data-fives": [
      "CEVBH",
      "GKL4J",
      "72Y0R",
      "LJBTO",
      "WJEHA",
      "TDEIO",
      "LHLHB",
      "VUYIW",
      "ZTMYL",
      "NCE9F",
      "Z9I0H",
      "VT96P",
      "KZC6H",
      "IP9OV",
      "X5FFT",
      "YD8CG",
      "YRWGG",
      "SQ0XJ",
      "COVUX",
      "EKBTQ",
      "YHGZY",
      "MLAA7",
      "COCPI",
      "QX1UZ",
      "MBFOA",
      "9UMLW",
      "HQGYF",
      "OOUXY",
      "SIPQU",
      "QKPNY",
      "GP3HX",
      "KZYKM",
      "AYV0F",
      "KSOUF",
      "ECLSM",
      "BOL4J",
      "K3WTW",
      "555IX",
      "ZPGID",
      "BWNCE",
      "OQE8V",
      "LDMXN",
      "CDODO",
      "M0BM4",
      "QFRJN",
      "AH4GG",
      "PRW8L",
      "YLNYF",
      "IIDS9",
      "FXO5C",
      "QJDEF",
      "HDFQP",
      "1JDZJ",
      "KQB77",
      "CAL2I",
      "SWMVA",
      "4GGMJ",
      "GYPF8",
      "BCPGM",
      "U9EU7"
    ],
    "cont-data-fives": [
      "72Y0R",
      "LJBTO",
      "WJEHA",
      "TDEIO",
      "VUYIW",
      "ZTMYL",
      "NCE9F",
      "HQGYF",
      "OOUXY",
      "FXO5C",
      "HDFQP",
      "1JDZJ",
      "KQB77"
    ],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [
      "119068",
      "37811"
    ],
    "cf-data-fives": []
  },
  {
    "Name": "Eukanuba",
    "Slug": "alternative-to-eukanuba-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd4081ba945ec9233e0c",
    "canonical": "alternative-to-eukanuba-dog-food",
    "recordId": "rec288JkLV66Bf5z4",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "eukanuba",
    "brandName": "Eukanuba",
    "keys": "eukanuba, eukanaba, eucanuba, eukanuba kibble, eukanaba",
    "data-five": "6734",
    "data-sort": 8,
    "data-one": "eukanuba",
    "data-brand": "Eukanuba",
    "brandId": "6734",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9x439c2566aba841b68d82073c26688034?version=1.0&width=2046&height=1536",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "552422",
    "img-data-fives": [
      "552422"
    ],
    "ing-data-fives": [
      "IULX1",
      "MDIZK",
      "I1FXE",
      "JGOFI",
      "INGB4",
      "VUYIW",
      "Z9I0H",
      "TDEIO",
      "ZTMYL",
      "AH4GG",
      "KZC6H",
      "GJA6Y",
      "9UMLW",
      "4GUVA",
      "RD1WV",
      "QKPNY",
      "UTGPV",
      "YD8CG",
      "SQ0XJ",
      "HBTUA",
      "YRWGG",
      "MLAA7",
      "YHGZY",
      "QX1UZ",
      "COVUX",
      "COCPI",
      "MBFOA",
      "SIPQU",
      "V43XM",
      "MBU30",
      "BOL4J",
      "555IX",
      "OQE8V",
      "SCYOC",
      "LDMXN",
      "9WQMN",
      "L5O6A",
      "7YYYV"
    ],
    "cont-data-fives": [
      "MDIZK",
      "I1FXE",
      "JGOFI",
      "VUYIW",
      "TDEIO",
      "ZTMYL",
      "RD1WV"
    ],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [
      "552422"
    ],
    "cf-data-fives": []
  },
  {
    "Name": "Farmina",
    "Slug": "alternative-to-farmina-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd4008ecc5d50fedf4ad",
    "canonical": "alternative-to-farmina-dog-food",
    "recordId": "recpakb7zx8rorCpE",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "farmina",
    "brandName": "Farmina",
    "keys": "farmina, framina, farmna, farmina dog food",
    "data-five": "6749",
    "data-sort": 5,
    "data-one": "farmina",
    "data-brand": "Farmina",
    "brandId": "6749",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473133c1341cf43ea4d198d4e3de201225bfa?version=1.0&width=2046&height=1536",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "55911",
    "img-data-fives": [
      "55911",
      "105269",
      "202214"
    ],
    "ing-data-fives": [
      "7SZIB",
      "C2TWM",
      "G4ZMU",
      "DZYA6",
      "XC0BR",
      "Z7Z8A",
      "HT5ZK",
      "VUYIW",
      "IQTT3",
      "1VEVT",
      "IQE13",
      "YHSJR",
      "90DOH",
      "4GUVA",
      "JJTVJ",
      "XR8EH",
      "HJJWJ",
      "TSXY8",
      "YPL1J",
      "17YZ3",
      "PRW8L",
      "9UMLW",
      "LNDRX",
      "W0HAM",
      "IPPTH",
      "9WQMN",
      "EKBTQ",
      "COCPI",
      "04ZOO",
      "JUDBS",
      "YRWGG",
      "UIC8H",
      "81XCU",
      "MLAA7",
      "YHGZY",
      "YD8CG",
      "MBFOA",
      "QX1UZ",
      "QKPNY",
      "UHTXD",
      "2SX0Z",
      "VDCDU",
      "CAIRD",
      "4BJJX",
      "XV780",
      "SIPQU",
      "M0BM4",
      "SWMVA",
      "VM56I",
      "NVUQ6",
      "L5O6A",
      "CAFOM",
      "IULX1",
      "GAMG6",
      "JRLXE",
      "CIPVY",
      "RW1BB",
      "ZOEIR",
      "U6HWJ",
      "V43XM"
    ],
    "cont-data-fives": [
      "G4ZMU",
      "DZYA6",
      "VUYIW",
      "1VEVT"
    ],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [
      "105269",
      "202214",
      "55911"
    ],
    "cf-data-fives": []
  },
  {
    "Name": "Nutro",
    "Slug": "alternative-to-nutro-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd40322fb2fd16f0f7d3",
    "canonical": "alternative-to-nutro-dog-food",
    "recordId": "recuP07TR6YoUwAkZ",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "nutro",
    "brandName": "Nutro",
    "keys": "nutro, nutroo, nutro dry, nutro dog food",
    "data-five": "7138",
    "data-sort": 9,
    "data-one": "nutro",
    "data-brand": "Nutro",
    "brandId": "7138",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "",
    "img-data-fives": [],
    "ing-data-fives": [],
    "cont-data-fives": [],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [],
    "cf-data-fives": []
  },
  {
    "Name": "Purina Pro Plan",
    "Slug": "alternative-to-purina-pro-plan-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6852015fb2bcb307a5d8d835",
    "canonical": "alternative-to-purina-pro-plan-dog-food",
    "recordId": "rec3hVRKT7Ylerk5J",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "purina-pro-plan",
    "brandName": "Purina Pro Plan",
    "keys": "purina pro plan, purinaproplan, purina proplan, purina pro, pro plan, purinaplan",
    "data-five": "7434",
    "data-sort": 2,
    "data-one": "purina",
    "data-brand": "Purina Pro Plan",
    "brandId": "7434",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xcc58fac5e0664d969a12cdaa8c2063da?version=1.0&width=2046&height=1536",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "298045",
    "img-data-fives": [
      "298045",
      "52445",
      "52423",
      "114025"
    ],
    "ing-data-fives": [
      "THZVQ",
      "CDQCK",
      "UYDPF",
      "QHDUJ",
      "OAYON",
      "GOURU",
      "PUVNB",
      "Q99OM",
      "SZ9O3",
      "F4SUG",
      "1VEVT",
      "8KBDY",
      "K4SWZ",
      "ORXDE",
      "G0IOG",
      "KZC6H",
      "R8PIF",
      "9UMLW",
      "AH4GG",
      "UCMJH",
      "BOL4J",
      "BWNCE",
      "K3WTW",
      "AWE1M",
      "AJI2E",
      "JX8SA",
      "E94HP",
      "EKBTQ",
      "5EIKP",
      "7TSVX",
      "QZ09Z",
      "CPEN5",
      "2ZKIM",
      "HQCHY",
      "B92D3",
      "Q08LQ",
      "0EEFX",
      "QKPNY",
      "4GGMJ",
      "1THAG",
      "QISOK",
      "DLHTR",
      "FLMRA",
      "B2WBK",
      "NQ4LR",
      "RD1WV",
      "5S0XF",
      "E87QO",
      "HUSPZ",
      "FRWZQ",
      "YAPNO",
      "X7J76",
      "NRX8Q",
      "555IX",
      "V43XM",
      "M0BM4",
      "FSMSV",
      "IULX1",
      "HWIWE",
      "WHF79",
      "K2QVC",
      "GVKK6",
      "XGGOP",
      "RANER"
    ],
    "cont-data-fives": [
      "CDQCK",
      "UYDPF",
      "QHDUJ",
      "OAYON",
      "GOURU",
      "Q99OM",
      "SZ9O3",
      "1VEVT",
      "G0IOG",
      "JGOFI",
      "R8PIF",
      "B2WBK",
      "NQ4LR",
      "RD1WV",
      "HWIWE",
      "WHF79"
    ],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [
      "114025",
      "298045",
      "52423",
      "52445"
    ],
    "cf-data-fives": []
  },
  {
    "Name": "Royal Canin",
    "Slug": "alternative-to-royal-canin-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd40b2bcb307a5d72f1b",
    "canonical": "alternative-to-royal-canin-dog-food",
    "recordId": "recZD5twvKGDD6vl0",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "royal-canin",
    "brandName": "Royal Canin",
    "keys": "royal canin, royalcanin, royal cannin, royal canan",
    "data-five": "7487",
    "data-sort": 10,
    "data-one": "royal",
    "data-brand": "Royal Canin",
    "brandId": "7487",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "",
    "img-data-fives": [],
    "ing-data-fives": [],
    "cont-data-fives": [],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [],
    "cf-data-fives": []
  },
  {
    "Name": "Solid Gold",
    "Slug": "alternative-to-solid-gold-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd40c46cf117a17dce80",
    "canonical": "alternative-to-solid-gold-dog-food",
    "recordId": "recwt16fDtdyOFJUR",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "solid-gold",
    "brandName": "Solid Gold",
    "keys": "solid gold, solidgold, solide gold, solid gold kibble",
    "data-five": "7536",
    "data-sort": 7,
    "data-one": "solid",
    "data-brand": "Solid Gold",
    "brandId": "7536",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xc275aeaaead6465abf3987c34513b166?version=1.0&width=2046&height=1536",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "841846",
    "img-data-fives": [
      "841846"
    ],
    "ing-data-fives": [
      "2NZMY",
      "FVSVS",
      "GKL4J",
      "KEB4Z",
      "VFUPE",
      "5KHTT",
      "LJBTO",
      "K5VFA",
      "8ALHU",
      "5E1NB",
      "2LCAZ",
      "R7JU0",
      "IQCTZ",
      "F4SUG",
      "P46XM",
      "IIDS9",
      "4CQVY",
      "GXM84",
      "BOL4J",
      "555IX",
      "NRX8Q",
      "ZPGID",
      "BWNCE",
      "K3WTW",
      "OQE8V",
      "CDODO",
      "IP9OV",
      "DL4MS",
      "YRWGG",
      "UIC8H",
      "81XCU",
      "MLAA7",
      "YHGZY",
      "EKBTQ",
      "QX1UZ",
      "COCPI",
      "YD8CG",
      "LBF24",
      "XORST",
      "XUUYO",
      "QKPNY",
      "IQK4Z",
      "F1INB",
      "M0BM4",
      "L5O6A",
      "ZYKY5"
    ],
    "cont-data-fives": [
      "VFUPE",
      "5KHTT",
      "LJBTO",
      "K5VFA",
      "8OTUY",
      "R7JU0"
    ],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [
      "841846"
    ],
    "cf-data-fives": []
  },
  {
    "Name": "Victor",
    "Slug": "alternative-to-victor-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd406b23e78d87cfccb6",
    "canonical": "alternative-to-victor-dog-food",
    "recordId": "recSJYWkocDyf0cMi",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor",
    "brandName": "Victor",
    "keys": "victor, viktor, victor dog food, victor active, victor xyz",
    "data-five": "7682",
    "data-sort": 6,
    "data-one": "victor",
    "data-brand": "Victor",
    "brandId": "7682",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313974dbedb88c3499bb3770ed53a26bfac?version=1.0&width=2046&height=1536",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "120680",
    "img-data-fives": [
      "120680",
      "120684",
      "120700",
      "120702",
      "120706",
      "120708",
      "120711",
      "129281",
      "279306"
    ],
    "ing-data-fives": [
      "B9RZP",
      "E9MIY",
      "VJD3I",
      "VUYIW",
      "LJBTO",
      "GE6GU",
      "RH9L7",
      "ETXUL",
      "BS8EA",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK",
      "GSJWC",
      "CEVBH",
      "H0NSG",
      "V43XM",
      "9WQMN",
      "G2YVH",
      "5E1NB",
      "LQRGM",
      "7JYFL",
      "MBFOA",
      "4GGMJ",
      "6GX4D",
      "V9APU",
      "LNUMU",
      "Y7ODL",
      "DH0D2",
      "EJMRL",
      "ZTMYL",
      "CSYLS",
      "U3RU8"
    ],
    "cont-data-fives": [
      "VUYIW",
      "LJBTO",
      "BSL2E",
      "PG8TP",
      "HNLVZ",
      "OOUXY",
      "G2YVH",
      "LNUMU",
      "ZTMYL"
    ],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [
      "120680",
      "120684",
      "120700",
      "120702",
      "120706",
      "120708",
      "120711",
      "129281",
      "279306"
    ],
    "cf-data-fives": []
  },
  {
    "Name": "Acana",
    "Slug": "alternative-to-acana-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd40e1d1e7b519d90274",
    "canonical": "alternative-to-acana-dog-food",
    "recordId": "recksMWzYkPoF9lO3",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "acana",
    "brandName": "Acana",
    "keys": "acana, acanna, acana dog food, acana kibble",
    "data-five": "8755",
    "data-sort": 3,
    "data-one": "acana",
    "data-brand": "Acana",
    "brandId": "8755",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473133da27f6ef89f47309fdd379884287a5b?version=1.0&width=2046&height=1536",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "285973",
    "img-data-fives": [
      "285973"
    ],
    "ing-data-fives": [
      "FLMRA",
      "GSJWC",
      "CQCMT",
      "5E1NB",
      "5KHTT",
      "ARHPV",
      "XJAAA",
      "4CQVY",
      "RD1WV",
      "SYGQB",
      "Z9I0H",
      "BSARH",
      "XUUYO",
      "9UMLW",
      "QKPNY",
      "M0BM4",
      "GP3HX",
      "04ZOO",
      "ZPGID",
      "AGJPT",
      "COCPI",
      "YRWGG",
      "YHGZY",
      "UIC8H",
      "MLAA7",
      "81XCU",
      "MBFOA",
      "QX1UZ",
      "K3WTW",
      "QFRJN",
      "W0HAM",
      "KE2JS",
      "L5O6A",
      "RUAPK",
      "993B1",
      "UQHTP"
    ],
    "cont-data-fives": [
      "5KHTT",
      "XJAAA",
      "RD1WV",
      "SYGQB"
    ],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [
      "285973"
    ],
    "cf-data-fives": []
  },
  {
    "Name": "Orijen",
    "Slug": "alternative-to-orijen-dog-food",
    "Collection ID": "647ddb9037101ce399b330cb",
    "Item ID": "6851fd4036a23a7789e5efd8",
    "canonical": "alternative-to-orijen-dog-food",
    "recordId": "recZao9PG7Whx62FE",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "orijen",
    "brandName": "Orijen",
    "keys": "orijen, orjan, origen, origan, orijen kibble",
    "data-five": "8819",
    "data-sort": 11,
    "data-one": "orijen",
    "data-brand": "Orijen",
    "brandId": "8819",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "br",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "",
    "img-data-fives": [],
    "ing-data-fives": [],
    "cont-data-fives": [],
    "si-data-fives": [],
    "sf-data-fives": [],
    "ci-data-fives": [],
    "cf-data-fives": []
  }
]
