[
  {
    "Name": "Farmina Nd Ancestral Grain Lamb",
    "Slug": "compare-farmina-nd-ancestral-grain-lamb-ingredients",
    "canonical": "compare-farmina-nd-ancestral-grain-lamb-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7800fefebdd76a521ed",
    "calcSlug": "farmina-nd-ancestral-grain-lamb",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "105269",
    "itemName": "Farmina Nd Ancestral Grain Lamb",
    "item-subtitle": "",
    "itemRecordId": "recG41YKSBwzoJ95O",
    "all_ingredients-calc-slugs": [
      "lamb",
      "spelt",
      "oats",
      "eggs",
      "fresh-herring",
      "herring",
      "chicken-fat",
      "herring-oil",
      "beet-pulp",
      "carrots",
      "alfalfa-meal",
      "inulin",
      "fructooligosaccharides",
      "yeast-extracts",
      "blueberries",
      "apples",
      "pomegranates",
      "dried-sweet-orange",
      "spinach",
      "psyllium-seed-husk",
      "salt",
      "brewers-yeast",
      "turmeric",
      "glucosamine",
      "chondroitin-sulfate",
      "vitamin-a-supplement",
      "vitamin-d3-supplement",
      "vitamin-e-supplement",
      "ascorbic-acid",
      "niacin",
      "calcium-pantothenate",
      "riboflavin",
      "pyridoxine-hydrochloride",
      "thiamine-mononitrate",
      "biotin",
      "folic-acid",
      "vitamin-b12-supplement",
      "choline-chloride",
      "beta-carotene",
      "zinc-methionine-hydroxy-analogue-chelate",
      "manganese-methionine-hydroxy-analogue-chelate",
      "ferrous-glycine",
      "copper-methionine-hydroxy-analogue-chelate",
      "selenium-yeast",
      "dl-methionine",
      "taurine",
      "l-carnitine",
      "aloe-vera-gel-concentrate",
      "green-tea-extract",
      "rosemary-extract",
      "mixed-tocopherols"
    ],
    "data-faqType": "",
    "data-sort": 1,
    "data-diet": "Grain",
    "data-one": "Nd Ancestral Grain Lamb",
    "data-alt": "Nd Ancestral Grain Lamb",
    "data-brand": "Farmina",
    "specs_price_per_bag": 99.99,
    "brandId": "Farmina",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313037a735e6d564ef48c280a60948ce8da?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Lamb Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 28,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3941,
    "ga_kcals_per_cup": 394,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 26.4,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Purina Pro Plan Adult Shredded Blend",
    "Slug": "compare-purina-pro-plan-adult-shredded-blend-ingredients",
    "canonical": "compare-purina-pro-plan-adult-shredded-blend-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a780f2d2d049077b5267",
    "calcSlug": "purina-pro-plan-adult-shredded-blend",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "114025",
    "itemName": "Purina Pro Plan Adult Shredded Blend",
    "item-subtitle": "",
    "itemRecordId": "recBTxPXyQpna57oa",
    "all_ingredients-calc-slugs": [
      "salmon",
      "rice",
      "wheat",
      "poultry-by-product",
      "corn",
      "soybean-meal",
      "beef-fat",
      "corn-protein-meal",
      "fish-meal",
      "natural-flavors",
      "beet-pulp",
      "egg-product",
      "glycerin",
      "mono-and-dicalcium-phosphate",
      "wheat-bran",
      "calcium-carbonate",
      "soybean-oil",
      "salt",
      "potassium-chloride",
      "ferrous-sulfate",
      "manganese-proteinate",
      "copper-proteinate",
      "calcium-iodate",
      "sodium-selenite",
      "niacin",
      "vitamin-a-supplement",
      "thiamine-mononitrate",
      "calcium-pantothenate",
      "riboflavin-supplement",
      "vitamin-b12-supplement",
      "pyridoxine-hydrochloride",
      "menadione-sodium-bisulfite-complex-(vitamin-k)",
      "folic-acid",
      "biotin",
      "vitamin-d3-supplement",
      "choline-chloride",
      "dried-bacillus-coagulans-fermentation-product",
      "l-lysine-monohydrochloride"
    ],
    "data-faqType": "",
    "data-sort": 2,
    "data-diet": "Grain",
    "data-one": "Adult Shredded Blend",
    "data-alt": "Adult Shredded Blend",
    "data-brand": "Purina Pro Plan",
    "specs_price_per_bag": 74.48,
    "brandId": "Purina Pro Plan",
    "brands": "Purina Pro Plan",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313ae81944782da45689476f3904529bf9f?version=1.0&width=2046&height=1536",
    "previewAlttag": "Adult Shredded Blend Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 26,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3856,
    "ga_kcals_per_cup": 389,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Fish",
    "specs_bag-size_lbs": 33,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Dr Tims Weight Management Metabolite",
    "Slug": "compare-dr-tims-weight-management-metabolite-ingredients",
    "canonical": "compare-dr-tims-weight-management-metabolite-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a780bb4b55c6a7bdd58b",
    "calcSlug": "dr-tims-weight-management-metabolite",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "119068",
    "itemName": "Dr Tims Weight Management Metabolite",
    "item-subtitle": "",
    "itemRecordId": "recOZZ6fOAtjUcH2C",
    "all_ingredients-calc-slugs": [
      "chicken-meal",
      "brown-rice",
      "oats",
      "peas",
      "cellulose",
      "beet-pulp",
      "salmon-meal",
      "chicken-fat",
      "egg-product",
      "porcine-plasma",
      "natural-flavors",
      "flaxseed",
      "calcium-carbonate",
      "l-ascorbyl-2-polyphosphate",
      "biotin",
      "niacin",
      "d-calcium-pantothenate",
      "riboflavin-supplement",
      "vitamin-a-supplement",
      "thiamine-mononitrate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "vitamin-b12-supplement",
      "folic-acid",
      "salt",
      "menhaden-fish-oil",
      "lecithin",
      "dl-methionine",
      "choline-chloride",
      "kelp",
      "l-lysine",
      "zinc-sulfate",
      "iron-proteinate",
      "ferrous-sulfate",
      "copper-proteinate",
      "copper-sulfate",
      "zinc-proteinate",
      "manganese-proteinate",
      "sodium-selenite",
      "manganous-oxide",
      "taurine",
      "chicory-root",
      "potassium-chloride",
      "psyllium-seed-husk",
      "yucca-schidigera-extract",
      "carrots",
      "celery",
      "beets",
      "parsley",
      "lettuce",
      "watercress",
      "spinach",
      "l-carnitine",
      "dried-bacillus-coagulans-fermentation-product"
    ],
    "data-faqType": "",
    "data-sort": 3,
    "data-diet": "Grain",
    "data-one": "Weight Management Metabolite",
    "data-alt": "Weight Management Metabolite",
    "data-brand": "Dr Tims",
    "specs_price_per_bag": 87.99,
    "brandId": "Dr Tims",
    "brands": "Dr Tims",
    "brandDisplay": "Dr Tims",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313fba4e5c590be4bb982ce5f2791570cb6?version=1.0&width=2046&height=1536",
    "previewAlttag": "Weight Management Metabolite Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 10,
    "ga_crude_fiber_%": 10,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3218,
    "ga_kcals_per_cup": 411,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 24,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Select Lamb Meal Brown Rice",
    "Slug": "compare-victor-select-lamb-meal-brown-rice-ingredients",
    "canonical": "compare-victor-select-lamb-meal-brown-rice-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7809c270652d7a81cf9",
    "calcSlug": "victor-select-lamb-meal-brown-rice",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "120680",
    "itemName": "Victor Select Lamb Meal Brown Rice",
    "item-subtitle": "",
    "itemRecordId": "recHWP48JBtTLPzIE",
    "all_ingredients-calc-slugs": [
      "lamb-meal",
      "brown-rice",
      "millet",
      "chicken-fat",
      "peas",
      "sorghum",
      "blood-meal",
      "yeast-cultures",
      "alfalfa-meal",
      "natural-flavors",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "zinc-methionine-complex",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "dried-aspergillus-oryzae-fermentation-extract",
      "dried-trichoderma-longibrachiatum-fermentation-extract",
      "bacillus-subtilis-fermentation",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "vegetable-oil",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid"
    ],
    "data-faqType": "",
    "data-sort": 4,
    "data-diet": "Grain",
    "data-one": "Select Lamb Meal Brown Rice",
    "data-alt": "Select Lamb Meal Brown Rice",
    "data-brand": "Victor",
    "specs_price_per_bag": 78.24,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313974dbedb88c3499bb3770ed53a26bfac?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Lamb Meal Brown Rice Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 24,
    "ga_crude_fat_%": 12,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3501,
    "ga_kcals_per_cup": 372,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 40,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Purpose Performance Formula",
    "Slug": "compare-victor-purpose-performance-formula-ingredients",
    "canonical": "compare-victor-purpose-performance-formula-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a780a7b546547d24d75a",
    "calcSlug": "victor-purpose-performance-formula",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "120684",
    "itemName": "Victor Purpose Performance Formula",
    "item-subtitle": "",
    "itemRecordId": "recYjsc1r9roUfZQu",
    "all_ingredients-calc-slugs": [
      "beef-meal",
      "sorghum",
      "millet",
      "chicken-fat",
      "blood-meal",
      "chicken-meal",
      "pork-meal",
      "alfalfa-meal",
      "yeast-cultures",
      "natural-flavors",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "zinc-methionine-complex",
      "glucosamine-hydrochloride",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "chondroitin-sulfate",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "dried-aspergillus-oryzae-fermentation-extract",
      "dried-trichoderma-longibrachiatum-fermentation-extract",
      "bacillus-subtilis-fermentation",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "vegetable-oil",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid"
    ],
    "data-faqType": "",
    "data-sort": 5,
    "data-diet": "Grain",
    "data-one": "Purpose Performance Formula",
    "data-alt": "Purpose Performance Formula",
    "data-brand": "Victor",
    "specs_price_per_bag": 65.29,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473130453a01e4ab94c9ea5a84cec88297f14?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Performance Formula Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 26,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3756,
    "ga_kcals_per_cup": 399,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 40,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Purpose Active Dog Puppy",
    "Slug": "compare-victor-purpose-active-dog-puppy-ingredients",
    "canonical": "compare-victor-purpose-active-dog-puppy-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7815ab150cfbcac8594",
    "calcSlug": "victor-purpose-active-dog-puppy",
    "typed_intro": "",
    "diets_slugs": [
      "grain-free"
    ],
    "itemId": "120700",
    "itemName": "Victor Purpose Active Dog Puppy",
    "item-subtitle": "",
    "itemRecordId": "recA5sadFi83r4I9Q",
    "all_ingredients-calc-slugs": [
      "beef-meal",
      "peas",
      "garbanzo-beans",
      "chicken-fat",
      "sweet-potatoes",
      "blood-meal",
      "menhaden-fish-meal",
      "yeast-cultures",
      "alfalfa-meal",
      "natural-flavors",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "zinc-methionine-complex",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "mono-and-diglycerides-of-fatty-acids",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid",
      "dried-bacillus-coagulans-fermentation-product",
      "bacillus-subtilis-fermentation"
    ],
    "data-faqType": "",
    "data-sort": 6,
    "data-diet": "Grain-Free",
    "data-one": "Purpose Active Dog Puppy",
    "data-alt": "Purpose Active Dog Puppy",
    "data-brand": "Victor",
    "specs_price_per_bag": 70.29,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313cd0b81f15619488b8f3a5a61031ee725?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Active Dog Puppy Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 33,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3614,
    "ga_kcals_per_cup": 384,
    "diets_multiselect": [
      "Grain Free"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 30,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Purpose Hero Grain Free Dry",
    "Slug": "compare-victor-purpose-hero-grain-free-dry-ingredients",
    "canonical": "compare-victor-purpose-hero-grain-free-dry-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a78034eee4f54e37e243",
    "calcSlug": "victor-purpose-hero-grain-free-dry",
    "typed_intro": "",
    "diets_slugs": [
      "grain-free"
    ],
    "itemId": "120702",
    "itemName": "Victor Purpose Hero Grain Free Dry",
    "item-subtitle": "",
    "itemRecordId": "rechhhtL9ySIeIiO6",
    "all_ingredients-calc-slugs": [
      "beef-meal",
      "peas",
      "sweet-potatoes",
      "chicken-fat",
      "menhaden-fish-meal",
      "blood-meal",
      "garbanzo-beans",
      "pork-meal",
      "yeast-cultures",
      "alfalfa-meal",
      "natural-flavors",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "zinc-methionine-complex",
      "glucosamine-hydrochloride",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "chondroitin-sulfate",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "dried-aspergillus-oryzae-fermentation-extract",
      "dried-trichoderma-longibrachiatum-fermentation-extract",
      "bacillus-subtilis-fermentation",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "vegetable-oil",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid"
    ],
    "data-faqType": "",
    "data-sort": 7,
    "data-diet": "Grain-Free",
    "data-one": "Purpose Hero Grain Free Dry",
    "data-alt": "Purpose Hero Grain Free Dry",
    "data-brand": "Victor",
    "specs_price_per_bag": 70.29,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313c9733e62fcd14c949e2bfd02367b4efe?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Hero Grain Free Dry Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 33,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3614,
    "ga_kcals_per_cup": 384,
    "diets_multiselect": [
      "Grain Free"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 30,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Select Yukon River Canine",
    "Slug": "compare-victor-select-yukon-river-canine-ingredients",
    "canonical": "compare-victor-select-yukon-river-canine-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a780b534d9b058da272c",
    "calcSlug": "victor-select-yukon-river-canine",
    "typed_intro": "",
    "diets_slugs": [
      "grain-free"
    ],
    "itemId": "120706",
    "itemName": "Victor Select Yukon River Canine",
    "item-subtitle": "",
    "itemRecordId": "receH6sCo3eoHcBsk",
    "all_ingredients-calc-slugs": [
      "menhaden-fish-meal",
      "peas",
      "chicken-fat",
      "garbanzo-beans",
      "salmon",
      "sweet-potatoes",
      "yeast-cultures",
      "alfalfa-meal",
      "blood-meal",
      "natural-flavors",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "zinc-methionine-complex",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "dried-aspergillus-oryzae-fermentation-extract",
      "dried-trichoderma-longibrachiatum-fermentation-extract",
      "bacillus-subtilis-fermentation",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "vegetable-oil",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid"
    ],
    "data-faqType": "",
    "data-sort": 8,
    "data-diet": "Grain-Free",
    "data-one": "Select Yukon River Canine",
    "data-alt": "Select Yukon River Canine",
    "data-brand": "Victor",
    "specs_price_per_bag": 77.99,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731382ccc323d7a3462da82b879e1901daad?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Yukon River Canine Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 33,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3666,
    "ga_kcals_per_cup": 390,
    "diets_multiselect": [
      "Grain Free"
    ],
    "specs_primary_flavor": "Fish",
    "specs_bag-size_lbs": 30,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Purpose Ultra Pro Grain Free",
    "Slug": "compare-victor-purpose-ultra-pro-grain-free-ingredients",
    "canonical": "compare-victor-purpose-ultra-pro-grain-free-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a781319a5aab0fcd1689",
    "calcSlug": "victor-purpose-ultra-pro-grain-free",
    "typed_intro": "",
    "diets_slugs": [
      "grain-free"
    ],
    "itemId": "120708",
    "itemName": "Victor Purpose Ultra Pro Grain Free",
    "item-subtitle": "",
    "itemRecordId": "recaeGW8ob4kCsNzL",
    "all_ingredients-calc-slugs": [
      "chicken-meal",
      "beef-meal",
      "chicken-fat",
      "peas",
      "blood-meal",
      "yeast-cultures",
      "pork-meal",
      "alfalfa-meal",
      "sweet-potatoes",
      "menhaden-fish-meal",
      "natural-flavors",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "zinc-methionine-complex",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "dried-aspergillus-oryzae-fermentation-extract",
      "dried-trichoderma-longibrachiatum-fermentation-extract",
      "bacillus-subtilis-fermentation",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "vegetable-oil",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid"
    ],
    "data-faqType": "",
    "data-sort": 9,
    "data-diet": "Grain-Free",
    "data-one": "Purpose Ultra Pro Grain Free",
    "data-alt": "Purpose Ultra Pro Grain Free",
    "data-brand": "Victor",
    "specs_price_per_bag": 80.99,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473132c96b2faf13543d38a1fbad71e89a66f?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Ultra Pro Grain Free Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 42,
    "ga_crude_fat_%": 22,
    "ga_crude_fiber_%": 3.4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3890,
    "ga_kcals_per_cup": 414,
    "diets_multiselect": [
      "Grain Free"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 30,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Select Chicken Meal Sweet",
    "Slug": "compare-victor-select-chicken-meal-sweet-ingredients",
    "canonical": "compare-victor-select-chicken-meal-sweet-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a781bb11284b09124f4f",
    "calcSlug": "victor-select-chicken-meal-sweet",
    "typed_intro": "",
    "diets_slugs": [
      "grain-free"
    ],
    "itemId": "120711",
    "itemName": "Victor Select Chicken Meal Sweet",
    "item-subtitle": "",
    "itemRecordId": "recbrOrtlhyEFLJqx",
    "all_ingredients-calc-slugs": [
      "chicken-meal",
      "peas",
      "chicken-fat",
      "garbanzo-beans",
      "sweet-potatoes",
      "yeast-cultures",
      "blood-meal",
      "menhaden-fish-meal",
      "alfalfa-meal",
      "natural-flavors",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "zinc-methionine-complex",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "dried-aspergillus-oryzae-fermentation-extract",
      "dried-trichoderma-longibrachiatum-fermentation-extract",
      "bacillus-subtilis-fermentation",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "vegetable-oil",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid"
    ],
    "data-faqType": "",
    "data-sort": 10,
    "data-diet": "Grain-Free",
    "data-one": "Select Chicken Meal Sweet",
    "data-alt": "Select Chicken Meal Sweet",
    "data-brand": "Victor",
    "specs_price_per_bag": 77.49,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313be3207e10c504765a61fb803c4eb5e90?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Chicken Meal Sweet Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 33,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3744,
    "ga_kcals_per_cup": 398,
    "diets_multiselect": [
      "Grain Free"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 30,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Purpose Nutra Pro Dry Dog Food",
    "Slug": "compare-victor-purpose-nutra-pro-dry-dog-food-ingredients",
    "canonical": "compare-victor-purpose-nutra-pro-dry-dog-food-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7812da81548f63e88e5",
    "calcSlug": "victor-purpose-nutra-pro-dry-dog-food",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "129281",
    "itemName": "Victor Purpose Nutra Pro Dry Dog Food",
    "item-subtitle": "",
    "itemRecordId": "rec8OgezfHbGRboNN",
    "all_ingredients-calc-slugs": [
      "chicken-meal",
      "blood-meal",
      "millet",
      "chicken-fat",
      "yeast-cultures",
      "sorghum",
      "menhaden-fish-meal",
      "beef-meal",
      "alfalfa-meal",
      "natural-flavors",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "zinc-methionine-complex",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "dried-aspergillus-oryzae-fermentation-extract",
      "dried-trichoderma-longibrachiatum-fermentation-extract",
      "bacillus-subtilis-fermentation",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "vegetable-oil",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid"
    ],
    "data-faqType": "",
    "data-sort": 11,
    "data-diet": "Grain",
    "data-one": "Purpose Nutra Pro Dry Dog Food",
    "data-alt": "Purpose Nutra Pro Dry Dog Food",
    "data-brand": "Victor",
    "specs_price_per_bag": 76.59,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473138c25caa99a19448db80ac5b30ee8b6e9?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Nutra Pro Dry Dog Food Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 38,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 3.5,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3774,
    "ga_kcals_per_cup": 399,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 40,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Farmina Nd Ancestral Grain Chicken",
    "Slug": "compare-farmina-nd-ancestral-grain-chicken-ingredients",
    "canonical": "compare-farmina-nd-ancestral-grain-chicken-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a78190772361803ac75c",
    "calcSlug": "farmina-nd-ancestral-grain-chicken",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "202214",
    "itemName": "Farmina Nd Ancestral Grain Chicken",
    "item-subtitle": "",
    "itemRecordId": "recurrQnBRJ0CD0xM",
    "all_ingredients-calc-slugs": [
      "chicken",
      "spelt",
      "oats",
      "chicken-fat",
      "eggs",
      "fresh-herring",
      "herring",
      "beet-pulp",
      "herring-oil",
      "carrots",
      "alfalfa-meal",
      "inulin",
      "fructooligosaccharides",
      "yeast-extracts",
      "pomegranates",
      "apples",
      "spinach",
      "psyllium-seed-husk",
      "dried-sweet-orange",
      "blueberries",
      "salt",
      "brewers-yeast",
      "turmeric",
      "glucosamine",
      "chondroitin-sulfate",
      "vitamin-a-supplement",
      "vitamin-d3-supplement",
      "vitamin-e-supplement",
      "ascorbic-acid",
      "niacin",
      "calcium-pantothenate",
      "riboflavin",
      "pyridoxine-hydrochloride",
      "thiamine-mononitrate",
      "biotin",
      "folic-acid",
      "vitamin-b12-supplement",
      "choline-chloride",
      "beta-carotene",
      "zinc-methionine-hydroxy-analogue-chelate",
      "manganese-methionine-hydroxy-analogue-chelate",
      "ferrous-glycine",
      "copper-methionine-hydroxy-analogue-chelate",
      "selenium-yeast",
      "dl-methionine",
      "taurine",
      "l-carnitine",
      "aloe-vera-gel-concentrate",
      "green-tea-extract",
      "rosemary-extract",
      "mixed-tocopherols"
    ],
    "data-faqType": "",
    "data-sort": 12,
    "data-diet": "Grain",
    "data-one": "Nd Ancestral Grain Chicken",
    "data-alt": "Nd Ancestral Grain Chicken",
    "data-brand": "Farmina",
    "specs_price_per_bag": 84.99,
    "brandId": "Farmina",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313a81707890b32423d9e477632a8ac09a8?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Chicken Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3997,
    "ga_kcals_per_cup": 400,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 26.5,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Farmina Nd Ancestral Grain Lamb",
    "Slug": "compare-farmina-nd-ancestral-grain-lamb-ingredients",
    "canonical": "compare-farmina-nd-ancestral-grain-lamb-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7810fefebdd76a5236a",
    "calcSlug": "farmina-nd-ancestral-grain-lamb",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "234247",
    "itemName": "Farmina Nd Ancestral Grain Lamb",
    "item-subtitle": "",
    "itemRecordId": "recZZ2pxasvzJKV40",
    "all_ingredients-calc-slugs": [
      "lamb",
      "spelt",
      "oats",
      "chicken-fat",
      "herring",
      "eggs",
      "beet-pulp",
      "herring-oil",
      "carrots",
      "alfalfa-meal",
      "chicken-cartilage",
      "inulin",
      "fructooligosaccharides",
      "yeast-extracts",
      "blueberries",
      "spinach",
      "psyllium-seed-husk",
      "apples",
      "dried-sweet-orange",
      "pomegranates",
      "salt",
      "brewers-yeast",
      "turmeric",
      "vitamin-a-supplement",
      "vitamin-d3-supplement",
      "vitamin-e-supplement",
      "ascorbic-acid",
      "niacin",
      "calcium-pantothenate",
      "riboflavin",
      "pyridoxine-hydrochloride",
      "thiamine-mononitrate",
      "biotin",
      "folic-acid",
      "vitamin-b12-supplement",
      "choline-chloride",
      "beta-carotene",
      "zinc-methionine-hydroxy-analogue-chelate",
      "manganese-methionine-hydroxy-analogue-chelate",
      "ferrous-glycine",
      "copper-methionine-hydroxy-analogue-chelate",
      "selenium-yeast",
      "dl-methionine",
      "taurine",
      "l-carnitine",
      "aloe-vera-gel-concentrate",
      "green-tea-extract",
      "rosemary-extract",
      "mixed-tocopherols"
    ],
    "data-faqType": "",
    "data-sort": 13,
    "data-diet": "Grain",
    "data-one": "Nd Ancestral Grain Lamb",
    "data-alt": "Nd Ancestral Grain Lamb",
    "data-brand": "Farmina",
    "specs_price_per_bag": 99.99,
    "brandId": "Farmina",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313f4d91c42071c4e419ff6c7590742983d?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Lamb Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 35,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 1.7,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3414,
    "ga_kcals_per_cup": 437,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 26.5,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Victor Realtree Max 5 Pro Dry Dog",
    "Slug": "compare-victor-realtree-max-5-pro-dry-dog-ingredients",
    "canonical": "compare-victor-realtree-max-5-pro-dry-dog-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a78193726ed1bc52d05b",
    "calcSlug": "victor-realtree-max-5-pro-dry-dog",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "279306",
    "itemName": "Victor Realtree Max 5 Pro Dry Dog",
    "item-subtitle": "",
    "itemRecordId": "rech8XpJSdzgzbjXu",
    "all_ingredients-calc-slugs": [
      "beef-meal",
      "sorghum",
      "chicken-fat",
      "natural-flavors",
      "brown-rice",
      "menhaden-fish-meal",
      "alfalfa-meal",
      "duck-meal",
      "potassium-chloride",
      "carrot-powder",
      "tomato-pomace",
      "salt",
      "flaxseed-meal",
      "seaweed-meal",
      "taurine",
      "choline-chloride",
      "calcium-stearate",
      "egg-product",
      "zinc-methionine-complex",
      "glucosamine-hydrochloride",
      "vitamin-e-supplement",
      "iron-amino-acids-complex",
      "hydrolyzed-yeast",
      "cranberry-powder",
      "chondroitin-sulfate",
      "manganese-amino-acids-complex",
      "silicon-dioxide",
      "blueberries",
      "l-carnitine",
      "selenium-yeast",
      "brewers-yeast",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "dried-aspergillus-oryzae-fermentation-extract",
      "dried-trichoderma-longibrachiatum-fermentation-extract",
      "bacillus-subtilis-fermentation",
      "copper-sulfate",
      "niacin",
      "vitamin-b12-supplement",
      "vitamin-a-supplement",
      "d-calcium-pantothenate",
      "thiamine-mononitrate",
      "biotin",
      "yucca-schidigera-extract",
      "calcium-carbonate",
      "riboflavin-supplement",
      "calcium-iodate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "tetrasodium-pyrophosphate",
      "vegetable-oil",
      "rosemary-extract",
      "green-tea-extract",
      "spearmint-extract",
      "inulin",
      "lecithin",
      "folic-acid"
    ],
    "data-faqType": "",
    "data-sort": 14,
    "data-diet": "Grain",
    "data-one": "Realtree Max 5 Pro Dry Dog",
    "data-alt": "Realtree Max 5 Pro Dry Dog",
    "data-brand": "Victor",
    "specs_price_per_bag": 68.49,
    "brandId": "Victor",
    "brands": "Victor",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473137116eeb638a44c8d838be1c48cfc5c45?version=1.0&width=2046&height=1536",
    "previewAlttag": "Realtree Max 5 Pro Dry Dog Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3794,
    "ga_kcals_per_cup": 403,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 40,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Acana Singles Limited Ingredient Diet",
    "Slug": "compare-acana-singles-limited-ingredient-diet-ingredients",
    "canonical": "compare-acana-singles-limited-ingredient-diet-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7816fec0964ccfcfa93",
    "calcSlug": "acana-singles-limited-ingredient-diet",
    "typed_intro": "",
    "diets_slugs": [
      "grain-free"
    ],
    "itemId": "285973",
    "itemName": "Acana Singles Limited Ingredient Diet",
    "item-subtitle": "",
    "itemRecordId": "recVXP10iAQ0yJa3L",
    "all_ingredients-calc-slugs": [
      "beef",
      "beef-meal",
      "beef-liver",
      "sweet-potatoes",
      "chickpeas",
      "beef-fat",
      "lentils",
      "pumpkin",
      "fish-oil",
      "lentil-fiber",
      "natural-flavors",
      "beef-tripe",
      "cranberries",
      "salt",
      "choline-chloride",
      "taurine",
      "kelp",
      "vitamin-e-supplement",
      "zinc-proteinate",
      "mixed-tocopherols",
      "vitamin-d3-supplement",
      "niacin",
      "thiamine-mononitrate",
      "calcium-pantothenate",
      "pyridoxine-hydrochloride",
      "riboflavin",
      "folic-acid",
      "vitamin-b12-supplement",
      "copper-proteinate",
      "chicory-root",
      "turmeric",
      "citric-acid",
      "rosemary-extract",
      "lactobacillus-acidophilus-fermentation",
      "bifidobacterium-animalis-fermentation",
      "lactobacillus-casei-fermentation"
    ],
    "data-faqType": "",
    "data-sort": 15,
    "data-diet": "Grain-Free",
    "data-one": "Singles Limited Ingredient Diet",
    "data-alt": "Singles Limited Ingredient Diet",
    "data-brand": "Acana",
    "specs_price_per_bag": 97.99,
    "brandId": "Acana",
    "brands": "Acana",
    "brandDisplay": "Acana",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473133da27f6ef89f47309fdd379884287a5b?version=1.0&width=2046&height=1536",
    "previewAlttag": "Singles Limited Ingredient Diet Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 31,
    "ga_crude_fat_%": 17,
    "ga_crude_fiber_%": 5,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3405,
    "ga_kcals_per_cup": 388,
    "diets_multiselect": [
      "Grain Free"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 22.5,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Purina Pro Plan Specialized Beef Rice",
    "Slug": "compare-purina-pro-plan-specialized-beef-rice-ingredients",
    "canonical": "compare-purina-pro-plan-specialized-beef-rice-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7819c270652d7a81d3f",
    "calcSlug": "purina-pro-plan-specialized-beef-rice",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "298045",
    "itemName": "Purina Pro Plan Specialized Beef Rice",
    "item-subtitle": "",
    "itemRecordId": "rec587UBLjMYZ41B2",
    "all_ingredients-calc-slugs": [
      "beef",
      "rice",
      "corn-protein-meal",
      "corn",
      "poultry-by-product",
      "wheat",
      "barley",
      "beef-fat",
      "corn-germ-meal",
      "fish-meal",
      "egg-product",
      "natural-flavors",
      "fish-oil",
      "wheat-bran",
      "calcium-carbonate",
      "soybean-oil",
      "potassium-chloride",
      "salt",
      "mono-and-dicalcium-phosphate",
      "potassium-citrate",
      "niacin",
      "vitamin-a-supplement",
      "calcium-pantothenate",
      "thiamine-mononitrate",
      "vitamin-b12-supplement",
      "riboflavin-supplement",
      "pyridoxine-hydrochloride",
      "folic-acid",
      "menadione-sodium-bisulfite-complex-(vitamin-k)",
      "vitamin-d3-supplement",
      "biotin",
      "choline-chloride",
      "ferrous-sulfate",
      "manganese-sulfate",
      "copper-sulfate",
      "calcium-iodate",
      "sodium-selenite",
      "glucosamine-hydrochloride",
      "taurine",
      "dried-bacillus-coagulans-fermentation-product",
      "l-lysine-monohydrochloride"
    ],
    "data-faqType": "",
    "data-sort": 16,
    "data-diet": "Grain",
    "data-one": "Specialized Beef Rice",
    "data-alt": "Specialized Beef Rice",
    "data-brand": "Purina Pro Plan",
    "specs_price_per_bag": 77.48,
    "brandId": "Purina Pro Plan",
    "brands": "Purina Pro Plan",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xcc58fac5e0664d969a12cdaa8c2063da?version=1.0&width=2046&height=1536",
    "previewAlttag": "Specialized Beef Rice Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 26,
    "ga_crude_fat_%": 12,
    "ga_crude_fiber_%": 4.5,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 4018.867924528302,
    "ga_kcals_per_cup": 426,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 34,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Dr Tims Active Dog Pursuit Formula",
    "Slug": "compare-dr-tims-active-dog-pursuit-formula-ingredients",
    "canonical": "compare-dr-tims-active-dog-pursuit-formula-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a77f22684ab14fd4ae63",
    "calcSlug": "dr-tims-active-dog-pursuit-formula",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "37811",
    "itemName": "Dr Tims Active Dog Pursuit Formula",
    "item-subtitle": "",
    "itemRecordId": "recIo33SmIRRx52rl",
    "all_ingredients-calc-slugs": [
      "chicken-meal",
      "brown-rice",
      "chicken-fat",
      "oats",
      "beet-pulp",
      "egg-product",
      "rice-bran",
      "menhaden-fish-oil",
      "herring-meal",
      "flaxseed",
      "catfish-meal",
      "natural-flavors",
      "porcine-plasma",
      "salmon-meal",
      "l-ascorbyl-2-polyphosphate",
      "biotin",
      "niacin",
      "d-calcium-pantothenate",
      "riboflavin-supplement",
      "vitamin-a-supplement",
      "thiamine-mononitrate",
      "pyridoxine-hydrochloride",
      "vitamin-d3-supplement",
      "vitamin-b12-supplement",
      "folic-acid",
      "potassium-chloride",
      "lecithin",
      "dl-methionine",
      "l-lysine",
      "zinc-sulfate",
      "iron-proteinate",
      "ferrous-sulfate",
      "copper-proteinate",
      "copper-sulfate",
      "zinc-proteinate",
      "manganese-proteinate",
      "sodium-selenite",
      "manganous-oxide",
      "kelp",
      "salt",
      "chicory-root",
      "choline-chloride",
      "taurine",
      "psyllium-seed-husk",
      "yucca-schidigera-extract",
      "l-carnitine",
      "dried-bacillus-coagulans-fermentation-product"
    ],
    "data-faqType": "",
    "data-sort": 17,
    "data-diet": "Grain",
    "data-one": "Active Dog Pursuit Formula",
    "data-alt": "Active Dog Pursuit Formula",
    "data-brand": "Dr Tims",
    "specs_price_per_bag": 119.99,
    "brandId": "Dr Tims",
    "brands": "Dr Tims",
    "brandDisplay": "Dr Tims",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731352dfcbfd5c23482c8525478b17031dfd?version=1.0&width=2046&height=1536",
    "previewAlttag": "Active Dog Pursuit Formula Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 4036,
    "ga_kcals_per_cup": 516,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 40,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Purina Pro Plan High Protein Chicken",
    "Slug": "compare-purina-pro-plan-high-protein-chicken-ingredients",
    "canonical": "compare-purina-pro-plan-high-protein-chicken-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a780edf22a5c4a7f1122",
    "calcSlug": "purina-pro-plan-high-protein-chicken",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "52423",
    "itemName": "Purina Pro Plan High Protein Chicken",
    "item-subtitle": "",
    "itemRecordId": "recIVlN33V7TQjQ7M",
    "all_ingredients-calc-slugs": [
      "chicken",
      "rice",
      "corn-gluten-meal",
      "corn",
      "poultry-by-product",
      "wheat",
      "beef-fat",
      "pea-fiber",
      "egg-product",
      "fish-meal",
      "natural-flavors",
      "fish-oil",
      "soybean-oil",
      "mono-and-dicalcium-phosphate",
      "salt",
      "calcium-carbonate",
      "potassium-chloride",
      "potassium-citrate",
      "choline-chloride",
      "l-lysine-monohydrochloride",
      "ferrous-sulfate",
      "manganese-sulfate",
      "copper-sulfate",
      "calcium-iodate",
      "sodium-selenite",
      "niacin",
      "vitamin-a-supplement",
      "calcium-pantothenate",
      "thiamine-mononitrate",
      "vitamin-b12-supplement",
      "riboflavin-supplement",
      "pyridoxine-hydrochloride",
      "folic-acid",
      "menadione-sodium-bisulfite-complex-(vitamin-k)",
      "vitamin-d3-supplement",
      "biotin",
      "garlic-oil"
    ],
    "data-faqType": "",
    "data-sort": 18,
    "data-diet": "Grain",
    "data-one": "High Protein Chicken",
    "data-alt": "High Protein Chicken",
    "data-brand": "Purina Pro Plan",
    "specs_price_per_bag": 74.98,
    "brandId": "Purina Pro Plan",
    "brands": "Purina Pro Plan",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731323751dbf15d74616b0874004f31d4912?version=1.0&width=2046&height=1536",
    "previewAlttag": "High Protein Chicken Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 28,
    "ga_crude_fat_%": 13,
    "ga_crude_fiber_%": 4.75,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3934,
    "ga_kcals_per_cup": 419,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 34,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Purina Pro Plan High Protein Shredded",
    "Slug": "compare-purina-pro-plan-high-protein-shredded-ingredients",
    "canonical": "compare-purina-pro-plan-high-protein-shredded-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7801e484e2da49d8ddc",
    "calcSlug": "purina-pro-plan-high-protein-shredded",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "52445",
    "itemName": "Purina Pro Plan High Protein Shredded",
    "item-subtitle": "",
    "itemRecordId": "recsBJUrKKf2mVLQG",
    "all_ingredients-calc-slugs": [
      "chicken",
      "rice",
      "wheat",
      "poultry-by-product",
      "corn",
      "soybean-meal",
      "beef-fat",
      "corn-protein-meal",
      "egg-product",
      "natural-flavors",
      "beet-pulp",
      "glycerin",
      "mono-and-dicalcium-phosphate",
      "wheat-bran",
      "calcium-carbonate",
      "fish-meal",
      "salt",
      "soybean-oil",
      "potassium-chloride",
      "zinc-proteinate",
      "ferrous-sulfate",
      "manganese-proteinate",
      "copper-proteinate",
      "calcium-iodate",
      "sodium-selenite",
      "vitamin-e-supplement",
      "niacin",
      "thiamine-mononitrate",
      "calcium-pantothenate",
      "vitamin-a-supplement",
      "riboflavin-supplement",
      "vitamin-b12-supplement",
      "pyridoxine-hydrochloride",
      "folic-acid",
      "menadione-sodium-bisulfite-complex-(vitamin-k)",
      "biotin",
      "vitamin-d3-supplement",
      "choline-chloride",
      "dried-bacillus-coagulans-fermentation-product",
      "l-lysine-monohydrochloride"
    ],
    "data-faqType": "",
    "data-sort": 19,
    "data-diet": "Grain",
    "data-one": "High Protein Shredded",
    "data-alt": "High Protein Shredded",
    "data-brand": "Purina Pro Plan",
    "specs_price_per_bag": 74.48,
    "brandId": "Purina Pro Plan",
    "brands": "Purina Pro Plan",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473132af6116f0e2742cba64632286e85426f?version=1.0&width=2046&height=1536",
    "previewAlttag": "High Protein Shredded Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 26,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3790,
    "ga_kcals_per_cup": 369,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 35,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Eukanuba Adult Large Breed Dry Dog",
    "Slug": "compare-eukanuba-adult-large-breed-dry-dog-ingredients",
    "canonical": "compare-eukanuba-adult-large-breed-dry-dog-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7819aba47e523965ce6",
    "calcSlug": "eukanuba-adult-large-breed-dry-dog",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "552422",
    "itemName": "Eukanuba Adult Large Breed Dry Dog",
    "item-subtitle": "",
    "itemRecordId": "recAmx4ma56VRQ37e",
    "all_ingredients-calc-slugs": [
      "chicken",
      "corn",
      "chicken-by-product-meal",
      "wheat",
      "sorghum",
      "chicken-fat",
      "natural-flavors",
      "beet-pulp",
      "egg-product",
      "potassium-chloride",
      "calcium-carbonate",
      "sodium-hexametaphosphate",
      "salt",
      "fructooligosaccharides",
      "fish-oil",
      "choline-chloride",
      "biotin",
      "d-calcium-pantothenate",
      "vitamin-a-acetate",
      "niacin",
      "pyridoxine-hydrochloride",
      "thiamine-mononitrate",
      "vitamin-b12-supplement",
      "riboflavin-supplement",
      "vitamin-d3-supplement",
      "folic-acid",
      "dl-methionine",
      "glucosamine-hydrochloride",
      "ferrous-sulfate",
      "copper-sulfate",
      "sodium-selenite",
      "manganous-oxide",
      "chondroitin-sulfate",
      "rosemary-extract",
      "preserved-with-mixed-tocopherols-and-citric-acid."
    ],
    "data-faqType": "",
    "data-sort": 20,
    "data-diet": "Grain",
    "data-one": " Adult Large Breed Dry Dog",
    "data-alt": " Adult Large Breed Dry Dog",
    "data-brand": "Eukanuba",
    "specs_price_per_bag": 77.99,
    "brandId": "Eukanuba",
    "brands": "Eukanuba",
    "brandDisplay": "Eukanuba",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9x439c2566aba841b68d82073c26688034?version=1.0&width=2046&height=1536",
    "previewAlttag": " Adult Large Breed Dry Dog Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 23,
    "ga_crude_fat_%": 13,
    "ga_crude_fiber_%": 3.9,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3122.6415094339623,
    "ga_kcals_per_cup": 331,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 30,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Farmina Nd Ancestral Grain Chicken",
    "Slug": "compare-farmina-nd-ancestral-grain-chicken-ingredients",
    "canonical": "compare-farmina-nd-ancestral-grain-chicken-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a7802f97b02373abb75e",
    "calcSlug": "farmina-nd-ancestral-grain-chicken",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "55909",
    "itemName": "Farmina Nd Ancestral Grain Chicken",
    "item-subtitle": "",
    "itemRecordId": "recMAiEuPgWvylbmZ",
    "all_ingredients-calc-slugs": [
      "chicken",
      "spelt",
      "oats",
      "chicken-fat",
      "eggs",
      "fresh-herring",
      "herring",
      "beet-pulp",
      "herring-oil",
      "carrots",
      "alfalfa-meal",
      "inulin",
      "fructooligosaccharides",
      "yeast-extracts",
      "pomegranates",
      "apples",
      "spinach",
      "psyllium-seed-husk",
      "dried-sweet-orange",
      "blueberries",
      "salt",
      "brewers-yeast",
      "turmeric",
      "glucosamine",
      "chondroitin-sulfate",
      "vitamin-a-supplement",
      "vitamin-d3-supplement",
      "vitamin-e-supplement",
      "ascorbic-acid",
      "niacin",
      "calcium-pantothenate",
      "riboflavin",
      "pyridoxine-hydrochloride",
      "thiamine-mononitrate",
      "biotin",
      "folic-acid",
      "vitamin-b12-supplement",
      "choline-chloride",
      "beta-carotene",
      "zinc-methionine-hydroxy-analogue-chelate",
      "manganese-methionine-hydroxy-analogue-chelate",
      "ferrous-glycine",
      "copper-methionine-hydroxy-analogue-chelate",
      "selenium-yeast",
      "dl-methionine",
      "taurine",
      "l-carnitine",
      "aloe-vera-gel-concentrate",
      "green-tea-extract",
      "rosemary-extract",
      "mixed-tocopherols"
    ],
    "data-faqType": "",
    "data-sort": 21,
    "data-diet": "Grain",
    "data-one": "Nd Ancestral Grain Chicken",
    "data-alt": "Nd Ancestral Grain Chicken",
    "data-brand": "Farmina",
    "specs_price_per_bag": 84.99,
    "brandId": "Farmina",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731310f78da65bbe4e7fb85986f5d65c1409?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Chicken Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3997,
    "ga_kcals_per_cup": 400,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Poultry",
    "specs_bag-size_lbs": 26.5,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Farmina Nd Ocean Codfish Orange",
    "Slug": "compare-farmina-nd-ocean-codfish-orange-ingredients",
    "canonical": "compare-farmina-nd-ocean-codfish-orange-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a77fb97bea2686617764",
    "calcSlug": "farmina-nd-ocean-codfish-orange",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "55911",
    "itemName": "Farmina Nd Ocean Codfish Orange",
    "item-subtitle": "",
    "itemRecordId": "recO3o4bOV3H9GlFf",
    "all_ingredients-calc-slugs": [
      "cod",
      "herring-oil",
      "spelt",
      "oats",
      "beet-pulp",
      "carrots",
      "alfalfa-meal",
      "inulin",
      "fructooligosaccharides",
      "yeast-extracts",
      "dried-sweet-orange",
      "apples",
      "pomegranates",
      "spinach",
      "psyllium-seed-husk",
      "blueberries",
      "salt",
      "brewers-yeast",
      "turmeric",
      "glucosamine-hydrochloride",
      "chondroitin-sulfate",
      "vitamin-a-supplement",
      "vitamin-d3-supplement",
      "vitamin-e-supplement",
      "ascorbic-acid",
      "niacin",
      "calcium-pantothenate",
      "riboflavin",
      "pyridoxine-hydrochloride",
      "thiamine-mononitrate",
      "biotin",
      "folic-acid",
      "vitamin-b12-supplement",
      "choline-chloride",
      "beta-carotene",
      "zinc-methionine-hydroxy-analogue-chelate",
      "manganese-methionine-hydroxy-analogue-chelate",
      "ferrous-glycine",
      "copper-methionine-hydroxy-analogue-chelate",
      "selenium-yeast",
      "dl-methionine",
      "taurine",
      "l-carnitine",
      "aloe-vera-gel-concentrate",
      "green-tea-extract",
      "rosemary-extract",
      "mixed-tocopherols"
    ],
    "data-faqType": "",
    "data-sort": 22,
    "data-diet": "Grain",
    "data-one": "Nd Ocean Codfish Orange",
    "data-alt": "Nd Ocean Codfish Orange",
    "data-brand": "Farmina",
    "specs_price_per_bag": 99.99,
    "brandId": "Farmina",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473133c1341cf43ea4d198d4e3de201225bfa?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ocean Codfish Orange Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3125,
    "ga_kcals_per_cup": 400,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Fish",
    "specs_bag-size_lbs": 26.5,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  },
  {
    "Name": "Solid Gold Nutrient Boost Wolf King",
    "Slug": "compare-solid-gold-nutrient-boost-wolf-king-ingredients",
    "canonical": "compare-solid-gold-nutrient-boost-wolf-king-ingredients",
    "Collection ID": {
      "id": "selvRoHOxAwFlz8CB",
      "name": "647ddb9037101ce399b330b4",
      "color": "blueLight2"
    },
    "Item ID": "6844a781faabc6e39ed1d7b9",
    "calcSlug": "solid-gold-nutrient-boost-wolf-king",
    "typed_intro": "",
    "diets_slugs": [
      "grain-inclusive"
    ],
    "itemId": "841846",
    "itemName": "Solid Gold Nutrient Boost Wolf King",
    "item-subtitle": "",
    "itemRecordId": "recJuEt1QWhaZnvFY",
    "all_ingredients-calc-slugs": [
      "bison",
      "oceanfish-meal",
      "brown-rice",
      "oatmeal",
      "pearled-barley",
      "chickpeas",
      "peas",
      "potatoes",
      "eggs",
      "sweet-potatoes",
      "flaxseed",
      "tomato-pomace",
      "chicken-fat",
      "natural-flavors",
      "salmon-oil",
      "carrots",
      "pumpkin",
      "ferrous-sulfate",
      "copper-sulfate",
      "manganese-sulfate",
      "zinc-proteinate",
      "manganese-proteinate",
      "copper-proteinate",
      "sodium-selenite",
      "niacin",
      "calcium-pantothenate",
      "riboflavin",
      "pyridoxine-hydrochloride",
      "thiamine-mononitrate",
      "vitamin-a-supplement",
      "vitamin-b12-supplement",
      "vitamin-d3-supplement",
      "biotin",
      "folic-acid",
      "blueberries",
      "cranberries",
      "choline-chloride",
      "chicory-root",
      "taurine",
      "rosemary-extract",
      "dried-bacillus-coagulans-fermentation-product."
    ],
    "data-faqType": "",
    "data-sort": 23,
    "data-diet": "Grain",
    "data-one": "Nutrient Boost Wolf King",
    "data-alt": "Nutrient Boost Wolf King",
    "data-brand": "Solid Gold",
    "specs_price_per_bag": 79.99,
    "brandId": "Solid Gold",
    "brands": "Solid Gold",
    "brandDisplay": "Solid Gold",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xc275aeaaead6465abf3987c34513b166?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nutrient Boost Wolf King Dog Food Bag",
    "item-status": "",
    "ga_crude_protein_%": 22,
    "ga_crude_fat_%": 9,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3207.547169811321,
    "ga_kcals_per_cup": 340,
    "diets_multiselect": [
      "Grain Inclusive"
    ],
    "specs_primary_flavor": "Meat",
    "specs_bag-size_lbs": 22,
    "manual_faq_enabled": "",
    "section-h1": "",
    "section-name": "",
    "persona_context": "",
    "tone_override_subtitle": "",
    "tone_override_tagline": "",
    "section-p": "",
    "section-prompt": ""
  }
]
