
[
  {
    "Name": "Eukanuba Adult Large Breed Dry Dog",
    "Slug": "compare-eukanuba-adult-large-breed-dry-dog-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5dac7d154f53ae1b06e",
    "canonical": "compare-eukanuba-adult-large-breed-dry-dog-ingredients",
    "recordId": "recAmx4ma56VRQ37e",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "eukanuba-adult-large-breed-dry-dog",
    "itemId": "552422",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Eukanuba Adult Large Breed Dry Dog",
    "data-five": "552422",
    "data-sort": 20,
    "data-one": " Adult Large Breed Dry Dog",
    "data-brand": "Eukanuba",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "6734",
    "brandDisplay": "Eukanuba",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9x439c2566aba841b68d82073c26688034?version=1.0&width=2046&height=1536",
    "previewAlttag": " Adult Large Breed Dry Dog Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "6734",
    "img-data-five": "552422",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "IULX1",
      "MDIZK",
      "I1FXE",
      "JGOFI",
      "INGB4",
      "VUYIW",
      "Z9I0H",
      "TDEIO",
      "ZTMYL",
      "AH4GG",
      "KZC6H",
      "GJA6Y",
      "9UMLW",
      "4GUVA",
      "RD1WV",
      "QKPNY",
      "UTGPV",
      "YD8CG",
      "SQ0XJ",
      "HBTUA",
      "YRWGG",
      "MLAA7",
      "YHGZY",
      "QX1UZ",
      "COVUX",
      "COCPI",
      "MBFOA",
      "SIPQU",
      "V43XM",
      "MBU30",
      "BOL4J",
      "555IX",
      "OQE8V",
      "SCYOC",
      "LDMXN",
      "9WQMN",
      "L5O6A",
      "7YYYV"
    ],
    "cont-data-fives": [
      "I1FXE",
      "ZTMYL",
      "TDEIO",
      "VUYIW",
      "MDIZK",
      "RD1WV",
      "JGOFI"
    ],
    "cf-data-five": 552422,
    "specs_price_per_bag": 77.99,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 23,
    "tag_kcalscup": "low",
    "tag_fat": "low",
    "tag_protein": "low",
    "ga_crude_fat_%": 13,
    "ga_crude_fiber_%": 3.9,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3122.6415094339623,
    "ga_kcals_per_cup": 331
  },
  {
    "Name": "Solid Gold Nutrient Boost Wolf King",
    "Slug": "compare-solid-gold-nutrient-boost-wolf-king-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5da017813e2adf6d3a8",
    "canonical": "compare-solid-gold-nutrient-boost-wolf-king-ingredients",
    "recordId": "recJuEt1QWhaZnvFY",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "solid-gold-nutrient-boost-wolf-king",
    "itemId": "841846",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Solid Gold Nutrient Boost Wolf King",
    "data-five": "841846",
    "data-sort": 23,
    "data-one": "Nutrient Boost",
    "data-brand": "Solid Gold",
    "data-diet": "Grain",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7536",
    "brandDisplay": "Solid Gold",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xc275aeaaead6465abf3987c34513b166?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nutrient Boost Wolf King Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7536",
    "img-data-five": "841846",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "2NZMY",
      "FVSVS",
      "GKL4J",
      "KEB4Z",
      "VFUPE",
      "5KHTT",
      "LJBTO",
      "K5VFA",
      "8ALHU",
      "5E1NB",
      "2LCAZ",
      "R7JU0",
      "IQCTZ",
      "F4SUG",
      "P46XM",
      "IIDS9",
      "4CQVY",
      "GXM84",
      "BOL4J",
      "555IX",
      "NRX8Q",
      "ZPGID",
      "BWNCE",
      "K3WTW",
      "OQE8V",
      "CDODO",
      "IP9OV",
      "DL4MS",
      "YRWGG",
      "UIC8H",
      "81XCU",
      "MLAA7",
      "YHGZY",
      "EKBTQ",
      "QX1UZ",
      "COCPI",
      "YD8CG",
      "LBF24",
      "XORST",
      "XUUYO",
      "QKPNY",
      "IQK4Z",
      "F1INB",
      "M0BM4",
      "L5O6A",
      "ZYKY5"
    ],
    "cont-data-fives": [
      "VFUPE",
      "8OTUY",
      "GKL4J",
      "VUYIW",
      "5KHTT",
      "LJBTO",
      "K5VFA",
      "BSL2E"
    ],
    "cf-data-five": 841846,
    "specs_price_per_bag": 79.99,
    "specs_bag-size_lbs": 22,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 22,
    "tag_kcalscup": "low",
    "tag_fat": "low",
    "tag_protein": "low",
    "ga_crude_fat_%": 9,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3207.547169811321,
    "ga_kcals_per_cup": 340
  },
  {
    "Name": "Purina Pro Plan High Protein Shredded",
    "Slug": "compare-purina-pro-plan-high-protein-shredded-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5da0ca4050d2f6ba64a",
    "canonical": "compare-purina-pro-plan-high-protein-shredded-ingredients",
    "recordId": "recsBJUrKKf2mVLQG",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "purina-pro-plan-high-protein-shredded",
    "itemId": "52445",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Purina Pro Plan High Protein Shredded",
    "data-five": "52445",
    "data-sort": 19,
    "data-one": "High Protein Shredded",
    "data-brand": "Purina Pro Plan",
    "data-diet": "Grain",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7434",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473132af6116f0e2742cba64632286e85426f?version=1.0&width=2046&height=1536",
    "previewAlttag": "High Protein Shredded Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7434",
    "img-data-five": "52445",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "IULX1",
      "CDQCK",
      "UYDPF",
      "QHDUJ",
      "OAYON",
      "GOURU",
      "PUVNB",
      "Q99OM",
      "8KBDY",
      "F4SUG",
      "1VEVT",
      "K4SWZ",
      "ORXDE",
      "G0IOG",
      "KZC6H",
      "SZ9O3",
      "9UMLW",
      "R8PIF",
      "AH4GG",
      "XGGOP",
      "BOL4J",
      "BWNCE",
      "K3WTW",
      "AWE1M",
      "AJI2E",
      "E87QO",
      "HUSPZ",
      "5EIKP",
      "7TSVX",
      "EKBTQ",
      "QZ09Z",
      "CPEN5",
      "2ZKIM",
      "B92D3",
      "HQCHY",
      "Q08LQ",
      "0EEFX",
      "QKPNY",
      "4GGMJ",
      "1THAG",
      "QISOK",
      "RANER"
    ],
    "cont-data-fives": [
      "QHDUJ",
      "ZTMYL",
      "MYRTC",
      "TDEIO",
      "MDIZK",
      "Q99OM",
      "SZ9O3",
      "CDQCK",
      "GOURU",
      "R8PIF",
      "JGOFI",
      "G0IOG"
    ],
    "cf-data-five": 52445,
    "specs_price_per_bag": 74.48,
    "specs_bag-size_lbs": 35,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 26,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3790,
    "ga_kcals_per_cup": 369
  },
  {
    "Name": "Victor Select Lamb Meal Brown Rice",
    "Slug": "compare-victor-select-lamb-meal-brown-rice-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d9f4c10c3b4738a159",
    "canonical": "compare-victor-select-lamb-meal-brown-rice-ingredients",
    "recordId": "recHWP48JBtTLPzIE",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-select-lamb-meal-brown-rice",
    "itemId": "120680",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Select Lamb Meal Brown Rice",
    "data-five": "120680",
    "data-sort": 4,
    "data-one": "Lamb Meal",
    "data-brand": "Victor",
    "data-diet": "Grain",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313974dbedb88c3499bb3770ed53a26bfac?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Lamb Meal Brown Rice Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "120680",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "B9RZP",
      "E9MIY",
      "VJD3I",
      "VUYIW",
      "LJBTO",
      "GE6GU",
      "RH9L7",
      "ETXUL",
      "BS8EA",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK"
    ],
    "cont-data-fives": [
      "PG8TP",
      "OOUXY",
      "LCALN",
      "GKL4J",
      "VUYIW",
      "LJBTO",
      "BSL2E",
      "HNLVZ"
    ],
    "cf-data-five": 120680,
    "specs_price_per_bag": 78.24,
    "specs_bag-size_lbs": 40,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 24,
    "tag_kcalscup": "low",
    "tag_fat": "low",
    "tag_protein": "low",
    "ga_crude_fat_%": 12,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3501,
    "ga_kcals_per_cup": 372
  },
  {
    "Name": "Victor Purpose Active Dog Puppy",
    "Slug": "compare-victor-purpose-active-dog-puppy-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d9654cf8b9ecae289b",
    "canonical": "compare-victor-purpose-active-dog-puppy-ingredients",
    "recordId": "recA5sadFi83r4I9Q",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-purpose-active-dog-puppy",
    "itemId": "120700",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Purpose Active Dog Puppy",
    "data-five": "120700",
    "data-sort": 6,
    "data-one": "Active Dog",
    "data-brand": "Victor",
    "data-diet": "Grain-Free",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "Grain Free",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313cd0b81f15619488b8f3a5a61031ee725?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Active Dog Puppy Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "120700",
    "sd-data-fives": "3A9NE",
    "ing-data-fives": [
      "GSJWC",
      "LJBTO",
      "G2YVH",
      "VUYIW",
      "5E1NB",
      "RH9L7",
      "LQRGM",
      "ETXUL",
      "BS8EA",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "7JYFL",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "MBFOA",
      "4GGMJ",
      "6GX4D"
    ],
    "cont-data-fives": [
      "G2YVH",
      "PG8TP",
      "OOUXY",
      "LCALN",
      "VUYIW",
      "LNUMU",
      "LJBTO",
      "BSL2E"
    ],
    "cf-data-five": 120700,
    "specs_price_per_bag": 70.29,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 33,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3614,
    "ga_kcals_per_cup": 384
  },
  {
    "Name": "Victor Purpose Hero Grain Free Dry",
    "Slug": "compare-victor-purpose-hero-grain-free-dry-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d99cc817e5629994eb",
    "canonical": "compare-victor-purpose-hero-grain-free-dry-ingredients",
    "recordId": "rechhhtL9ySIeIiO6",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-purpose-hero-grain-free-dry",
    "itemId": "120702",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Purpose Hero Grain Free Dry",
    "data-five": "120702",
    "data-sort": 7,
    "data-one": "Hero",
    "data-brand": "Victor",
    "data-diet": "Grain-Free",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "Grain Free",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313c9733e62fcd14c949e2bfd02367b4efe?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Hero Grain Free Dry Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "120702",
    "sd-data-fives": "3A9NE",
    "ing-data-fives": [
      "GSJWC",
      "LJBTO",
      "V9APU",
      "VUYIW",
      "LQRGM",
      "RH9L7",
      "G2YVH",
      "H0NSG",
      "ETXUL",
      "BS8EA",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "V43XM",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "9WQMN",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK"
    ],
    "cont-data-fives": [
      "G2YVH",
      "PG8TP",
      "OOUXY",
      "LCALN",
      "VUYIW",
      "LNUMU",
      "LJBTO",
      "BSL2E",
      "HNLVZ"
    ],
    "cf-data-five": 120702,
    "specs_price_per_bag": 70.29,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 33,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3614,
    "ga_kcals_per_cup": 384
  },
  {
    "Name": "Acana Singles Limited Ingredient Diet",
    "Slug": "compare-acana-singles-limited-ingredient-diet-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5dae1a7eb596c1fb346",
    "canonical": "compare-acana-singles-limited-ingredient-diet-ingredients",
    "recordId": "recVXP10iAQ0yJa3L",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "acana-singles-limited-ingredient-diet",
    "itemId": "285973",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Acana Singles Limited Ingredient Diet",
    "data-five": "285973",
    "data-sort": 15,
    "data-one": "Singles LID",
    "data-brand": "Acana",
    "data-diet": "Grain-Free",
    "data-legumes": "",
    "data-poultry": "Poultry Free",
    "data-grain": "Grain Free",
    "brandId": "8755",
    "brandDisplay": "Acana",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473133da27f6ef89f47309fdd379884287a5b?version=1.0&width=2046&height=1536",
    "previewAlttag": "Singles Limited Ingredient Diet Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "8755",
    "img-data-five": "285973",
    "sd-data-fives": "3A9NE",
    "ing-data-fives": [
      "FLMRA",
      "GSJWC",
      "CQCMT",
      "5E1NB",
      "5KHTT",
      "ARHPV",
      "XJAAA",
      "4CQVY",
      "RD1WV",
      "SYGQB",
      "Z9I0H",
      "BSARH",
      "XUUYO",
      "9UMLW",
      "QKPNY",
      "M0BM4",
      "GP3HX",
      "04ZOO",
      "ZPGID",
      "AGJPT",
      "COCPI",
      "YRWGG",
      "YHGZY",
      "UIC8H",
      "MLAA7",
      "81XCU",
      "MBFOA",
      "QX1UZ",
      "K3WTW",
      "QFRJN",
      "W0HAM",
      "KE2JS",
      "L5O6A",
      "RUAPK",
      "993B1",
      "UQHTP"
    ],
    "cont-data-fives": [
      "XJAAA",
      "SYGQB",
      "5KHTT",
      "RD1WV"
    ],
    "cf-data-five": 285973,
    "specs_price_per_bag": 97.99,
    "specs_bag-size_lbs": 22.5,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 31,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 17,
    "ga_crude_fiber_%": 5,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3405,
    "ga_kcals_per_cup": 388
  },
  {
    "Name": "Purina Pro Plan Adult Shredded Blend",
    "Slug": "compare-purina-pro-plan-adult-shredded-blend-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d99b72bddf1b95dcda",
    "canonical": "compare-purina-pro-plan-adult-shredded-blend-ingredients",
    "recordId": "recBTxPXyQpna57oa",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "purina-pro-plan-adult-shredded-blend",
    "itemId": "114025",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Purina Pro Plan Adult Shredded Blend",
    "data-five": "114025",
    "data-sort": 2,
    "data-one": "Adult Shredded Blend",
    "data-brand": "Purina Pro Plan",
    "data-diet": "Grain",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7434",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313ae81944782da45689476f3904529bf9f?version=1.0&width=2046&height=1536",
    "previewAlttag": "Adult Shredded Blend Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7434",
    "img-data-five": "114025",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "THZVQ",
      "CDQCK",
      "UYDPF",
      "QHDUJ",
      "OAYON",
      "GOURU",
      "PUVNB",
      "Q99OM",
      "SZ9O3",
      "F4SUG",
      "1VEVT",
      "8KBDY",
      "K4SWZ",
      "ORXDE",
      "G0IOG",
      "KZC6H",
      "R8PIF",
      "9UMLW",
      "AH4GG",
      "UCMJH",
      "BOL4J",
      "BWNCE",
      "K3WTW",
      "AWE1M",
      "AJI2E",
      "JX8SA",
      "E94HP",
      "EKBTQ",
      "5EIKP",
      "7TSVX",
      "QZ09Z",
      "CPEN5",
      "2ZKIM",
      "HQCHY",
      "B92D3",
      "Q08LQ",
      "0EEFX",
      "QKPNY",
      "4GGMJ",
      "1THAG",
      "QISOK",
      "DLHTR"
    ],
    "cont-data-fives": [
      "QHDUJ",
      "ZTMYL",
      "MYRTC",
      "TDEIO",
      "MDIZK",
      "Q99OM",
      "SZ9O3",
      "CDQCK",
      "GOURU",
      "R8PIF",
      "JGOFI",
      "G0IOG"
    ],
    "cf-data-five": 114025,
    "specs_price_per_bag": 74.48,
    "specs_bag-size_lbs": 33,
    "specs_primary_flavor": "Fish",
    "ga_crude_protein_%": 26,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3856,
    "ga_kcals_per_cup": 389
  },
  {
    "Name": "Victor Select Yukon River Canine",
    "Slug": "compare-victor-select-yukon-river-canine-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d97dac4baf5afcbdc7",
    "canonical": "compare-victor-select-yukon-river-canine-ingredients",
    "recordId": "receH6sCo3eoHcBsk",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-select-yukon-river-canine",
    "itemId": "120706",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Select Yukon River Canine",
    "data-five": "120706",
    "data-sort": 8,
    "data-one": "Yukon River",
    "data-brand": "Victor",
    "data-diet": "Grain-Free",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "Grain Free",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731382ccc323d7a3462da82b879e1901daad?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Yukon River Canine Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "120706",
    "sd-data-fives": "3A9NE",
    "ing-data-fives": [
      "LNUMU",
      "LJBTO",
      "VUYIW",
      "G2YVH",
      "Y7ODL",
      "V9APU",
      "ETXUL",
      "BS8EA",
      "RH9L7",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK"
    ],
    "cont-data-fives": [
      "G2YVH",
      "PG8TP",
      "OOUXY",
      "LCALN",
      "VUYIW",
      "LNUMU",
      "LJBTO",
      "BSL2E",
      "HNLVZ"
    ],
    "cf-data-five": 120706,
    "specs_price_per_bag": 77.99,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Fish",
    "ga_crude_protein_%": 33,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3666,
    "ga_kcals_per_cup": 390
  },
  {
    "Name": "Farmina Nd Ancestral Grain Lamb",
    "Slug": "compare-farmina-nd-ancestral-grain-lamb-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d9703b07f33cb18efb",
    "canonical": "compare-farmina-nd-ancestral-grain-lamb-ingredients",
    "recordId": "recG41YKSBwzoJ95O",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "farmina-nd-ancestral-grain-lamb",
    "itemId": "105269",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Farmina Nd Ancestral Grain Lamb",
    "data-five": "105269",
    "data-sort": 1,
    "data-one": "Ancestral Grain Lamb",
    "data-brand": "Farmina",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "6749",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313037a735e6d564ef48c280a60948ce8da?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Lamb Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "6749",
    "img-data-five": "105269",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "7SZIB",
      "C2TWM",
      "G4ZMU",
      "DZYA6",
      "XC0BR",
      "Z7Z8A",
      "HT5ZK",
      "VUYIW",
      "IQTT3",
      "1VEVT",
      "IQE13",
      "YHSJR",
      "90DOH",
      "4GUVA",
      "JJTVJ",
      "XR8EH",
      "HJJWJ",
      "TSXY8",
      "YPL1J",
      "17YZ3",
      "PRW8L",
      "9UMLW",
      "LNDRX",
      "W0HAM",
      "IPPTH",
      "9WQMN",
      "EKBTQ",
      "COCPI",
      "04ZOO",
      "JUDBS",
      "YRWGG",
      "UIC8H",
      "81XCU",
      "MLAA7",
      "YHGZY",
      "YD8CG",
      "MBFOA",
      "QX1UZ",
      "QKPNY",
      "UHTXD",
      "2SX0Z",
      "VDCDU",
      "CAIRD",
      "4BJJX",
      "XV780",
      "SIPQU",
      "M0BM4",
      "SWMVA",
      "VM56I",
      "NVUQ6",
      "L5O6A",
      "CAFOM"
    ],
    "cont-data-fives": [
      "IQTT3",
      "FZR9B",
      "3HWIO",
      "JUDBS",
      "8OTUY",
      "YPL1J",
      "TDEIO",
      "VUYIW",
      "72Y0R",
      "QVQOL"
    ],
    "cf-data-five": 105269,
    "specs_price_per_bag": 99.99,
    "specs_bag-size_lbs": 26.4,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 28,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3941,
    "ga_kcals_per_cup": 394
  },
  {
    "Name": "Victor Select Chicken Meal Sweet",
    "Slug": "compare-victor-select-chicken-meal-sweet-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d9291391a5988a8092",
    "canonical": "compare-victor-select-chicken-meal-sweet-ingredients",
    "recordId": "recbrOrtlhyEFLJqx",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-select-chicken-meal-sweet",
    "itemId": "120711",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Select Chicken Meal Sweet",
    "data-five": "120711",
    "data-sort": 10,
    "data-one": "Chicken Meal",
    "data-brand": "Victor",
    "data-diet": "Grain-Free",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "Grain Free",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313be3207e10c504765a61fb803c4eb5e90?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Chicken Meal Sweet Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "120711",
    "sd-data-fives": "3A9NE",
    "ing-data-fives": [
      "CEVBH",
      "LJBTO",
      "VUYIW",
      "G2YVH",
      "V9APU",
      "ETXUL",
      "RH9L7",
      "LQRGM",
      "BS8EA",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK"
    ],
    "cont-data-fives": [
      "G2YVH",
      "PG8TP",
      "OOUXY",
      "LCALN",
      "VUYIW",
      "LNUMU",
      "LJBTO",
      "BSL2E",
      "HNLVZ"
    ],
    "cf-data-five": 120711,
    "specs_price_per_bag": 77.49,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 33,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3744,
    "ga_kcals_per_cup": 398
  },
  {
    "Name": "Victor Purpose Performance Formula",
    "Slug": "compare-victor-purpose-performance-formula-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d92d52d7a5e0ecb50d",
    "canonical": "compare-victor-purpose-performance-formula-ingredients",
    "recordId": "recYjsc1r9roUfZQu",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-purpose-performance-formula",
    "itemId": "120684",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Purpose Performance Formula",
    "data-five": "120684",
    "data-sort": 5,
    "data-one": "Performance",
    "data-brand": "Victor",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473130453a01e4ab94c9ea5a84cec88297f14?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Performance Formula Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "120684",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "GSJWC",
      "GE6GU",
      "VJD3I",
      "VUYIW",
      "RH9L7",
      "CEVBH",
      "H0NSG",
      "BS8EA",
      "ETXUL",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "V43XM",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "9WQMN",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK"
    ],
    "cont-data-fives": [
      "PG8TP",
      "OOUXY",
      "LCALN",
      "VUYIW",
      "BSL2E",
      "HNLVZ"
    ],
    "cf-data-five": 120684,
    "specs_price_per_bag": 65.29,
    "specs_bag-size_lbs": 40,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 26,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3756,
    "ga_kcals_per_cup": 399
  },
  {
    "Name": "Victor Purpose Nutra Pro Dry Dog Food",
    "Slug": "compare-victor-purpose-nutra-pro-dry-dog-food-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d93e6b303e24d4ae93",
    "canonical": "compare-victor-purpose-nutra-pro-dry-dog-food-ingredients",
    "recordId": "rec8OgezfHbGRboNN",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-purpose-nutra-pro-dry-dog-food",
    "itemId": "129281",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Purpose Nutra Pro Dry Dog Food",
    "data-five": "129281",
    "data-sort": 11,
    "data-one": "Nutra Pro",
    "data-brand": "Victor",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473138c25caa99a19448db80ac5b30ee8b6e9?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Nutra Pro Dry Dog Food Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "129281",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "CEVBH",
      "RH9L7",
      "VJD3I",
      "VUYIW",
      "ETXUL",
      "GE6GU",
      "LNUMU",
      "GSJWC",
      "BS8EA",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK"
    ],
    "cont-data-fives": [
      "PG8TP",
      "OOUXY",
      "LCALN",
      "VUYIW",
      "LNUMU",
      "BSL2E",
      "HNLVZ"
    ],
    "cf-data-five": 129281,
    "specs_price_per_bag": 76.59,
    "specs_bag-size_lbs": 40,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 38,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 3.5,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3774,
    "ga_kcals_per_cup": 399
  },
  {
    "Name": "Farmina Nd Ocean Codfish Orange",
    "Slug": "compare-farmina-nd-ocean-codfish-orange-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5db5d4f7aa7f82a1aea",
    "canonical": "compare-farmina-nd-ocean-codfish-orange-ingredients",
    "recordId": "recO3o4bOV3H9GlFf",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "farmina-nd-ocean-codfish-orange",
    "itemId": "55911",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Farmina Nd Ocean Codfish Orange",
    "data-five": "55911",
    "data-sort": 22,
    "data-one": "Ancestral Grain Ocean",
    "data-brand": "Farmina",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "Poultry Free",
    "data-grain": "",
    "brandId": "6749",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473133c1341cf43ea4d198d4e3de201225bfa?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ocean Codfish Orange Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "6749",
    "img-data-five": "55911",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "JRLXE",
      "CIPVY",
      "IQTT3",
      "G4ZMU",
      "DZYA6",
      "1VEVT",
      "RW1BB",
      "ZOEIR",
      "90DOH",
      "U6HWJ",
      "JJTVJ",
      "YPL1J",
      "HJJWJ",
      "TSXY8",
      "17YZ3",
      "PRW8L",
      "XR8EH",
      "9UMLW",
      "LNDRX",
      "W0HAM",
      "V43XM",
      "9WQMN",
      "EKBTQ",
      "COCPI",
      "04ZOO",
      "JUDBS",
      "YRWGG",
      "UIC8H",
      "81XCU",
      "MLAA7",
      "YHGZY",
      "YD8CG",
      "MBFOA",
      "QX1UZ",
      "QKPNY",
      "UHTXD",
      "2SX0Z",
      "VDCDU",
      "CAIRD",
      "4BJJX",
      "XV780",
      "SIPQU",
      "M0BM4",
      "SWMVA",
      "VM56I",
      "NVUQ6",
      "L5O6A",
      "CAFOM"
    ],
    "cont-data-fives": [
      "IQTT3",
      "3HWIO",
      "FZR9B",
      "JUDBS",
      "YPL1J",
      "TDEIO",
      "72Y0R",
      "QVQOL"
    ],
    "cf-data-five": 55911,
    "specs_price_per_bag": 99.99,
    "specs_bag-size_lbs": 26.5,
    "specs_primary_flavor": "Fish",
    "ga_crude_protein_%": 30,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3125,
    "ga_kcals_per_cup": 400
  },
  {
    "Name": "Farmina Nd Ancestral Grain Chicken",
    "Slug": "compare-farmina-nd-ancestral-grain-chicken-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5da0ca4050d2f6ba62a",
    "canonical": "compare-farmina-nd-ancestral-grain-chicken-ingredients",
    "recordId": "recurrQnBRJ0CD0xM",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "farmina-nd-ancestral-grain-chicken",
    "itemId": "202214",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Farmina Nd Ancestral Grain Chicken",
    "data-five": "202214",
    "data-sort": 12,
    "data-one": "Ancestral Grain Chicken",
    "data-brand": "Farmina",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "6749",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313a81707890b32423d9e477632a8ac09a8?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Chicken Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "6749",
    "img-data-five": "202214",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "IULX1",
      "GAMG6",
      "G4ZMU",
      "DZYA6",
      "VUYIW",
      "XC0BR",
      "Z7Z8A",
      "HT5ZK",
      "1VEVT",
      "IQTT3",
      "IQE13",
      "YHSJR",
      "90DOH",
      "4GUVA",
      "JJTVJ",
      "TSXY8",
      "HJJWJ",
      "17YZ3",
      "PRW8L",
      "YPL1J",
      "XR8EH",
      "9UMLW",
      "LNDRX",
      "W0HAM",
      "IPPTH",
      "9WQMN",
      "EKBTQ",
      "COCPI",
      "04ZOO",
      "JUDBS",
      "YRWGG",
      "UIC8H",
      "81XCU",
      "MLAA7",
      "YHGZY",
      "YD8CG",
      "MBFOA",
      "QX1UZ",
      "QKPNY",
      "UHTXD",
      "2SX0Z",
      "VDCDU",
      "CAIRD",
      "4BJJX",
      "XV780",
      "SIPQU",
      "M0BM4",
      "SWMVA",
      "VM56I",
      "NVUQ6",
      "L5O6A",
      "CAFOM"
    ],
    "cont-data-fives": [
      "IQTT3",
      "FZR9B",
      "3HWIO",
      "JUDBS",
      "8OTUY",
      "YPL1J",
      "TDEIO",
      "VUYIW",
      "72Y0R",
      "QVQOL"
    ],
    "cf-data-five": 202214,
    "specs_price_per_bag": 84.99,
    "specs_bag-size_lbs": 26.5,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 30,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3997,
    "ga_kcals_per_cup": 400
  },
  {
    "Name": "Victor Realtree Max 5 Pro Dry Dog",
    "Slug": "compare-victor-realtree-max-5-pro-dry-dog-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5da37902d38e50284f1",
    "canonical": "compare-victor-realtree-max-5-pro-dry-dog-ingredients",
    "recordId": "rech8XpJSdzgzbjXu",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-realtree-max-5-pro-dry-dog",
    "itemId": "279306",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Realtree Max 5 Pro Dry Dog",
    "data-five": "279306",
    "data-sort": 14,
    "data-one": "Realtree Max 5",
    "data-brand": "Victor",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473137116eeb638a44c8d838be1c48cfc5c45?version=1.0&width=2046&height=1536",
    "previewAlttag": "Realtree Max 5 Pro Dry Dog Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "279306",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "GSJWC",
      "GE6GU",
      "VUYIW",
      "F4SUG",
      "E9MIY",
      "LNUMU",
      "BS8EA",
      "DH0D2",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "EJMRL",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "ZTMYL",
      "IJG6H",
      "V43XM",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "CSYLS",
      "9WQMN",
      "OH49J",
      "PSOWE",
      "U3RU8",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK"
    ],
    "cont-data-fives": [
      "PG8TP",
      "OOUXY",
      "ZTMYL",
      "GKL4J",
      "VUYIW",
      "LNUMU",
      "BSL2E",
      "HNLVZ"
    ],
    "cf-data-five": 279306,
    "specs_price_per_bag": 68.49,
    "specs_bag-size_lbs": 40,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3794,
    "ga_kcals_per_cup": 403
  },
  {
    "Name": "Dr Tims Weight Management Metabolite",
    "Slug": "compare-dr-tims-weight-management-metabolite-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d910daa6cd349ed4e9",
    "canonical": "compare-dr-tims-weight-management-metabolite-ingredients",
    "recordId": "recOZZ6fOAtjUcH2C",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "dr-tims-weight-management-metabolite",
    "itemId": "119068",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Dr Tims Weight Management Metabolite",
    "data-five": "119068",
    "data-sort": 3,
    "data-one": "Metabolite",
    "data-brand": "Dr Tims",
    "data-diet": "Grain",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "6697",
    "brandDisplay": "Dr Tims",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313fba4e5c590be4bb982ce5f2791570cb6?version=1.0&width=2046&height=1536",
    "previewAlttag": "Weight Management Metabolite Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "6697",
    "img-data-five": "119068",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "CEVBH",
      "GKL4J",
      "72Y0R",
      "LJBTO",
      "WJEHA",
      "TDEIO",
      "LHLHB",
      "VUYIW",
      "ZTMYL",
      "NCE9F",
      "Z9I0H",
      "VT96P",
      "KZC6H",
      "IP9OV",
      "X5FFT",
      "YD8CG",
      "YRWGG",
      "SQ0XJ",
      "COVUX",
      "EKBTQ",
      "YHGZY",
      "MLAA7",
      "COCPI",
      "QX1UZ",
      "MBFOA",
      "9UMLW",
      "HQGYF",
      "OOUXY",
      "SIPQU",
      "QKPNY",
      "GP3HX",
      "KZYKM",
      "AYV0F",
      "KSOUF",
      "ECLSM",
      "BOL4J",
      "K3WTW",
      "555IX",
      "ZPGID",
      "BWNCE",
      "OQE8V",
      "LDMXN",
      "CDODO",
      "M0BM4",
      "QFRJN",
      "AH4GG",
      "PRW8L",
      "YLNYF",
      "IIDS9",
      "FXO5C",
      "QJDEF",
      "HDFQP",
      "1JDZJ",
      "KQB77",
      "CAL2I",
      "SWMVA",
      "4GGMJ"
    ],
    "cont-data-fives": [
      "9FK4M",
      "NCE9F",
      "FXO5C",
      "HDFQP",
      "1JDZJ",
      "ZTMYL",
      "HQGYF",
      "GKL4J",
      "TDEIO",
      "VUYIW",
      "72Y0R",
      "LJBTO"
    ],
    "cf-data-five": 119068,
    "specs_price_per_bag": 87.99,
    "specs_bag-size_lbs": 24,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 30,
    "tag_kcalscup": "low",
    "tag_fat": "low",
    "tag_protein": "",
    "ga_crude_fat_%": 10,
    "ga_crude_fiber_%": 10,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3218,
    "ga_kcals_per_cup": 411
  },
  {
    "Name": "Victor Purpose Ultra Pro Grain Free",
    "Slug": "compare-victor-purpose-ultra-pro-grain-free-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5d910daa6cd349ed598",
    "canonical": "compare-victor-purpose-ultra-pro-grain-free-ingredients",
    "recordId": "recaeGW8ob4kCsNzL",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "victor-purpose-ultra-pro-grain-free",
    "itemId": "120708",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Victor Purpose Ultra Pro Grain Free",
    "data-five": "120708",
    "data-sort": 9,
    "data-one": "Ultra Pro",
    "data-brand": "Victor",
    "data-diet": "Grain-Free",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "Grain Free",
    "brandId": "7682",
    "brandDisplay": "Victor",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473132c96b2faf13543d38a1fbad71e89a66f?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Ultra Pro Grain Free Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7682",
    "img-data-five": "120708",
    "sd-data-fives": "3A9NE",
    "ing-data-fives": [
      "CEVBH",
      "GSJWC",
      "VUYIW",
      "LJBTO",
      "RH9L7",
      "ETXUL",
      "H0NSG",
      "BS8EA",
      "V9APU",
      "LQRGM",
      "F4SUG",
      "AH4GG",
      "WG5DM",
      "BSL2E",
      "9UMLW",
      "UHYTS",
      "M0BM4",
      "QKPNY",
      "MICCW",
      "IJG6H",
      "04ZOO",
      "IQK4Z",
      "IDQAS",
      "PG8TP",
      "OH49J",
      "PSOWE",
      "SWMVA",
      "XV780",
      "LNDRX",
      "RRO5G",
      "DQ78W",
      "QY3IX",
      "CKYLP",
      "YJSLD",
      "555IX",
      "8LGUT",
      "QX1UZ",
      "EKBTQ",
      "8UWMC",
      "YHGZY",
      "YD8CG",
      "YLNYF",
      "KZC6H",
      "COVUX",
      "AWE1M",
      "MLAA7",
      "COCPI",
      "MLJ43",
      "HNLVZ",
      "L5O6A",
      "NVUQ6",
      "ZATJI",
      "90DOH",
      "OOUXY",
      "ATUZK"
    ],
    "cont-data-fives": [
      "PG8TP",
      "OOUXY",
      "LCALN",
      "VUYIW",
      "LNUMU",
      "LJBTO",
      "BSL2E",
      "HNLVZ"
    ],
    "cf-data-five": 120708,
    "specs_price_per_bag": 80.99,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 42,
    "tag_kcalscup": "low",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 22,
    "ga_crude_fiber_%": 3.4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3890,
    "ga_kcals_per_cup": 414
  },
  {
    "Name": "Purina Pro Plan High Protein Chicken",
    "Slug": "compare-purina-pro-plan-high-protein-chicken-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5da9c76eeae246ae477",
    "canonical": "compare-purina-pro-plan-high-protein-chicken-ingredients",
    "recordId": "recIVlN33V7TQjQ7M",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "purina-pro-plan-high-protein-chicken",
    "itemId": "52423",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Purina Pro Plan High Protein Chicken",
    "data-five": "52423",
    "data-sort": 18,
    "data-one": "High Protein Chicken",
    "data-brand": "Purina Pro Plan",
    "data-diet": "Grain",
    "data-legumes": "",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7434",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731323751dbf15d74616b0874004f31d4912?version=1.0&width=2046&height=1536",
    "previewAlttag": "High Protein Chicken Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7434",
    "img-data-five": "52423",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "IULX1",
      "CDQCK",
      "HWIWE",
      "OAYON",
      "QHDUJ",
      "UYDPF",
      "PUVNB",
      "WHF79",
      "8KBDY",
      "SZ9O3",
      "F4SUG",
      "RD1WV",
      "R8PIF",
      "ORXDE",
      "9UMLW",
      "KZC6H",
      "AH4GG",
      "5S0XF",
      "QKPNY",
      "QISOK",
      "K2QVC",
      "BOL4J",
      "NRX8Q",
      "555IX",
      "AWE1M",
      "AJI2E",
      "JX8SA",
      "HUSPZ",
      "EKBTQ",
      "7TSVX",
      "5EIKP",
      "CPEN5",
      "QZ09Z",
      "2ZKIM",
      "B92D3",
      "HQCHY",
      "FRWZQ",
      "YAPNO",
      "GVKK6"
    ],
    "cont-data-fives": [
      "HWIWE",
      "QHDUJ",
      "WHF79",
      "ZTMYL",
      "MYRTC",
      "MDIZK",
      "SZ9O3",
      "RD1WV",
      "CDQCK",
      "R8PIF",
      "JGOFI"
    ],
    "cf-data-five": 52423,
    "specs_price_per_bag": 74.98,
    "specs_bag-size_lbs": 34,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 28,
    "tag_kcalscup": "low",
    "tag_fat": "low",
    "tag_protein": "",
    "ga_crude_fat_%": 13,
    "ga_crude_fiber_%": 4.75,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3934,
    "ga_kcals_per_cup": 419
  },
  {
    "Name": "Purina Pro Plan Specialized Beef Rice",
    "Slug": "compare-purina-pro-plan-specialized-beef-rice-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5dad77caa49ce7545bf",
    "canonical": "compare-purina-pro-plan-specialized-beef-rice-ingredients",
    "recordId": "rec587UBLjMYZ41B2",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "purina-pro-plan-specialized-beef-rice",
    "itemId": "298045",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Purina Pro Plan Specialized Beef Rice",
    "data-five": "298045",
    "data-sort": 16,
    "data-one": "Specialized Beef Rice",
    "data-brand": "Purina Pro Plan",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "7434",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xcc58fac5e0664d969a12cdaa8c2063da?version=1.0&width=2046&height=1536",
    "previewAlttag": "Specialized Beef Rice Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "7434",
    "img-data-five": "298045",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "FLMRA",
      "CDQCK",
      "Q99OM",
      "OAYON",
      "QHDUJ",
      "UYDPF",
      "B2WBK",
      "PUVNB",
      "NQ4LR",
      "SZ9O3",
      "8KBDY",
      "F4SUG",
      "RD1WV",
      "G0IOG",
      "KZC6H",
      "R8PIF",
      "AH4GG",
      "9UMLW",
      "ORXDE",
      "5S0XF",
      "E87QO",
      "HUSPZ",
      "EKBTQ",
      "7TSVX",
      "5EIKP",
      "CPEN5",
      "QZ09Z",
      "2ZKIM",
      "B92D3",
      "HQCHY",
      "FRWZQ",
      "YAPNO",
      "QKPNY",
      "X7J76",
      "BOL4J",
      "NRX8Q",
      "555IX",
      "AWE1M",
      "AJI2E",
      "V43XM",
      "M0BM4",
      "1THAG",
      "4GGMJ",
      "QISOK",
      "FSMSV"
    ],
    "cont-data-fives": [
      "QHDUJ",
      "B2WBK",
      "NQ4LR",
      "ZTMYL",
      "MYRTC",
      "MDIZK",
      "Q99OM",
      "SZ9O3",
      "RD1WV",
      "CDQCK",
      "R8PIF",
      "JGOFI",
      "G0IOG"
    ],
    "cf-data-five": 298045,
    "specs_price_per_bag": 77.48,
    "specs_bag-size_lbs": 34,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 26,
    "tag_kcalscup": "",
    "tag_fat": "low",
    "tag_protein": "",
    "ga_crude_fat_%": 12,
    "ga_crude_fiber_%": 4.5,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 4018.867924528302,
    "ga_kcals_per_cup": 426
  },
  {
    "Name": "Sport Dog Food Herding Dog Grain Free Buffalo Formula",
    "Slug": "compare-sport-dog-food-grain-free-herding-dog-ingredients",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "compare--ingredients",
    "recordId": "recKwJ5pIWVIldfZk",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "itemId": "28979",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Sport Dog Food Herding Dog Grain Free Buffalo Formula",
    "data-five": "28979",
    "data-sort": 31,
    "data-one": "Herding Dog",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain-Free",
    "data-legumes": "Legumes Free",
    "data-poultry": "Poultry Free",
    "data-grain": "Grain Free",
    "brandId": "1000",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "",
    "previewAlttag": " Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "",
    "sd-data-fives": "",
    "ing-data-fives": [
      "C6HRL",
      "K5VFA",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "cont-data-fives": [
      "K5VFA"
    ],
    "cf-data-five": "",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "tag_kcalscup": "",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3603.0500000000006,
    "ga_kcals_per_cup": 460
  },
  {
    "Name": "Sport Dog Food Dock Dog Poultry Free Buffalo Formula",
    "Slug": "compare-sport-dog-food-dock-dog-ingredients",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "compare--ingredients",
    "recordId": "rec3cINoGv2tGiPHp",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "itemId": "29099",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Sport Dog Food Dock Dog Poultry Free Buffalo Formula",
    "data-five": "29099",
    "data-sort": 33,
    "data-one": "Dock Dog",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "Poultry Free",
    "data-grain": "",
    "brandId": "1000",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "",
    "previewAlttag": " Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "",
    "sd-data-fives": "",
    "ing-data-fives": [
      "C6HRL",
      "KEB4Z",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "cont-data-fives": [],
    "cf-data-five": "",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "tag_kcalscup": "",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.4,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3579,
    "ga_kcals_per_cup": 460
  },
  {
    "Name": "Dr Tims Active Dog Pursuit Formula",
    "Slug": "compare-dr-tims-active-dog-pursuit-formula-ingredients",
    "Collection ID": "647ddb9037101ce399b330b4",
    "Item ID": "6852e5daef4f6dcd3d3fb819",
    "canonical": "compare-dr-tims-active-dog-pursuit-formula-ingredients",
    "recordId": "recIo33SmIRRx52rl",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "dr-tims-active-dog-pursuit-formula",
    "itemId": "37811",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Dr Tims Active Dog Pursuit Formula",
    "data-five": "37811",
    "data-sort": 17,
    "data-one": "Pursuit",
    "data-brand": "Dr Tims",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "",
    "data-grain": "",
    "brandId": "6697",
    "brandDisplay": "Dr Tims",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731352dfcbfd5c23482c8525478b17031dfd?version=1.0&width=2046&height=1536",
    "previewAlttag": "Active Dog Pursuit Formula Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "6697",
    "img-data-five": "37811",
    "sd-data-fives": "YOIPL",
    "ing-data-fives": [
      "CEVBH",
      "GKL4J",
      "VUYIW",
      "72Y0R",
      "TDEIO",
      "ZTMYL",
      "GYPF8",
      "HQGYF",
      "BCPGM",
      "VT96P",
      "U9EU7",
      "Z9I0H",
      "NCE9F",
      "LHLHB",
      "IP9OV",
      "X5FFT",
      "YD8CG",
      "YRWGG",
      "SQ0XJ",
      "COVUX",
      "EKBTQ",
      "YHGZY",
      "MLAA7",
      "COCPI",
      "QX1UZ",
      "MBFOA",
      "AH4GG",
      "OOUXY",
      "SIPQU",
      "KZYKM",
      "AYV0F",
      "KSOUF",
      "ECLSM",
      "BOL4J",
      "K3WTW",
      "555IX",
      "ZPGID",
      "BWNCE",
      "OQE8V",
      "LDMXN",
      "CDODO",
      "GP3HX",
      "9UMLW",
      "QFRJN",
      "QKPNY",
      "M0BM4",
      "PRW8L",
      "YLNYF",
      "SWMVA",
      "4GGMJ"
    ],
    "cont-data-fives": [
      "NCE9F",
      "ZTMYL",
      "HQGYF",
      "GKL4J",
      "TDEIO",
      "VUYIW",
      "72Y0R"
    ],
    "cf-data-five": 37811,
    "specs_price_per_bag": 119.99,
    "specs_bag-size_lbs": 40,
    "specs_primary_flavor": "Poultry",
    "ga_crude_protein_%": 30,
    "tag_kcalscup": "",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 4036,
    "ga_kcals_per_cup": 516
  },
  {
    "Name": "Sport Dog Food Cub Puppy Poultry Free Buffalo Formula",
    "Slug": "compare-sport-dog-food-puppy-ingredients",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "compare--ingredients",
    "recordId": "rec4ZbvYXdyr6wiiR",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "itemId": "29280",
    "item-subtitle": "",
    "item-status": "",
    "itemName": "Sport Dog Food Cub Puppy Poultry Free Buffalo Formula",
    "data-five": "29280",
    "data-sort": 32,
    "data-one": "Cub Puppy",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain",
    "data-legumes": "Legumes Free",
    "data-poultry": "Poultry Free",
    "data-grain": "",
    "brandId": "1000",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "",
    "previewAlttag": " Dog Food Bag",
    "cf_description": "",
    "data-faqType": "ci",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "",
    "sd-data-fives": "",
    "ing-data-fives": [
      "C6HRL",
      "KEB4Z",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "cont-data-fives": [],
    "cf-data-five": "",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "tag_kcalscup": "",
    "tag_fat": "",
    "tag_protein": "",
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3847.7000000000003,
    "ga_kcals_per_cup": 526
  }
]
