[
  {
    "Name": "105269",
    "Slug": "105269",
    "collection-api": "",
    "itemID_api": "6844a7800fefebdd76a521ed",
    "calcSlug": 105269,
    "itemId": "105269",
    "itemName": "Farmina Nd Ancestral Grain Lamb",
    "item-subtitle": "",
    "itemRecordId": "recG41YKSBwzoJ95O",
    "data-faqType": "compare-hello",
    "data-sort": 1,
    "data-one": "Nd Ancestral Grain Lamb",
    "data-alt": "Nd Ancestral Grain Lamb",
    "data-diet": "Grain",
    "data-brand": "6749",
    "brandId": "6749",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313037a735e6d564ef48c280a60948ce8da?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Lamb Dog Food Bag",
    "specs_price_per_bag": 99.99,
    "specs_bag-size_lbs": 26.4,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 28,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3941,
    "ga_kcals_per_cup": 394,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": [
      "lamb",
      "dehydrated-lamb"
    ]
  },
  {
    "Name": "114025",
    "Slug": "114025",
    "collection-api": "",
    "itemID_api": "6844a780f2d2d049077b5267",
    "calcSlug": 114025,
    "itemId": "114025",
    "itemName": "Purina Pro Plan Adult Shredded Blend",
    "item-subtitle": "",
    "itemRecordId": "recBTxPXyQpna57oa",
    "data-faqType": "compare-hello",
    "data-sort": 2,
    "data-one": "Adult Shredded Blend",
    "data-alt": "Adult Shredded Blend",
    "data-diet": "Grain",
    "data-brand": "7434",
    "brandId": "7434",
    "brands": "Purina Pro Plan",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313ae81944782da45689476f3904529bf9f?version=1.0&width=2046&height=1536",
    "previewAlttag": "Adult Shredded Blend Dog Food Bag",
    "specs_price_per_bag": 74.48,
    "specs_bag-size_lbs": 33,
    "item-status": "",
    "specs_primary_flavor": "Fish",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 26,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3856,
    "ga_kcals_per_cup": 389,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "119068",
    "Slug": "119068",
    "collection-api": "",
    "itemID_api": "6844a780bb4b55c6a7bdd58b",
    "calcSlug": 119068,
    "itemId": "119068",
    "itemName": "Dr Tims Weight Management Metabolite",
    "item-subtitle": "",
    "itemRecordId": "recOZZ6fOAtjUcH2C",
    "data-faqType": "compare-hello",
    "data-sort": 3,
    "data-one": "Weight Management Metabolite",
    "data-alt": "Weight Management Metabolite",
    "data-diet": "Grain",
    "data-brand": "6697",
    "brandId": "6697",
    "brands": "Dr Tims",
    "brandDisplay": "Dr Tims",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313fba4e5c590be4bb982ce5f2791570cb6?version=1.0&width=2046&height=1536",
    "previewAlttag": "Weight Management Metabolite Dog Food Bag",
    "specs_price_per_bag": 87.99,
    "specs_bag-size_lbs": 24,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 10,
    "ga_crude_fiber_%": 10,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3218,
    "ga_kcals_per_cup": 411,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "120680",
    "Slug": "120680",
    "collection-api": "",
    "itemID_api": "6844a7809c270652d7a81cf9",
    "calcSlug": 120680,
    "itemId": "120680",
    "itemName": "Victor Select Lamb Meal Brown Rice",
    "item-subtitle": "",
    "itemRecordId": "recHWP48JBtTLPzIE",
    "data-faqType": "compare-hello",
    "data-sort": 4,
    "data-one": "Select Lamb Meal Brown Rice",
    "data-alt": "Select Lamb Meal Brown Rice",
    "data-diet": "Grain",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313974dbedb88c3499bb3770ed53a26bfac?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Lamb Meal Brown Rice Dog Food Bag",
    "specs_price_per_bag": 78.24,
    "specs_bag-size_lbs": 40,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 24,
    "ga_crude_fat_%": 12,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3501,
    "ga_kcals_per_cup": 372,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "120684",
    "Slug": "120684",
    "collection-api": "",
    "itemID_api": "6844a780a7b546547d24d75a",
    "calcSlug": 120684,
    "itemId": "120684",
    "itemName": "Victor Purpose Performance Formula",
    "item-subtitle": "",
    "itemRecordId": "recYjsc1r9roUfZQu",
    "data-faqType": "compare-hello",
    "data-sort": 5,
    "data-one": "Purpose Performance Formula",
    "data-alt": "Purpose Performance Formula",
    "data-diet": "Grain",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473130453a01e4ab94c9ea5a84cec88297f14?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Performance Formula Dog Food Bag",
    "specs_price_per_bag": 65.29,
    "specs_bag-size_lbs": 40,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 26,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3756,
    "ga_kcals_per_cup": 399,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "120700",
    "Slug": "120700",
    "collection-api": "",
    "itemID_api": "6844a7815ab150cfbcac8594",
    "calcSlug": 120700,
    "itemId": "120700",
    "itemName": "Victor Purpose Active Dog Puppy",
    "item-subtitle": "",
    "itemRecordId": "recA5sadFi83r4I9Q",
    "data-faqType": "compare-hello",
    "data-sort": 6,
    "data-one": "Purpose Active Dog Puppy",
    "data-alt": "Purpose Active Dog Puppy",
    "data-diet": "Grain-Free",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313cd0b81f15619488b8f3a5a61031ee725?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Active Dog Puppy Dog Food Bag",
    "specs_price_per_bag": 70.29,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 33,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3614,
    "ga_kcals_per_cup": 384,
    "diets_slugs": [],
    "ing_calcSlugs": []
  },
  {
    "Name": "120702",
    "Slug": "120702",
    "collection-api": "",
    "itemID_api": "6844a78034eee4f54e37e243",
    "calcSlug": 120702,
    "itemId": "120702",
    "itemName": "Victor Purpose Hero Grain Free Dry",
    "item-subtitle": "",
    "itemRecordId": "rechhhtL9ySIeIiO6",
    "data-faqType": "compare-hello",
    "data-sort": 7,
    "data-one": "Purpose Hero Grain Free Dry",
    "data-alt": "Purpose Hero Grain Free Dry",
    "data-diet": "Grain-Free",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313c9733e62fcd14c949e2bfd02367b4efe?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Hero Grain Free Dry Dog Food Bag",
    "specs_price_per_bag": 70.29,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 33,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3614,
    "ga_kcals_per_cup": 384,
    "diets_slugs": [],
    "ing_calcSlugs": []
  },
  {
    "Name": "120706",
    "Slug": "120706",
    "collection-api": "",
    "itemID_api": "6844a780b534d9b058da272c",
    "calcSlug": 120706,
    "itemId": "120706",
    "itemName": "Victor Select Yukon River Canine",
    "item-subtitle": "",
    "itemRecordId": "receH6sCo3eoHcBsk",
    "data-faqType": "compare-hello",
    "data-sort": 8,
    "data-one": "Select Yukon River Canine",
    "data-alt": "Select Yukon River Canine",
    "data-diet": "Grain-Free",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731382ccc323d7a3462da82b879e1901daad?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Yukon River Canine Dog Food Bag",
    "specs_price_per_bag": 77.99,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Fish",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 33,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3666,
    "ga_kcals_per_cup": 390,
    "diets_slugs": [],
    "ing_calcSlugs": []
  },
  {
    "Name": "120708",
    "Slug": "120708",
    "collection-api": "",
    "itemID_api": "6844a781319a5aab0fcd1689",
    "calcSlug": 120708,
    "itemId": "120708",
    "itemName": "Victor Purpose Ultra Pro Grain Free",
    "item-subtitle": "",
    "itemRecordId": "recaeGW8ob4kCsNzL",
    "data-faqType": "compare-hello",
    "data-sort": 9,
    "data-one": "Purpose Ultra Pro Grain Free",
    "data-alt": "Purpose Ultra Pro Grain Free",
    "data-diet": "Grain-Free",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473132c96b2faf13543d38a1fbad71e89a66f?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Ultra Pro Grain Free Dog Food Bag",
    "specs_price_per_bag": 80.99,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 42,
    "ga_crude_fat_%": 22,
    "ga_crude_fiber_%": 3.4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3890,
    "ga_kcals_per_cup": 414,
    "diets_slugs": [],
    "ing_calcSlugs": []
  },
  {
    "Name": "120711",
    "Slug": "120711",
    "collection-api": "",
    "itemID_api": "6844a781bb11284b09124f4f",
    "calcSlug": 120711,
    "itemId": "120711",
    "itemName": "Victor Select Chicken Meal Sweet",
    "item-subtitle": "",
    "itemRecordId": "recbrOrtlhyEFLJqx",
    "data-faqType": "compare-hello",
    "data-sort": 10,
    "data-one": "Select Chicken Meal Sweet",
    "data-alt": "Select Chicken Meal Sweet",
    "data-diet": "Grain-Free",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313be3207e10c504765a61fb803c4eb5e90?version=1.0&width=2046&height=1536",
    "previewAlttag": "Select Chicken Meal Sweet Dog Food Bag",
    "specs_price_per_bag": 77.49,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 33,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3.8,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3744,
    "ga_kcals_per_cup": 398,
    "diets_slugs": [],
    "ing_calcSlugs": []
  },
  {
    "Name": "129281",
    "Slug": "129281",
    "collection-api": "",
    "itemID_api": "6844a7812da81548f63e88e5",
    "calcSlug": 129281,
    "itemId": "129281",
    "itemName": "Victor Purpose Nutra Pro Dry Dog Food",
    "item-subtitle": "",
    "itemRecordId": "rec8OgezfHbGRboNN",
    "data-faqType": "compare-hello",
    "data-sort": 11,
    "data-one": "Purpose Nutra Pro Dry Dog Food",
    "data-alt": "Purpose Nutra Pro Dry Dog Food",
    "data-diet": "Grain",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473138c25caa99a19448db80ac5b30ee8b6e9?version=1.0&width=2046&height=1536",
    "previewAlttag": "Purpose Nutra Pro Dry Dog Food Dog Food Bag",
    "specs_price_per_bag": 76.59,
    "specs_bag-size_lbs": 40,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 38,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 3.5,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3774,
    "ga_kcals_per_cup": 399,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "202214",
    "Slug": "202214",
    "collection-api": "",
    "itemID_api": "6844a78190772361803ac75c",
    "calcSlug": 202214,
    "itemId": "202214",
    "itemName": "Farmina Nd Ancestral Grain Chicken",
    "item-subtitle": "",
    "itemRecordId": "recurrQnBRJ0CD0xM",
    "data-faqType": "compare-hello",
    "data-sort": 12,
    "data-one": "Nd Ancestral Grain Chicken",
    "data-alt": "Nd Ancestral Grain Chicken",
    "data-diet": "Grain",
    "data-brand": "6749",
    "brandId": "6749",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313a81707890b32423d9e477632a8ac09a8?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Chicken Dog Food Bag",
    "specs_price_per_bag": 84.99,
    "specs_bag-size_lbs": 26.5,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3997,
    "ga_kcals_per_cup": 400,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "234247",
    "Slug": "234247",
    "collection-api": "",
    "itemID_api": "6844a7810fefebdd76a5236a",
    "calcSlug": 234247,
    "itemId": "234247",
    "itemName": "Farmina Nd Ancestral Grain Lamb",
    "item-subtitle": "",
    "itemRecordId": "recZZ2pxasvzJKV40",
    "data-faqType": "compare-hello",
    "data-sort": 13,
    "data-one": "Nd Ancestral Grain Lamb",
    "data-alt": "Nd Ancestral Grain Lamb",
    "data-diet": "Grain",
    "data-brand": "6749",
    "brandId": "6749",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/47313f4d91c42071c4e419ff6c7590742983d?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Lamb Dog Food Bag",
    "specs_price_per_bag": 99.99,
    "specs_bag-size_lbs": 26.5,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 35,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 1.7,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3414,
    "ga_kcals_per_cup": 437,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "279306",
    "Slug": "279306",
    "collection-api": "",
    "itemID_api": "6844a78193726ed1bc52d05b",
    "calcSlug": 279306,
    "itemId": "279306",
    "itemName": "Victor Realtree Max 5 Pro Dry Dog",
    "item-subtitle": "",
    "itemRecordId": "rech8XpJSdzgzbjXu",
    "data-faqType": "compare-hello",
    "data-sort": 14,
    "data-one": "Realtree Max 5 Pro Dry Dog",
    "data-alt": "Realtree Max 5 Pro Dry Dog",
    "data-diet": "Grain",
    "data-brand": "7682",
    "brandId": "7682",
    "brands": "VICTOR",
    "brandDisplay": "VICTOR",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473137116eeb638a44c8d838be1c48cfc5c45?version=1.0&width=2046&height=1536",
    "previewAlttag": "Realtree Max 5 Pro Dry Dog Dog Food Bag",
    "specs_price_per_bag": 68.49,
    "specs_bag-size_lbs": 40,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3794,
    "ga_kcals_per_cup": 403,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "285973",
    "Slug": "285973",
    "collection-api": "",
    "itemID_api": "6844a7816fec0964ccfcfa93",
    "calcSlug": 285973,
    "itemId": "285973",
    "itemName": "Acana Singles Limited Ingredient Diet",
    "item-subtitle": "",
    "itemRecordId": "recVXP10iAQ0yJa3L",
    "data-faqType": "compare-hello",
    "data-sort": 15,
    "data-one": "Singles Limited Ingredient Diet",
    "data-alt": "Singles Limited Ingredient Diet",
    "data-diet": "Grain-Free",
    "data-brand": "8755",
    "brandId": "8755",
    "brands": "ACANA",
    "brandDisplay": "ACANA",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473133da27f6ef89f47309fdd379884287a5b?version=1.0&width=2046&height=1536",
    "previewAlttag": "Singles Limited Ingredient Diet Dog Food Bag",
    "specs_price_per_bag": 97.99,
    "specs_bag-size_lbs": 22.5,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 31,
    "ga_crude_fat_%": 17,
    "ga_crude_fiber_%": 5,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3405,
    "ga_kcals_per_cup": 388,
    "diets_slugs": [],
    "ing_calcSlugs": []
  },
  {
    "Name": "298045",
    "Slug": "298045",
    "collection-api": "",
    "itemID_api": "6844a7819c270652d7a81d3f",
    "calcSlug": 298045,
    "itemId": "298045",
    "itemName": "Purina Pro Plan Specialized Beef Rice",
    "item-subtitle": "",
    "itemRecordId": "rec587UBLjMYZ41B2",
    "data-faqType": "compare-hello",
    "data-sort": 16,
    "data-one": "Specialized Beef Rice",
    "data-alt": "Specialized Beef Rice",
    "data-diet": "Grain",
    "data-brand": "7434",
    "brandId": "7434",
    "brands": "Purina Pro Plan",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xcc58fac5e0664d969a12cdaa8c2063da?version=1.0&width=2046&height=1536",
    "previewAlttag": "Specialized Beef Rice Dog Food Bag",
    "specs_price_per_bag": 77.48,
    "specs_bag-size_lbs": 34,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 26,
    "ga_crude_fat_%": 12,
    "ga_crude_fiber_%": 4.5,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 4018.867924528302,
    "ga_kcals_per_cup": 426,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "37811",
    "Slug": "37811",
    "collection-api": "",
    "itemID_api": "6844a77f22684ab14fd4ae63",
    "calcSlug": 37811,
    "itemId": "37811",
    "itemName": "Dr Tims Active Dog Pursuit Formula",
    "item-subtitle": "",
    "itemRecordId": "recIo33SmIRRx52rl",
    "data-faqType": "compare-hello",
    "data-sort": 17,
    "data-one": "Active Dog Pursuit Formula",
    "data-alt": "Active Dog Pursuit Formula",
    "data-diet": "Grain",
    "data-brand": "6697",
    "brandId": "6697",
    "brands": "Dr Tims",
    "brandDisplay": "Dr Tims",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731352dfcbfd5c23482c8525478b17031dfd?version=1.0&width=2046&height=1536",
    "previewAlttag": "Active Dog Pursuit Formula Dog Food Bag",
    "specs_price_per_bag": 119.99,
    "specs_bag-size_lbs": 40,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 4036,
    "ga_kcals_per_cup": 516,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "52423",
    "Slug": "52423",
    "collection-api": "",
    "itemID_api": "6844a780edf22a5c4a7f1122",
    "calcSlug": 52423,
    "itemId": "52423",
    "itemName": "Purina Pro Plan High Protein Chicken",
    "item-subtitle": "",
    "itemRecordId": "recIVlN33V7TQjQ7M",
    "data-faqType": "compare-hello",
    "data-sort": 18,
    "data-one": "High Protein Chicken",
    "data-alt": "High Protein Chicken",
    "data-diet": "Grain",
    "data-brand": "7434",
    "brandId": "7434",
    "brands": "Purina Pro Plan",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731323751dbf15d74616b0874004f31d4912?version=1.0&width=2046&height=1536",
    "previewAlttag": "High Protein Chicken Dog Food Bag",
    "specs_price_per_bag": 74.98,
    "specs_bag-size_lbs": 34,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 28,
    "ga_crude_fat_%": 13,
    "ga_crude_fiber_%": 4.75,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3934,
    "ga_kcals_per_cup": 419,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "52445",
    "Slug": "52445",
    "collection-api": "",
    "itemID_api": "6844a7801e484e2da49d8ddc",
    "calcSlug": 52445,
    "itemId": "52445",
    "itemName": "Purina Pro Plan High Protein Shredded",
    "item-subtitle": "",
    "itemRecordId": "recsBJUrKKf2mVLQG",
    "data-faqType": "compare-hello",
    "data-sort": 19,
    "data-one": "High Protein Shredded",
    "data-alt": "High Protein Shredded",
    "data-diet": "Grain",
    "data-brand": "7434",
    "brandId": "7434",
    "brands": "Purina Pro Plan",
    "brandDisplay": "Purina Pro Plan",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473132af6116f0e2742cba64632286e85426f?version=1.0&width=2046&height=1536",
    "previewAlttag": "High Protein Shredded Dog Food Bag",
    "specs_price_per_bag": 74.48,
    "specs_bag-size_lbs": 35,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 26,
    "ga_crude_fat_%": 16,
    "ga_crude_fiber_%": 3,
    "ga_moisture_%": 12,
    "ga_kcals_per_kg": 3790,
    "ga_kcals_per_cup": 369,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "552422",
    "Slug": "552422",
    "collection-api": "",
    "itemID_api": "6844a7819aba47e523965ce6",
    "calcSlug": 552422,
    "itemId": "552422",
    "itemName": "Eukanuba Adult Large Breed Dry Dog",
    "item-subtitle": "",
    "itemRecordId": "recAmx4ma56VRQ37e",
    "data-faqType": "compare-hello",
    "data-sort": 20,
    "data-one": " Adult Large Breed Dry Dog",
    "data-alt": " Adult Large Breed Dry Dog",
    "data-diet": "Grain",
    "data-brand": "6734",
    "brandId": "6734",
    "brands": "Eukanuba",
    "brandDisplay": "Eukanuba",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9x439c2566aba841b68d82073c26688034?version=1.0&width=2046&height=1536",
    "previewAlttag": " Adult Large Breed Dry Dog Dog Food Bag",
    "specs_price_per_bag": 77.99,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 23,
    "ga_crude_fat_%": 13,
    "ga_crude_fiber_%": 3.9,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3122.6415094339623,
    "ga_kcals_per_cup": 331,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "55909",
    "Slug": "55909",
    "collection-api": "",
    "itemID_api": "6844a7802f97b02373abb75e",
    "calcSlug": 55909,
    "itemId": "55909",
    "itemName": "Farmina Nd Ancestral Grain Chicken",
    "item-subtitle": "",
    "itemRecordId": "recMAiEuPgWvylbmZ",
    "data-faqType": "compare-hello",
    "data-sort": 21,
    "data-one": "Nd Ancestral Grain Chicken",
    "data-alt": "Nd Ancestral Grain Chicken",
    "data-diet": "Grain",
    "data-brand": "6749",
    "brandId": "6749",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/4731310f78da65bbe4e7fb85986f5d65c1409?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ancestral Grain Chicken Dog Food Bag",
    "specs_price_per_bag": 84.99,
    "specs_bag-size_lbs": 26.5,
    "item-status": "",
    "specs_primary_flavor": "Poultry",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3997,
    "ga_kcals_per_cup": 400,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "55911",
    "Slug": "55911",
    "collection-api": "",
    "itemID_api": "6844a77fb97bea2686617764",
    "calcSlug": 55911,
    "itemId": "55911",
    "itemName": "Farmina Nd Ocean Codfish Orange",
    "item-subtitle": "",
    "itemRecordId": "recO3o4bOV3H9GlFf",
    "data-faqType": "compare-hello",
    "data-sort": 22,
    "data-one": "Nd Ocean Codfish Orange",
    "data-alt": "Nd Ocean Codfish Orange",
    "data-diet": "Grain",
    "data-brand": "6749",
    "brandId": "6749",
    "brands": "Farmina",
    "brandDisplay": "Farmina",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/473133c1341cf43ea4d198d4e3de201225bfa?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nd Ocean Codfish Orange Dog Food Bag",
    "specs_price_per_bag": 99.99,
    "specs_bag-size_lbs": 26.5,
    "item-status": "",
    "specs_primary_flavor": "Fish",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 18,
    "ga_crude_fiber_%": 2.9,
    "ga_moisture_%": 9,
    "ga_kcals_per_kg": 3125,
    "ga_kcals_per_cup": 400,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  },
  {
    "Name": "841846",
    "Slug": "841846",
    "collection-api": "",
    "itemID_api": "6844a781faabc6e39ed1d7b9",
    "calcSlug": 841846,
    "itemId": "841846",
    "itemName": "Solid Gold Nutrient Boost Wolf King",
    "item-subtitle": "",
    "itemRecordId": "recJuEt1QWhaZnvFY",
    "data-faqType": "compare-hello",
    "data-sort": 23,
    "data-one": "Nutrient Boost Wolf King",
    "data-alt": "Nutrient Boost Wolf King",
    "data-diet": "Grain",
    "data-brand": "7536",
    "brandId": "7536",
    "brands": "Solid Gold",
    "brandDisplay": "Solid Gold",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xc275aeaaead6465abf3987c34513b166?version=1.0&width=2046&height=1536",
    "previewAlttag": "Nutrient Boost Wolf King Dog Food Bag",
    "specs_price_per_bag": 79.99,
    "specs_bag-size_lbs": 22,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 22,
    "ga_crude_fat_%": 9,
    "ga_crude_fiber_%": 4,
    "ga_moisture_%": 10,
    "ga_kcals_per_kg": 3207.547169811321,
    "ga_kcals_per_cup": 340,
    "diets_slugs": [
      "grain-inclusive"
    ],
    "ing_calcSlugs": []
  }
]
