export const DOG_DATA = {
  "HGW3D": {
    "Name": "Weimaraners",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recF7Zk0i9o0hgW3d",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 60,
    "data-five": "HGW3D",
    "data-sort": 85,
    "data-one": "Weimaraners",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Field Trials, Tracking, Agility",
    "job-suit": "",
    "common_misspellings": "Weimeraner, Wiemaraner",
    "other_common_names": "Weim, Grey Ghost",
    "common_initials": "WM, WEIM",
    "common_nickname": "Weims, Gray Ghost",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "ME0KB": {
    "Name": "Vizslas",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recDiWLGv4c2me0KB",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 57,
    "data-five": "ME0KB",
    "data-sort": 86,
    "data-one": "Vizslas",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Field Trials, Tracking, Agility",
    "job-suit": "Detection",
    "common_misspellings": "Vizslaa, Vizla",
    "other_common_names": "Hungarian Pointer",
    "common_initials": "VZ, VIZ",
    "common_nickname": "Red Dog",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "NTOHN": {
    "Name": "Rottweilers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recKmgv6NrIANTOhN",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 90,
    "data-five": "NTOHN",
    "data-sort": 87,
    "data-one": "Rottweilers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Highly Active",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs",
    "activity-suit": "Tracking",
    "job-suit": "Patrol, Protection",
    "common_misspellings": "Rotweiler, Rottwieler",
    "other_common_names": "Rottie",
    "common_initials": "RTW, ROT",
    "common_nickname": "Rottie",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "GF0GP": {
    "Name": "Labrador Retrievers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recMFQ72RdVXgF0GP",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 67,
    "data-five": "GF0GP",
    "data-sort": 88,
    "data-one": "Labrador Retrievers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Dock Diving, Field Trials, Tracking, Agility",
    "job-suit": "Detection",
    "common_misspellings": "Labradore, Labrodor",
    "other_common_names": "Lab",
    "common_initials": "LR, LAB",
    "common_nickname": "Lab, Labby",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "8KTYX": {
    "Name": "Golden Retrievers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recN9zAPh1R68kTYx",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 65,
    "data-five": "8KTYX",
    "data-sort": 89,
    "data-one": "Golden Retrievers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Agility Dogs",
    "activity-suit": "Dock Diving, Field Trials, Agility",
    "job-suit": "",
    "common_misspellings": "Golden Retreiver, Goldens",
    "other_common_names": "Goldie",
    "common_initials": "GR, GOLD",
    "common_nickname": "Goldie",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "MLXGP": {
    "Name": "German Shorthaired Pointers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recs3PG2jC9RMlxGp",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 57,
    "data-five": "MLXGP",
    "data-sort": 90,
    "data-one": "German Shorthaired Pointers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Field Trials, Tracking, Agility",
    "job-suit": "",
    "common_misspellings": "German Shorthair, Shorthair",
    "other_common_names": "GSP",
    "common_initials": "GSP, GSHP",
    "common_nickname": "Shorthair",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "2ZREE": {
    "Name": "German Shepherds",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recmQ5ncvwYR2zrEe",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 70,
    "data-five": "2ZREE",
    "data-sort": 91,
    "data-one": "German Shepherds",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Working",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Tracking, Agility",
    "job-suit": "Patrol, Protection, Detection",
    "common_misspellings": "German Shepard, Sheperd",
    "other_common_names": "GSD",
    "common_initials": "GS, GSD",
    "common_nickname": "Shep",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "VJYZS": {
    "Name": "Dutch Shepherds",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recGGMwU5tMlvJyZS",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 70,
    "data-five": "VJYZS",
    "data-sort": 92,
    "data-one": "Dutch Shepherds",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Working",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Tracking, Agility",
    "job-suit": "Patrol, Protection, Detection",
    "common_misspellings": "Dutch Shepard, Duch Shepherd",
    "other_common_names": "Hollandse Herder",
    "common_initials": "DS, DUTCH",
    "common_nickname": "Dutchie",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "4TIL1": {
    "Name": "Doberman Pinschers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recZEWtYdOmD4TIl1",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 75,
    "data-five": "4TIL1",
    "data-sort": 93,
    "data-one": "Doberman Pinschers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Highly Active",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs",
    "activity-suit": "Tracking",
    "job-suit": "Patrol, Protection",
    "common_misspellings": "Doberman Pincher, Dobermann",
    "other_common_names": "Dobie",
    "common_initials": "DP, DOB",
    "common_nickname": "Dobie",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "UQ7MN": {
    "Name": "Chesapeake Bay Retrievers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recOyhZvjPMluq7mN",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 68,
    "data-five": "UQ7MN",
    "data-sort": 94,
    "data-one": "Chesapeake Bay Retrievers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs",
    "activity-suit": "Dock Diving, Field Trials, Tracking",
    "job-suit": "",
    "common_misspellings": "Chessie, Chesapeake Retriever",
    "other_common_names": "Chessie",
    "common_initials": "CBR, CHESS",
    "common_nickname": "Chessie",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "MOVBB": {
    "Name": "Border Collies",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "rec8LciBFGslMOvbB",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 42,
    "data-five": "MOVBB",
    "data-sort": 95,
    "data-one": "Border Collies",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Working Dogs, Active Dogs, Performance Dogs, Agility Dogs",
    "activity-suit": "Agility",
    "job-suit": "",
    "common_misspellings": "Boarder Collie, Border Colie",
    "other_common_names": "BC",
    "common_initials": "BC, BCollie",
    "common_nickname": "Collie, BC",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  },
  "IPVOO": {
    "Name": "Belgian Malinois",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recgTbmD2K7rIpVoO",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 60,
    "data-five": "IPVOO",
    "data-sort": 96,
    "data-one": "Belgian Malinois",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Working",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Dock Diving, Tracking, Agility",
    "job-suit": "Patrol, Protection, Detection",
    "common_misspellings": "Belgian Malinios, Malinwa",
    "other_common_names": "Malinois, Mali",
    "common_initials": "BM, MAL",
    "common_nickname": "Mali",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": ""
  }
};
