export const DOG_DATA = [
  {
    "Name": "Weimaraners",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recF7Zk0i9o0hgW3d",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 60,
    "data-five": "HGW3D",
    "data-sort": 85,
    "data-one": "Weimaraners",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Field Trials, Tracking, Agility",
    "job-suit": "",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Vizslas",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recDiWLGv4c2me0KB",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 57,
    "data-five": "ME0KB",
    "data-sort": 86,
    "data-one": "Vizslas",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Field Trials, Tracking, Agility",
    "job-suit": "Detection",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Rottweilers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recKmgv6NrIANTOhN",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 90,
    "data-five": "NTOHN",
    "data-sort": 87,
    "data-one": "Rottweilers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Highly Active",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs",
    "activity-suit": "Tracking",
    "job-suit": "Patrol, Protection",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Labrador Retrievers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recMFQ72RdVXgF0GP",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 67,
    "data-five": "GF0GP",
    "data-sort": 88,
    "data-one": "Labrador Retrievers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Dock Diving, Field Trials, Tracking, Agility",
    "job-suit": "Detection",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Golden Retrievers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recN9zAPh1R68kTYx",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 65,
    "data-five": "8KTYX",
    "data-sort": 89,
    "data-one": "Golden Retrievers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Agility Dogs",
    "activity-suit": "Dock Diving, Field Trials, Agility",
    "job-suit": "",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "German Shorthaired Pointers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recs3PG2jC9RMlxGp",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 57,
    "data-five": "MLXGP",
    "data-sort": 90,
    "data-one": "German Shorthaired Pointers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Field Trials, Tracking, Agility",
    "job-suit": "",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "German Shepherds",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recmQ5ncvwYR2zrEe",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 70,
    "data-five": "2ZREE",
    "data-sort": 91,
    "data-one": "German Shepherds",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Working",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Tracking, Agility",
    "job-suit": "Patrol, Protection, Detection",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Dutch Shepherds",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recGGMwU5tMlvJyZS",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 70,
    "data-five": "VJYZS",
    "data-sort": 92,
    "data-one": "Dutch Shepherds",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Working",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Tracking, Agility",
    "job-suit": "Patrol, Protection, Detection",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Doberman Pinschers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recZEWtYdOmD4TIl1",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 75,
    "data-five": "4TIL1",
    "data-sort": 93,
    "data-one": "Doberman Pinschers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Highly Active",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs",
    "activity-suit": "Tracking",
    "job-suit": "Patrol, Protection",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Chesapeake Bay Retrievers",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recOyhZvjPMluq7mN",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 68,
    "data-five": "UQ7MN",
    "data-sort": 94,
    "data-one": "Chesapeake Bay Retrievers",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs",
    "activity-suit": "Dock Diving, Field Trials, Tracking",
    "job-suit": "",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Border Collies",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "rec8LciBFGslMOvbB",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 42,
    "data-five": "MOVBB",
    "data-sort": 95,
    "data-one": "Border Collies",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "activity-level": "Active",
    "group-suit": "Working Dogs, Active Dogs, Performance Dogs, Agility Dogs",
    "activity-suit": "Agility",
    "job-suit": "",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Belgian Malinois",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recgTbmD2K7rIpVoO",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "defaulWeight": 60,
    "data-five": "IPVOO",
    "data-sort": 96,
    "data-one": "Belgian Malinois",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "activity-level": "Working",
    "group-suit": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "activity-suit": "Dock Diving, Tracking, Agility",
    "job-suit": "Patrol, Protection, Detection",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "",
    "dogs-nutritional-focus-description2": "",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  }
];
