[
  {
    "Name": "Weimaraners",
    "Slug": "most-recommended-dog-food-for-weimaraners",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b333f9",
    "canonical": "most-recommended-dog-food-for-weimaraners",
    "recordId": "recSXosv53LnleSyj",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "weimaraners",
    "dogName": "",
    "data-five": "LESYJ",
    "data-sort": 24,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Sleek, speedy, and athletic, Weimaraners thrive on food rich in protein, fat, and antioxidants to support their active lifestyle and maintain muscle tone.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "J76F7",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "4CQVY",
      "YLNYF",
      "UQHTP"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "KJCYZ",
      "MXQV1",
      "SKYQA"
    ],
    "dog1-data-fives": [
      "LCCV8",
      "9V6Z8",
      "MM5SK",
      "OSXWL",
      "SOG9C",
      "PEG2O",
      "HKAHU",
      "EP5IL",
      "GAQ7O",
      "KCDKK",
      "WBT8X",
      "LESYJ"
    ],
    "dog2-data-fives": "LESYJ",
    "common_misspellings": "Weimeraner, Weimereiner, Weimy",
    "other_common_names": "Weim",
    "common_initials": "Weim",
    "common_nickname": "Weim, Grey Ghost",
    "dogs-nutritional-focus-title": "Stamina & Focus",
    "dogs-nutritional-focus-description2": "Require a calorie-dense, highly digestible diet to support fast runs and sustained athleticism, with healthy fats and balanced minerals for joint and muscle recovery.",
    "height_range": "",
    "weight_range": "55-85 lbs",
    "feeding_range": "1.60 - 2.21 cups",
    "max_weight": 85,
    "min_weight": 55,
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Vizslas",
    "Slug": "most-recommended-dog-food-for-vizslas",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b33437",
    "canonical": "most-recommended-dog-food-for-vizslas",
    "recordId": "recdQQnQUPX6N6m4b",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "vizslas",
    "dogName": "",
    "data-five": "N6M4B",
    "data-sort": 29,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Vizslas are athletic, spirited, and affectionate sporting dogs celebrated for their agility and stamina. ",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "KEB4Z",
      "4CQVY",
      "YLNYF",
      "UQHTP",
      "YD8CG",
      "XORST",
      "J76F7",
      "XUUYO",
      "UQ30T",
      "MRSTT",
      "XGD4Z",
      "EK1NU",
      "IIDS9",
      "UDMZM",
      "PN28C",
      "NVHW0",
      "OWC0W"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "SKYQA",
      "9QHMW",
      "JDRWK"
    ],
    "dog1-data-fives": [
      "LCCV8",
      "9V6Z8",
      "MM5SK",
      "OSXWL",
      "SOG9C",
      "PEG2O",
      "N6M4B"
    ],
    "dog2-data-fives": "N6M4B",
    "common_misspellings": "Vizsla, Vizala, Vizla",
    "other_common_names": "Hungarian Pointer",
    "common_initials": "-",
    "common_nickname": "Viz, Velcro Dog",
    "dogs-nutritional-focus-title": "Endurance Support",
    "dogs-nutritional-focus-description2": "These energetic companions excel in running, hunting, and a wide range of canine sports. To support their high activity levels, Vizslas benefit from highly digestible, nutrient-rich food packed with lean protein, healthy fats, and upgraded vitamins. A well-balanced formula helps maintain their lean muscle, energy, and vibrant coats, keeping them ready for adventure every day.",
    "height_range": "21 - 24 inches",
    "weight_range": "50 - 65 lbs",
    "feeding_range": "1.49 - 1.81 cups",
    "max_weight": 65,
    "min_weight": 50,
    "life_span": "10 - 14 years",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Rottweilers",
    "Slug": "most-recommended-dog-food-for-rottweilers",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b332c0",
    "canonical": "most-recommended-dog-food-for-rottweilers",
    "recordId": "recXLBlyOhwxKc9UL",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "rottweilers",
    "dogName": "",
    "data-five": "KC9UL",
    "data-sort": 21,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Strong, confident, and loyal, Rottweilers benefit from balanced diets that promote joint health, lean mass, and energy for both protection work and family activities.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "J76F7",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C",
      "XORST",
      "XUUYO",
      "NVUQ6",
      "L5O6A",
      "OWC0W",
      "EK1NU",
      "IIDS9",
      "AGJPT",
      "KEB4Z",
      "UDMZM"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "KJCYZ",
      "VFKR6",
      "MXQV1"
    ],
    "dog1-data-fives": [
      "Y6PGF",
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "CSIRP",
      "MNLTS",
      "GAQ7O",
      "KCDKK",
      "KC9UL"
    ],
    "dog2-data-fives": "KC9UL",
    "common_misspellings": "Rottweiler, Rotweiler, Rottie",
    "other_common_names": "Rott, Rottie",
    "common_initials": "Rottie, RW",
    "common_nickname": "Rottie, Rotty",
    "dogs-nutritional-focus-title": "Strength & Stamina",
    "dogs-nutritional-focus-description2": "Benefit from calorie-dense, high-protein food with added performance minerals and antioxidants to maintain muscle mass, energy, and immune resilience during demanding activities.",
    "height_range": "22 - 27 inches",
    "weight_range": "75 - 110 lbs",
    "feeding_range": "2.01 - 2.68 cups",
    "max_weight": 110,
    "min_weight": 75,
    "life_span": "8 - 10 years",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Labrador Retrievers",
    "Slug": "most-recommended-dog-food-for-labrador-retrievers",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b333b2",
    "canonical": "most-recommended-dog-food-for-labrador-retrievers",
    "recordId": "recqvko6NOHOHwZh0",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "labrador-retrievers",
    "dogName": "",
    "data-five": "HWZH0",
    "data-sort": 17,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "America’s favorite sporting companion, Labs are always on the go. Nutrition supporting strong muscles, joint health, and a healthy weight keeps them ready for any adventure.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "YD8CG",
      "U9EU7",
      "NVHW0",
      "OWC0W",
      "XGD4Z",
      "PN28C",
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "4CQVY",
      "YLNYF",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "JDRWK",
      "MXQV1",
      "SKYQA"
    ],
    "dog1-data-fives": [
      "Y6PGF",
      "LCCV8",
      "9V6Z8",
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "SOG9C",
      "PEG2O",
      "CSIRP",
      "HKAHU",
      "UTHHC",
      "EP5IL",
      "GAQ7O",
      "KCDKK",
      "WBT8X",
      "HWZH0"
    ],
    "dog2-data-fives": "HWZH0",
    "common_misspellings": "Labrodor, Lab Retriever, Labradore",
    "other_common_names": "Lab",
    "common_initials": "Lab, LR",
    "common_nickname": "Lab, Labby",
    "dogs-nutritional-focus-title": "Endurance & Recovery",
    "dogs-nutritional-focus-description2": "Benefit from highly digestible, energy-rich diets with healthy fats and balanced nutrition to support stamina, joint health, and a shiny coat for all-day play.",
    "height_range": "21.5 - 24.5 inches",
    "weight_range": "55 - 80 lbs",
    "feeding_range": "1.60 - 2.11 cups",
    "max_weight": 80,
    "min_weight": 55,
    "life_span": "10 - 13 years",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Golden Retrievers",
    "Slug": "most-recommended-dog-food-for-golden-retrievers",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b333de",
    "canonical": "most-recommended-dog-food-for-golden-retrievers",
    "recordId": "rec1LAPs61O8tq87j",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "golden-retrievers",
    "dogName": "",
    "data-five": "TQ87J",
    "data-sort": 35,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Outgoing and athletic, Goldens love water, fetch, and family. Food rich in healthy fats, protein, and antioxidants keeps their coat shiny and energy high.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "J76F7",
      "JEBP3",
      "MRSTT",
      "XV780",
      "PN28C",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "UQHTP",
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "MXQV1",
      "KJCYZ",
      "GKJX3",
      "NG6TL"
    ],
    "dog1-data-fives": [
      "LCCV8",
      "9V6Z8",
      "MM5SK",
      "OSXWL",
      "SOG9C",
      "PEG2O",
      "HKAHU",
      "UTHHC",
      "EP5IL",
      "GAQ7O",
      "KCDKK",
      "WBT8X",
      "TQ87J"
    ],
    "dog2-data-fives": "TQ87J",
    "common_misspellings": "Golden Retreiver, Gold Retriever",
    "other_common_names": "Golden",
    "common_initials": "GR",
    "common_nickname": "Goldie, Golden",
    "dogs-nutritional-focus-title": "Focus & Mobility Support",
    "dogs-nutritional-focus-description2": "Require high-protein, balanced nutrition with performance minerals and probiotics to support mental sharpness, mobility, and immune health through active days.",
    "height_range": "",
    "weight_range": "55-75 lbs",
    "feeding_range": "1.60 - 2.01 cups",
    "max_weight": 75,
    "min_weight": 55,
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "German Shorthaired Pointers",
    "Slug": "most-recommended-dog-food-for-german-shorthaired-pointers",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b3310d",
    "canonical": "most-recommended-dog-food-for-german-shorthaired-pointers",
    "recordId": "reccy3HCNx5VUt6Sq",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "german-shorthaired-pointers",
    "dogName": "",
    "data-five": "UT6SQ",
    "data-sort": 37,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Built for action—hunting, field trials, or family fun—these dogs need energy-dense food for muscle recovery, healthy joints, and lasting endurance.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "YD8CG",
      "U9EU7",
      "NVHW0",
      "OWC0W",
      "XGD4Z",
      "PN28C",
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "XORST",
      "XUUYO",
      "NVUQ6",
      "L5O6A",
      "XV780",
      "EK1NU",
      "AGJPT"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "JDRWK",
      "MXQV1",
      "VFKR6"
    ],
    "dog1-data-fives": [
      "LCCV8",
      "9V6Z8",
      "MM5SK",
      "SOG9C",
      "PEG2O",
      "EP5IL",
      "KCDKK",
      "WBT8X",
      "UT6SQ"
    ],
    "dog2-data-fives": "UT6SQ",
    "common_misspellings": "German Shorthair, Shorthaired Pointer",
    "other_common_names": "GSP, Shorthair",
    "common_initials": "GSP",
    "common_nickname": "Shorthair",
    "dogs-nutritional-focus-title": "Stamina & Skin Health",
    "dogs-nutritional-focus-description2": "Thrive on balanced, calorie-dense food with healthy fats, antioxidants, and nutrients that support endurance and a glossy coat.",
    "height_range": "",
    "weight_range": "56-65 lbs",
    "feeding_range": "1.37 - 1.91 cups",
    "max_weight": 70,
    "min_weight": 45,
    "life_span": "",
    "color_coat": "",
    "activity_level": {
      "id": "selNUePvjDUsoDLkw",
      "name": "Highly Active",
      "color": "blueLight2"
    }
  },
  {
    "Name": "German Shepherds",
    "Slug": "most-recommended-dog-food-for-german-shepherds",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b34566",
    "canonical": "most-recommended-dog-food-for-german-shepherds",
    "recordId": "recmwXhqsEdTGVJdB",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "german-shepherds",
    "dogName": "",
    "data-five": "GVJDB",
    "data-sort": 13,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Legendary for their versatility—service, police, sport, or family—GSDs need high-quality nutrition for muscle strength, joint support, and all-day performance.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "YD8CG",
      "XORST",
      "J76F7",
      "XUUYO",
      "UQ30T",
      "MRSTT",
      "XGD4Z",
      "EK1NU",
      "IIDS9",
      "UDMZM",
      "PN28C",
      "KEB4Z",
      "XV780"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "9QHMW",
      "MXQV1",
      "KJCYZ"
    ],
    "dog1-data-fives": [
      "Y6PGF",
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "CSIRP",
      "HKAHU",
      "MNLTS",
      "OP4RY",
      "UTHHC",
      "5PFWE",
      "GAQ7O",
      "KCDKK",
      "GVJDB"
    ],
    "dog2-data-fives": "GVJDB",
    "common_misspellings": "German Shepard, German Sheperd",
    "other_common_names": "Alsatian",
    "common_initials": "GSD",
    "common_nickname": "Shep, German, Alsatian",
    "dogs-nutritional-focus-title": "All-Day Energy & Lean Muscle",
    "dogs-nutritional-focus-description2": "Benefit from calorie-dense, high-protein diets with upgraded vitamins and balanced minerals for stamina, muscle tone, and post-exercise recovery.",
    "height_range": "",
    "weight_range": "50 - 90 lbs",
    "feeding_range": "1.49 - 2.31 cups",
    "max_weight": 90,
    "min_weight": 50,
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Dutch Shepherds",
    "Slug": "most-recommended-dog-food-for-dutch-shepherds",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b3353c",
    "canonical": "most-recommended-dog-food-for-dutch-shepherds",
    "recordId": "recdw7iSXJkbVMXSF",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "dutch-shepherds",
    "dogName": "",
    "data-five": "VMXSF",
    "data-sort": 39,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Agile and resilient, Dutch Shepherds are ideal for working roles. A balanced, high-protein diet helps maintain their strength, endurance, and healthy coat.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "J76F7",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "UQHTP",
      "KEB4Z",
      "IIDS9",
      "UDMZM"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "KJCYZ",
      "GKJX3",
      "MXQV1"
    ],
    "dog1-data-fives": [
      "Y6PGF",
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "CSIRP",
      "HKAHU",
      "MNLTS",
      "OP4RY",
      "UTHHC",
      "5PFWE",
      "GAQ7O",
      "KCDKK",
      "VMXSF"
    ],
    "dog2-data-fives": "VMXSF",
    "common_misspellings": "Dutch Sheperd, Dutch Shepard",
    "other_common_names": "Hollandse Herdershond",
    "common_initials": "DS",
    "common_nickname": "Dutchie, Holland Dog",
    "dogs-nutritional-focus-title": "Muscle Maintenance & Agility",
    "dogs-nutritional-focus-description2": "Need high-protein, calorie-dense food with performance minerals and probiotics to keep muscles strong and energy consistent during varied activity.",
    "height_range": "22 - 24.5 inches",
    "weight_range": "50 - 70 lbs",
    "feeding_range": "1.49 - 1.91 cups",
    "max_weight": 70,
    "min_weight": 50,
    "life_span": "15 years",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Doberman Pinschers",
    "Slug": "most-recommended-dog-food-for-doberman-pinschers",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b33281",
    "canonical": "most-recommended-dog-food-for-doberman-pinschers",
    "recordId": "reclFa4GTihCCezhb",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "doberman-pinschers",
    "dogName": "",
    "data-five": "CEZHB",
    "data-sort": 8,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Powerful and loyal protectors, Dobermans benefit from food that supports lean muscle, heart health, and the energy needed for demanding training or guard work.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "KEB4Z",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP",
      "J76F7",
      "JEBP3",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C",
      "NVHW0",
      "OWC0W",
      "IIDS9",
      "UDMZM"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "SKYQA",
      "KJCYZ",
      "TQRAE",
      "MXQV1"
    ],
    "dog1-data-fives": [
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "CSIRP",
      "MNLTS",
      "UTHHC",
      "GAQ7O",
      "KCDKK",
      "CEZHB"
    ],
    "dog2-data-fives": "CEZHB",
    "common_misspellings": "Doberman, Dobermann, Dober man",
    "other_common_names": "Doberman",
    "common_initials": "DP, Dobe",
    "common_nickname": "Dobe, Dobie",
    "dogs-nutritional-focus-title": "Lean Muscle & Recovery",
    "dogs-nutritional-focus-description2": "Require highly digestible, protein-rich diets with balanced minerals and healthy fats to support muscle maintenance and rapid recovery from intense work.",
    "height_range": "24 - 28 inches",
    "weight_range": "66 - 88 lbs",
    "feeding_range": "1.83 - 2.27 cups",
    "max_weight": 88,
    "min_weight": 66,
    "life_span": "10 years",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Chesapeake Bay Retrievers",
    "Slug": "most-recommended-dog-food-for-chesapeake-bay-retrievers",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b34565",
    "canonical": "most-recommended-dog-food-for-chesapeake-bay-retrievers",
    "recordId": "recJ08OjLrzzEA62u",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "chesapeake-bay-retrievers",
    "dogName": "",
    "data-five": "EA62U",
    "data-sort": 10,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Chesapeake Bay Retrievers are rugged, energetic, and versatile sporting dogs known for their strength, endurance, and love of water. ",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "YD8CG",
      "XORST",
      "J76F7",
      "XUUYO",
      "UQ30T",
      "MRSTT",
      "XGD4Z",
      "EK1NU",
      "IIDS9",
      "UDMZM",
      "PN28C",
      "KEB4Z",
      "XV780"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "9QHMW",
      "MXQV1",
      "KJCYZ"
    ],
    "dog1-data-fives": [
      "LCCV8",
      "9V6Z8",
      "MM5SK",
      "OSXWL",
      "SOG9C",
      "PEG2O",
      "EA62U"
    ],
    "dog2-data-fives": "EA62U",
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Endurance & Immune Support",
    "dogs-nutritional-focus-description2": "Originally bred for retrieving game in cold, challenging environments, they thrive on high-protein, calorie-dense diets that support muscle recovery and sustained energy. Their active lifestyles demand balanced nutrition with quality fats, performance minerals, and healthy skin and coat support to keep them at their best on land and in the water.",
    "height_range": "21 - 26 inches",
    "weight_range": "55 - 80 lbs",
    "feeding_range": "1.6 - 2.11 cups",
    "max_weight": 80,
    "min_weight": 55,
    "life_span": "10 - 13 years",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Border Collies",
    "Slug": "most-recommended-dog-food-for-border-collies",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b3339f",
    "canonical": "most-recommended-dog-food-for-border-collies",
    "recordId": "recSMhjh8u319cDZc",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "border-collies",
    "dogName": "",
    "data-five": "9CDZC",
    "data-sort": 4,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Famous for their speed and sharp mind, Border Collies need nutrient-rich food to support their stamina, quick thinking, and all-day activity in fields or at play.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "YD8CG",
      "XORST",
      "J76F7",
      "XUUYO",
      "MRSTT",
      "XGD4Z",
      "EK1NU",
      "PN28C",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "MXQV1",
      "9QHMW",
      "GKJX3"
    ],
    "dog1-data-fives": [
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "HKAHU",
      "OP4RY",
      "UTHHC",
      "5PFWE",
      "EP5IL",
      "KCDKK",
      "9CDZC"
    ],
    "dog2-data-fives": "9CDZC",
    "common_misspellings": "Border Collie, Boarder Collie",
    "other_common_names": "Collie (Border)",
    "common_initials": "BC",
    "common_nickname": "Border, Sheepdog",
    "dogs-nutritional-focus-title": "Energy & Cognitive Focus",
    "dogs-nutritional-focus-description2": "Require highly digestible, high-energy food with balanced nutrition, upgraded vitamins, and probiotics to fuel their stamina and mental focus.",
    "height_range": "18 - 22 inches",
    "weight_range": "30 - 45 lbs",
    "feeding_range": "1.01 - 1.37 cups",
    "max_weight": 45,
    "min_weight": 30,
    "life_span": "12 - 16 years",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Belgian Malinois",
    "Slug": "most-recommended-dog-food-for-belgian-malinois",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "647ddb9037101ce399b3333c",
    "canonical": "most-recommended-dog-food-for-belgian-malinois",
    "recordId": "recUIPs8vEq8j5ghM",
    "recordType": "dg",
    "recordStatus": "",
    "calcSlug": "belgian-malinois",
    "dogName": "",
    "data-five": "J5GHM",
    "data-sort": 19,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Exceptionally driven, athletic, and intelligent—these dogs excel at police, military, and sport jobs. They thrive on performance nutrition with high protein and fat for endless energy and recovery.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "XORST",
      "XUUYO",
      "NVUQ6",
      "L5O6A",
      "OWC0W",
      "XV780",
      "EK1NU",
      "IIDS9",
      "AGJPT",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "UQHTP",
      "UQ30T",
      "KEB4Z",
      "UDMZM"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "VFKR6",
      "GKJX3",
      "MXQV1"
    ],
    "dog1-data-fives": [
      "Y6PGF",
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "CSIRP",
      "HKAHU",
      "MNLTS",
      "OP4RY",
      "UTHHC",
      "EP5IL",
      "GAQ7O",
      "KCDKK",
      "J5GHM"
    ],
    "dog2-data-fives": "J5GHM",
    "common_misspellings": "Malanois, Mallinois, Malinios",
    "other_common_names": "Malinois",
    "common_initials": "Mal, BMI",
    "common_nickname": "Mal, Mali",
    "dogs-nutritional-focus-title": "Elite Performance Fuel",
    "dogs-nutritional-focus-description2": "Need high-protein, calorie-dense, performance-driven nutrition with antioxidants and probiotics to maintain strength, agility, and recovery in demanding roles.",
    "height_range": "22 - 26 inches",
    "weight_range": "40 - 80 lbs",
    "feeding_range": "1.26 - 2.11 cups",
    "max_weight": 80,
    "min_weight": 40,
    "life_span": "12 - 14 years",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Dock Diving",
    "Slug": "best-dry-dog-food-for-dock-diving",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d8995faed81098598a8d",
    "canonical": "best-dry-dog-food-for-dock-diving",
    "recordId": "recGlHtPfsgMep5iL",
    "recordType": "ac",
    "recordStatus": "",
    "calcSlug": "dock-diving",
    "dogName": "",
    "data-five": "EP5IL",
    "data-sort": 11,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Jumping for distance or height into water—demands stamina, lean muscle, and healthy skin/coat. High-protein diets and omega-3s help support performance.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "NVHW0",
      "J76F7",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C",
      "YD8CG",
      "U9EU7",
      "OWC0W",
      "XGD4Z",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "NG6TL",
      "VYSPN",
      "KJCYZ",
      "JDRWK",
      "GKJX3"
    ],
    "dog1-data-fives": "EP5IL",
    "dog2-data-fives": [
      "HWZH0",
      "TQ87J",
      "UT6SQ",
      "LESYJ",
      "J5GHM",
      "9CDZC"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Endurance & Hydration",
    "dogs-nutritional-focus-description2": "Dock diving dogs benefit from high-energy, calorie-dense foods with Performance Minerals for hydration and muscle strength. Healthy Skin and Coat nutrients help maintain waterproofing, and Probiotics keep their digestive health on point for repeat jumps.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Field Dogs",
    "Slug": "top-dry-dog-food-for-field-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89a7774262cac1b6081",
    "canonical": "top-dry-dog-food-for-field-dogs",
    "recordId": "recVZbjuizvC9V6z8",
    "recordType": "gp",
    "recordStatus": "",
    "calcSlug": "field-dogs",
    "dogName": "",
    "data-five": "9V6Z8",
    "data-sort": 5,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Bred for long days in the field, tracking, flushing, or retrieving. Performance food gives them the energy, hydration, and muscle support needed to last all day.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "NVHW0",
      "OWC0W",
      "C6HRL",
      "J76F7",
      "JEBP3",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "TQRAE",
      "VYSPN",
      "KJCYZ"
    ],
    "dog1-data-fives": "9V6Z8",
    "dog2-data-fives": [
      "UT6SQ",
      "LESYJ",
      "HWZH0",
      "TQ87J",
      "N6M4B",
      "EA62U"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Field-Tested Performance Nutrition",
    "dogs-nutritional-focus-description2": "Thrive on high-fat, nutrient-rich diets for long working days and quick recovery.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Gun Dogs",
    "Slug": "top-dry-dog-food-for-gun-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89ab7a36e9c4af94a38",
    "canonical": "top-dry-dog-food-for-gun-dogs",
    "recordId": "recopYGRDuXwSog9C",
    "recordType": "gp",
    "recordStatus": "",
    "calcSlug": "gun-dogs",
    "dogName": "",
    "data-five": "SOG9C",
    "data-sort": 34,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Skilled hunting partners for flushing and retrieving game. Nutrient-dense food helps them perform at their best on long hunts and fast retrieves.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "J76F7",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "VYSPN",
      "NG6TL",
      "KJCYZ"
    ],
    "dog1-data-fives": "SOG9C",
    "dog2-data-fives": [
      "UT6SQ",
      "LESYJ",
      "TQ87J",
      "HWZH0",
      "N6M4B",
      "EA62U"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Energy and Joint Support",
    "dogs-nutritional-focus-description2": "Require high-protein, calorie-dense food for bursts of activity and joint health over long days.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Bird Dogs",
    "Slug": "top-dry-dog-food-for-bird-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89a825d5d8fd608e2a5",
    "canonical": "top-dry-dog-food-for-bird-dogs",
    "recordId": "recL9zmjK70XlCCv8",
    "recordType": "gp",
    "recordStatus": "",
    "calcSlug": "bird-dogs",
    "dogName": "",
    "data-five": "LCCV8",
    "data-sort": 23,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Expert upland and waterfowl hunters who rely on stamina and sharp senses. Balanced nutrition fuels their endurance, focus, and ability to retrieve in any conditions.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "KEB4Z",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP",
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5ELBD",
      "ZAPVO",
      "XORST",
      "XUUYO",
      "NVUQ6",
      "L5O6A",
      "OWC0W",
      "XV780",
      "EK1NU",
      "IIDS9",
      "AGJPT"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "SKYQA",
      "NG6TL",
      "VFKR6"
    ],
    "dog1-data-fives": "LCCV8",
    "dog2-data-fives": [
      "UT6SQ",
      "LESYJ",
      "TQ87J",
      "HWZH0",
      "N6M4B",
      "EA62U"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Sharp Focus and Recovery Nutrition",
    "dogs-nutritional-focus-description2": "Need high-protein, digestible food to support energy, focus, and recovery after long sessions outdoors.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Sporting Dogs",
    "Slug": "popular-dog-food-for-sporting-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89cd4da2f01917322c3",
    "canonical": "popular-dog-food-for-sporting-dogs",
    "recordId": "rec1EuIoHx96PEg2O",
    "recordType": "gp",
    "recordStatus": "",
    "calcSlug": "sporting-dogs",
    "dogName": "",
    "data-five": "PEG2O",
    "data-sort": 32,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Versatile, athletic dogs bred for hunting and retrieving. A diet rich in protein, fat, and essential nutrients keeps them in top condition for every adventure.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0",
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "VYSPN",
      "MXQV1",
      "GKJX3"
    ],
    "dog1-data-fives": "PEG2O",
    "dog2-data-fives": [
      "UT6SQ",
      "TQ87J",
      "HWZH0",
      "LESYJ",
      "N6M4B",
      "EA62U"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Peak Stamina and Recovery",
    "dogs-nutritional-focus-description2": "Thrive on calorie-dense, balanced food for sustained activity and efficient recovery after training or competition.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Field Trials",
    "Slug": "best-dry-dog-food-for-field-trials",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89b7bf5910666fb3278",
    "canonical": "best-dry-dog-food-for-field-trials",
    "recordId": "recs8guT0HS8WBT8x",
    "recordType": "ac",
    "recordStatus": "",
    "calcSlug": "field-trials",
    "dogName": "",
    "data-five": "WBT8X",
    "data-sort": 41,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Simulates hunting scenarios for retrieving and pointing breeds—requires endurance, focus, and strength. Nutrient-rich formulas help maintain stamina all day.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "KEB4Z",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP",
      "UQ30T",
      "IIDS9",
      "UDMZM",
      "J76F7",
      "JEBP3",
      "MRSTT",
      "XV780",
      "PN28C",
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5ELBD",
      "ZAPVO"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "SKYQA",
      "MXQV1",
      "KJCYZ",
      "NG6TL"
    ],
    "dog1-data-fives": "WBT8X",
    "dog2-data-fives": [
      "UT6SQ",
      "TQ87J",
      "HWZH0",
      "LESYJ"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Stamina & Focus",
    "dogs-nutritional-focus-description2": "Field trial participants thrive on highly digestible, balanced nutrition with Performance Minerals and High Energy formulas for sustained stamina, mental focus, and recovery through hours of work.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Search and Rescue Dogs",
    "Slug": "dog-food-formulated-for-search-and-rescue-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89cebdff8ac7c51e382",
    "canonical": "dog-food-formulated-for-search-and-rescue-dogs",
    "recordId": "rec58cZr3dJ2hkahu",
    "recordType": "jb",
    "recordStatus": "",
    "calcSlug": "search-and-rescue-dogs",
    "dogName": "",
    "data-five": "HKAHU",
    "data-sort": 16,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Search through rubble, wilderness, or disaster zones—sometimes for days. Nutrient-dense, highly digestible diets give them the sustained energy and mental focus to keep searching.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "C6HRL",
      "NVHW0",
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "MXQV1",
      "VYSPN",
      "SKYQA",
      "GKJX3"
    ],
    "dog1-data-fives": "HKAHU",
    "dog2-data-fives": [
      "9CDZC",
      "HWZH0",
      "TQ87J",
      "J5GHM",
      "VMXSF",
      "LESYJ",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Endurance & Digestive Health",
    "dogs-nutritional-focus-description2": "SAR dogs need balanced, calorie-dense nutrition for all-day search work. Highly Digestible ingredients and Probiotics aid in maintaining gut health and energy.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Obedience",
    "Slug": "best-dry-dog-food-for-obedience",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89ba4d4e8ef3cbe31ba",
    "canonical": "best-dry-dog-food-for-obedience",
    "recordId": "recTQno2QGPB5pFwe",
    "recordType": "ac",
    "recordStatus": "",
    "calcSlug": "obedience",
    "dogName": "",
    "data-five": "5PFWE",
    "data-sort": 3,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Precision training and competition—requires focus, quick response, and calm energy. Nutrients that support brain health and steady energy release are optimal.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "KEB4Z",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP",
      "UQ30T",
      "IIDS9",
      "UDMZM"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "SKYQA",
      "MXQV1",
      "GKJX3"
    ],
    "dog1-data-fives": "5PFWE",
    "dog2-data-fives": [
      "9CDZC",
      "VMXSF",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Focus & Digestive Health",
    "dogs-nutritional-focus-description2": "Obedience dogs benefit from highly digestible foods with Balanced Nutrition and Probiotics for sharp mental focus and regular digestion.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Tracking",
    "Slug": "best-dry-dog-food-for-tracking",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89c89b3b2b8d9c53041",
    "canonical": "best-dry-dog-food-for-tracking",
    "recordId": "recUKVSfJUmRGaQ7o",
    "recordType": "ac",
    "recordStatus": "",
    "calcSlug": "tracking",
    "dogName": "",
    "data-five": "GAQ7O",
    "data-sort": 12,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Scent-focused sport requiring stamina, mental focus, and calm energy over long distances. Diets that balance protein and slow-burning carbs are beneficial.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "C6HRL",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO",
      "YD8CG",
      "XORST",
      "J76F7",
      "XUUYO",
      "MRSTT",
      "XGD4Z",
      "EK1NU",
      "PN28C",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "MXQV1",
      "NG6TL",
      "9QHMW",
      "GKJX3"
    ],
    "dog1-data-fives": "GAQ7O",
    "dog2-data-fives": [
      "J5GHM",
      "HWZH0",
      "LESYJ",
      "VMXSF",
      "CEZHB",
      "KC9UL",
      "TQ87J",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Sustained Stamina & Brain Health",
    "dogs-nutritional-focus-description2": "Tracking dogs benefit from balanced, high-energy foods with Upgraded Vitamins and Probiotics, supporting mental acuity and long-term stamina.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "K9 Dogs",
    "Slug": "top-dry-dog-food-for-k9-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89b89b3b2b8d9c52fcd",
    "canonical": "top-dry-dog-food-for-k9-dogs",
    "recordId": "recnETN4kHNiy6PgF",
    "recordType": "gp",
    "recordStatus": "",
    "calcSlug": "k9-dogs",
    "dogName": "",
    "data-five": "Y6PGF",
    "data-sort": 42,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Police and security dogs trained for demanding jobs. High-protein, balanced nutrition powers their strength, focus, and quick recovery on the job.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "KEB4Z",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP",
      "YD8CG",
      "XORST",
      "J76F7",
      "XUUYO",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "UQ30T",
      "MRSTT",
      "YRWGG",
      "ABJVI",
      "81XCU",
      "5ELBD",
      "XGD4Z",
      "EK1NU",
      "IIDS9",
      "ZAPVO",
      "UDMZM",
      "PN28C"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "SKYQA",
      "9QHMW",
      "GKJX3"
    ],
    "dog1-data-fives": "Y6PGF",
    "dog2-data-fives": [
      "J5GHM",
      "VMXSF",
      "HWZH0",
      "KC9UL",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Peak Performance and Mental Clarity",
    "dogs-nutritional-focus-description2": "Need premium, highly digestible diets for top mental and physical performance under stress.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Police Dogs",
    "Slug": "dog-food-formulated-for-police-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89b996ac5820623d3ac",
    "canonical": "dog-food-formulated-for-police-dogs",
    "recordId": "rec10l5mJWcjCSiRP",
    "recordType": "jb",
    "recordStatus": "",
    "calcSlug": "police-dogs",
    "dogName": "",
    "data-five": "CSIRP",
    "data-sort": 9,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Chase, apprehend, and protect on the job. Power, speed, and sharp senses depend on high-quality nutrition—protein, healthy fats, and antioxidants for maximum performance and quick recovery.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0",
      "J76F7",
      "JEBP3",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C",
      "JTSRY",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "VYSPN",
      "KJCYZ",
      "GKJX3"
    ],
    "dog1-data-fives": "CSIRP",
    "dog2-data-fives": [
      "J5GHM",
      "VMXSF",
      "HWZH0",
      "CEZHB",
      "KC9UL",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Stamina & Cognitive Support",
    "dogs-nutritional-focus-description2": "Police dogs perform best on calorie-dense diets with Performance Minerals and Probiotics for sustained stamina and mental sharpness through stressful work.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Protection  Dogs",
    "Slug": "dog-food-formulated-for-protection-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89b1731afb6415968df",
    "canonical": "dog-food-formulated-for-protection-dogs",
    "recordId": "rec2xB4TyEoHmnLtS",
    "recordType": "jb",
    "recordStatus": "",
    "calcSlug": "protection-dogs",
    "dogName": "",
    "data-five": "MNLTS",
    "data-sort": 28,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Trained to guard families, property, or livestock. Food with quality protein, fats, and joint-supporting nutrients helps maintain their strength, drive, and readiness.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0",
      "YD8CG",
      "XORST",
      "J76F7",
      "XUUYO",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "UQ30T",
      "MRSTT",
      "YRWGG",
      "ABJVI",
      "81XCU",
      "5ELBD",
      "XGD4Z",
      "EK1NU",
      "IIDS9",
      "ZAPVO",
      "UDMZM",
      "PN28C",
      "NVUQ6",
      "L5O6A",
      "OWC0W",
      "XV780",
      "AGJPT"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "VYSPN",
      "9QHMW",
      "VFKR6"
    ],
    "dog1-data-fives": "MNLTS",
    "dog2-data-fives": [
      "J5GHM",
      "CEZHB",
      "KC9UL",
      "VMXSF",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Muscle Support & Immunity",
    "dogs-nutritional-focus-description2": "Protection dogs need calorie-dense, high-protein food for muscle strength and resilience. Upgraded Vitamins and Antioxidants support stress resistance and immune health.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Detection  Dogs",
    "Slug": "dog-food-formulated-for-detection-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d8993437ae7364aef917",
    "canonical": "dog-food-formulated-for-detection-dogs",
    "recordId": "reczcJCzXxx4utHHc",
    "recordType": "jb",
    "recordStatus": "",
    "calcSlug": "detection-dogs",
    "dogName": "",
    "data-five": "UTHHC",
    "data-sort": 38,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Work tirelessly using their nose to detect scents—explosives, drugs, or even bed bugs. They need high-protein, high-energy food to fuel focus, endurance, and alertness through long shifts.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP",
      "YD8CG",
      "XORST",
      "J76F7",
      "XUUYO",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "MRSTT",
      "YRWGG",
      "ABJVI",
      "81XCU",
      "5ELBD",
      "XGD4Z",
      "EK1NU",
      "ZAPVO",
      "PN28C"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "MXQV1",
      "SKYQA",
      "9QHMW",
      "GKJX3"
    ],
    "dog1-data-fives": "UTHHC",
    "dog2-data-fives": [
      "J5GHM",
      "9CDZC",
      "VMXSF",
      "HWZH0",
      "TQ87J",
      "CEZHB",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Focus & Endurance",
    "dogs-nutritional-focus-description2": "Detection dogs need balanced, highly digestible nutrition to fuel long hours of scent work. Probiotics and Upgraded Vitamins help support sharp focus and resilience on the job.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Livestock Guardian Dogs",
    "Slug": "dog-food-formulated-for-livestock-guardian-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89b50769739cacd9b13",
    "canonical": "dog-food-formulated-for-livestock-guardian-dogs",
    "recordId": "recuXsoWKKuyOp4ry",
    "recordType": "jb",
    "recordStatus": "",
    "calcSlug": "livestock-guardian-dogs",
    "dogName": "",
    "data-five": "OP4RY",
    "data-sort": 30,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Protect herds and flocks around the clock, often in tough conditions. Foods rich in energy and immune-supporting nutrients help them stay healthy, resilient, and alert on duty.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP",
      "C6HRL",
      "H0NSG",
      "OWC0W"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "MXQV1",
      "SKYQA",
      "1UH7O",
      "GKJX3",
      "MBUVJ"
    ],
    "dog1-data-fives": "OP4RY",
    "dog2-data-fives": [
      "J5GHM",
      "9CDZC",
      "VMXSF",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Immune Support & Endurance",
    "dogs-nutritional-focus-description2": "Guardian breeds thrive on balanced, highly digestible diets to keep them alert and healthy over long shifts. Probiotics and Allergy Relief ingredients can help support sensitive stomachs.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Agility",
    "Slug": "best-dry-dog-food-for-agility",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d899ff7ade4b3d2c4eb1",
    "canonical": "best-dry-dog-food-for-agility",
    "recordId": "rec5d0WxgKi3KCdkk",
    "recordType": "ac",
    "recordStatus": "",
    "calcSlug": "agility",
    "dogName": "",
    "data-five": "KCDKK",
    "data-sort": 22,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Fast-paced obstacle course competition requiring speed, focus, and high energy. Dogs need balanced, calorie-dense food to fuel quick sprints and rapid recovery.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0",
      "JTSRY",
      "U9EU7",
      "QFRJN",
      "HFCYR",
      "RUAPK",
      "KEB4Z",
      "4CQVY",
      "5E1NB",
      "YLNYF",
      "UQHTP",
      "UQ30T",
      "IIDS9",
      "UDMZM",
      "J76F7",
      "JEBP3",
      "MRSTT",
      "XV780",
      "PN28C"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "VYSPN",
      "SKYQA",
      "MXQV1",
      "KJCYZ",
      "GKJX3"
    ],
    "dog1-data-fives": "KCDKK",
    "dog2-data-fives": [
      "J5GHM",
      "9CDZC",
      "VMXSF",
      "CEZHB",
      "TQ87J",
      "HWZH0",
      "KC9UL",
      "LESYJ",
      "UT6SQ",
      "GVJDB"
    ],
    "common_misspellings": "German Shepard, German Sheperd",
    "other_common_names": "Alsatian",
    "common_initials": "GSD",
    "common_nickname": "Shep, German, Alsatian",
    "dogs-nutritional-focus-title": "High-Energy & Joint Support",
    "dogs-nutritional-focus-description2": "Agility dogs need a calorie-dense diet with highly digestible ingredients and healthy fats for fast energy. Balanced Nutrition, Performance Minerals, and added Probiotics help support stamina, joint health, and rapid recovery after intense runs.",
    "height_range": "",
    "weight_range": "50 - 90 lbs",
    "feeding_range": "1.49 - 2.31 cups",
    "max_weight": 90,
    "min_weight": 50,
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Working Dogs",
    "Slug": "popular-dog-food-for-working-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89c29112ce38cbbece8",
    "canonical": "popular-dog-food-for-working-dogs",
    "recordId": "recnTkqmTMdVb5jOi",
    "recordType": "gp",
    "recordStatus": "",
    "calcSlug": "working-dogs",
    "dogName": "",
    "data-five": "B5JOI",
    "data-sort": 7,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "All-around workers from search and rescue to service jobs. They need balanced, reliable nutrition to keep their bodies strong and their minds sharp day after day.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0",
      "J76F7",
      "JEBP3",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C",
      "YD8CG",
      "XORST",
      "XUUYO",
      "SQ0XJ",
      "MBFOA",
      "YRWGG",
      "ABJVI",
      "81XCU",
      "5ELBD",
      "XGD4Z",
      "EK1NU",
      "IIDS9",
      "ZAPVO",
      "UDMZM"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "VYSPN",
      "KJCYZ",
      "9QHMW"
    ],
    "dog1-data-fives": "B5JOI",
    "dog2-data-fives": [
      "J5GHM",
      "9CDZC",
      "CEZHB",
      "VMXSF",
      "HWZH0",
      "KC9UL",
      "GVJDB"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Reliable Energy and Immune Support",
    "dogs-nutritional-focus-description2": "Require nutrient-rich diets with extra calories and minerals to support endurance, muscle health, and immune function for daily working routines.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Active Dogs",
    "Slug": "top-dry-dog-food-for-active-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d899d7dfaed5620fb616",
    "canonical": "top-dry-dog-food-for-active-dogs",
    "recordId": "recPSMtNebGqOSXWL",
    "recordType": "gp",
    "recordStatus": "",
    "calcSlug": "active-dogs",
    "dogName": "",
    "data-five": "OSXWL",
    "data-sort": 31,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Energetic dogs that love to run, play, and work hard every day. They thrive on calorie-dense, high-protein food that keeps up with their nonstop lifestyle.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0",
      "UQ30T",
      "KEB4Z",
      "IIDS9",
      "UDMZM",
      "SQ0XJ",
      "MBFOA",
      "JEBP3",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO"
    ],
    "si-data-fives": [
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29099",
      "28979"
    ],
    "va-data-fives": [
      "VYSPN",
      "MXQV1",
      "NG6TL"
    ],
    "dog1-data-fives": "OSXWL",
    "dog2-data-fives": [
      "J5GHM",
      "9CDZC",
      "CEZHB",
      "VMXSF",
      "TQ87J",
      "HWZH0",
      "KC9UL",
      "LESYJ",
      "GVJDB",
      "N6M4B",
      "EA62U"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Sustained Energy for Active Lifestyles",
    "dogs-nutritional-focus-description2": "Require calorie-dense, balanced diets for stamina and endurance through rigorous activity.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  },
  {
    "Name": "Performance Dogs",
    "Slug": "top-dry-dog-food-for-performance-dogs",
    "Collection ID": "647ddb9037101ce399b33148",
    "Item ID": "6852d89b55a6dd9f1e269078",
    "canonical": "top-dry-dog-food-for-performance-dogs",
    "recordId": "recbOzufm3T2mm5SK",
    "recordType": "gp",
    "recordStatus": "",
    "calcSlug": "performance-dogs",
    "dogName": "",
    "data-five": "MM5SK",
    "data-sort": 27,
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "Compete in sports and events, from agility to dock diving. They need precise nutrition for muscle recovery, joint health, and maximum energy output.",
    "data-faqType": "dog",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0",
      "J76F7",
      "JEBP3",
      "UQ30T",
      "MRSTT",
      "XV780",
      "PN28C",
      "SQ0XJ",
      "MBFOA",
      "YRWGG",
      "H0NSG",
      "ABJVI",
      "81XCU",
      "5E1NB",
      "5ELBD",
      "ZAPVO"
    ],
    "si-data-fives": [
      "29280",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "28979"
    ],
    "va-data-fives": [
      "VYSPN",
      "KJCYZ",
      "NG6TL"
    ],
    "dog1-data-fives": "MM5SK",
    "dog2-data-fives": [
      "J5GHM",
      "9CDZC",
      "CEZHB",
      "VMXSF",
      "UT6SQ",
      "TQ87J",
      "HWZH0",
      "KC9UL",
      "LESYJ",
      "GVJDB",
      "N6M4B",
      "EA62U"
    ],
    "common_misspellings": "",
    "other_common_names": "",
    "common_initials": "",
    "common_nickname": "",
    "dogs-nutritional-focus-title": "Elite Athlete Nutrition",
    "dogs-nutritional-focus-description2": "Require specialized, performance-driven formulas for power, stamina, and rapid recovery.",
    "height_range": "",
    "weight_range": "",
    "feeding_range": "",
    "max_weight": "",
    "min_weight": "",
    "life_span": "",
    "color_coat": "",
    "activity_level": ""
  }
]
