export const gaFocus = [
  {
    "Item ID": "647ddb9037101ce399b34500",
    "Slug": "cub-puppy",
    "Name": "Cub Puppy",
    "faqType": "cub",
    "ga_crude_protein": 30,
    "ga_crude_fat": 20,
    "ga_crude_fiber": 3.3,
    "ga_moisture": 8,
    "ga_kcals_per_kg": 3847.7,
    "ga_kcals_per_cup": 526,
    "ga_omega_6_fatty_acids": 3.39,
    "ga_omega_3_fatty_acids": 0.46,
    "ga_animal_protein": 86,
    "calc_cups_per_bag": 40,
    "specs_price_per_bag": 98,
    "based_grams-per-cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "aafco-short": "For all life stages",
    "manual_faq_enabled": false
  },
  {
    "Item ID": "647ddb9037101ce399b34501",
    "Slug": "dock-dog",
    "Name": "Dock Dog",
    "faqType": "dock",
    "ga_crude_protein": 30,
    "ga_crude_fat": 15,
    "ga_crude_fiber": 3.3,
    "ga_moisture": 8,
    "ga_kcals_per_kg": 3579.35,
    "ga_kcals_per_cup": 460,
    "ga_omega_6_fatty_acids": 3.36,
    "ga_omega_3_fatty_acids": 0.39,
    "ga_animal_protein": 85,
    "calc_cups_per_bag": 37,
    "specs_price_per_bag": 98,
    "based_grams-per-cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "aafco-short": "For all life stages",
    "manual_faq_enabled": false
  },
  {
    "Item ID": "647ddb9037101ce399b344fb",
    "Slug": "herding-dog",
    "Name": "Herding Dog",
    "faqType": "herding",
    "ga_crude_protein": 30,
    "ga_crude_fat": 15,
    "ga_crude_fiber": 3.4,
    "ga_moisture": 8,
    "ga_kcals_per_kg": 3603.0,
    "ga_kcals_per_cup": 460,
    "ga_omega_6_fatty_acids": 1.42,
    "ga_omega_3_fatty_acids": 0.4,
    "ga_animal_protein": 89,
    "calc_cups_per_bag": 37,
    "specs_price_per_bag": 98,
    "based_grams-per-cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "aafco-short": "For all life stages",
    "manual_faq_enabled": false
  }
];
