
[
  {
    "Name": "Cub Puppy",
    "Slug": "cub-puppy",
    "Collection ID": "647ddb9037101ce399b331bb",
    "Item ID": "647ddb9037101ce399b34500",
    "canonical": "cub-puppy-poultry-free-dog-food-analysis",
    "recordId": "reclUqppjWPAEzGDY",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "cub-puppy",
    "itemId": "29280",
    "item-subtitle": "Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "item-status": "",
    "itemName": "Cub Puppy Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "data-five": "29280",
    "data-sort": 1,
    "data-one": "Cub",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zohoexternal.com/image/WD/euwhm685fd378c91d4139913bebff1c172e1b?version=1.0&width=600",
    "previewAlttag": "Cub Dog Food Bag",
    "cf_description": "",
    "data-faqType": "sf",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "Cub Puppy",
    "sd-data-fives": [
      "YOIPL",
      "DNXWW",
      "71Q6Z"
    ],
    "ing-data-fives": [
      "C6HRL",
      "KEB4Z",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-five": "29280",
    "va-data-fives": [
      "NG6TL",
      "VYSPN",
      "1UH7O",
      "M3BBO",
      "F9VGP",
      "MZQRJ",
      "PSAC9",
      "0PA9E",
      "DUKQO",
      "80FEX",
      "CPQ7X",
      "5T46P",
      "63DFT",
      "VELOJ",
      "RD1V9",
      "0CSHM",
      "KLFNM",
      "D1SQF",
      "JV9J9",
      "SKYQA",
      "MXQV1",
      "MBUVJ",
      "HP3UR",
      "EZB40",
      "JZ8D8",
      "TQRAE",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "GKJX3",
      "ZIFVT",
      "F2O7T"
    ],
    "dog-data-fives": [
      "J5GHM",
      "9CDZC",
      "CEZHB",
      "VMXSF",
      "HWZH0",
      "KC9UL"
    ],
    "Product ID": "084282929280",
    "specs_in_stock": "",
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3847.7,
    "ga_kcals_per_cup": 526,
    "calc_price_per_lb": 3.26,
    "calc_cups_per_day": 2.5,
    "calc_cups_in_bag": 99,
    "calc_days_in_bag": 40,
    "calc_cost_per_day": 2.43,
    "calc_cost_per_cup": 0.99,
    "based_on_grams_per_cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "dynamic_weight_input": "",
    "conditional_results_days_per_bag": 1,
    "conditional_results_cost_per_day": 2,
    "conditional_results_cups_per_day": 3,
    "conditional_sport_herding_selected": 460,
    "conditional_sport_cub_selected": 526,
    "conditional_sport_dock_selected": 460,
    "conditional_thisFood_selected": 526,
    "conditional_activity_selected": "active",
    "conditional_life_selected": "adult",
    "based_on_typical": 1300,
    "based_on_active": 1492,
    "based_on_working": 2088,
    "based_on_highlyactive": 1799,
    "based_on_heavy_duty": 2984,
    "ga_carbs_%": 34,
    "ga_omega_6_fatty_acids_%": 3.39,
    "ga_omega_3_fatty_acids_%": 0.46,
    "ga_animal_protein_%": 86,
    "ga_ash_%": 8,
    "ga_calcium_%": 1.2,
    "ga_phosphorous_%": 0.9,
    "ga_vitamin_d3_ui_per_kg": 726,
    "ga_vitamin_e_ui_per_kg": 143,
    "ga_vitamin_b12_ui_per_kg": 0,
    "calc_cal_phos_ratio": 1.4,
    "calc_display_cal_phos_ratio": "2001-01-01T03:01:00.000Z",
    "aafco-options": "Formulated to meet the nutritional levels established by the AAFCO Dog Food Nutrient Profiles for All Life Stages including puppies and pregnant or lactating female dogs.",
    "aafco-short": "For all life stages"
  },
  {
    "Name": "Dock Dog",
    "Slug": "dock-dog",
    "Collection ID": "647ddb9037101ce399b331bb",
    "Item ID": "647ddb9037101ce399b34501",
    "canonical": "dock-dog-poultry-free-dog-food-analysis",
    "recordId": "recYfCuMd4nkKSWYO",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "dock-dog",
    "itemId": "29099",
    "item-subtitle": "Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "item-status": "",
    "itemName": "Dock Dog Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "data-five": "29099",
    "data-sort": 2,
    "data-one": "Dock",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zohoexternal.com/image/WD/euwhmbb227f31208a4a0cbbcbf498723b3ab8?version=1.0&width=600",
    "previewAlttag": "Dock Dog Food Bag",
    "cf_description": "",
    "data-faqType": "sf",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "Dock Dog",
    "sd-data-fives": [
      "YOIPL",
      "DNXWW",
      "71Q6Z"
    ],
    "ing-data-fives": [
      "C6HRL",
      "KEB4Z",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-five": "29099",
    "va-data-fives": [
      "NG6TL",
      "VYSPN",
      "1UH7O",
      "M3BBO",
      "F9VGP",
      "MZQRJ",
      "PSAC9",
      "0PA9E",
      "DUKQO",
      "80FEX",
      "CPQ7X",
      "5T46P",
      "63DFT",
      "VELOJ",
      "RD1V9",
      "0CSHM",
      "KLFNM",
      "D1SQF",
      "JV9J9",
      "SKYQA",
      "MXQV1",
      "MBUVJ",
      "HP3UR",
      "EZB40",
      "JZ8D8",
      "TQRAE",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "GKJX3",
      "ZIFVT",
      "F2O7T"
    ],
    "dog-data-fives": [
      "LESYJ",
      "UT6SQ",
      "TQ87J",
      "N6M4B"
    ],
    "Product ID": "084282929099",
    "specs_in_stock": "",
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3579.35,
    "ga_kcals_per_cup": 460,
    "calc_price_per_lb": 3.26,
    "calc_cups_per_day": 2.8,
    "calc_cups_in_bag": 105,
    "calc_days_in_bag": 37,
    "calc_cost_per_day": 2.62,
    "calc_cost_per_cup": 0.93,
    "based_on_grams_per_cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "dynamic_weight_input": "",
    "conditional_results_days_per_bag": 1,
    "conditional_results_cost_per_day": 2,
    "conditional_results_cups_per_day": 3,
    "conditional_sport_herding_selected": 460,
    "conditional_sport_cub_selected": 526,
    "conditional_sport_dock_selected": 460,
    "conditional_thisFood_selected": 460,
    "conditional_activity_selected": "active",
    "conditional_life_selected": "adult",
    "based_on_typical": 1300,
    "based_on_active": 1492,
    "based_on_working": 2088,
    "based_on_highlyactive": 1799,
    "based_on_heavy_duty": 2984,
    "ga_carbs_%": 38,
    "ga_omega_6_fatty_acids_%": 3.36,
    "ga_omega_3_fatty_acids_%": 0.39,
    "ga_animal_protein_%": 85,
    "ga_ash_%": 8,
    "ga_calcium_%": 1.2,
    "ga_phosphorous_%": 0.9,
    "ga_vitamin_d3_ui_per_kg": 681,
    "ga_vitamin_e_ui_per_kg": 134,
    "ga_vitamin_b12_ui_per_kg": 0,
    "calc_cal_phos_ratio": 1.4,
    "calc_display_cal_phos_ratio": "2001-01-01T03:01:00.000Z",
    "aafco-options": "Formulated to meet the nutritional levels established by the AAFCO Dog Food Nutrient Profiles for All Life Stages, including growth of large size dogs (70 lb. or more as an adult).",
    "aafco-short": "For all life stages"
  },
  {
    "Name": "Herding Dog",
    "Slug": "herding-dog",
    "Collection ID": "647ddb9037101ce399b331bb",
    "Item ID": "647ddb9037101ce399b344fb",
    "canonical": "herding-dog-poultry-free-dog-food-analysis",
    "recordId": "recL4C3ECWQNbFehc",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "herding-dog",
    "itemId": "28979",
    "item-subtitle": "Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "item-status": "",
    "itemName": "Herding Dog Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "data-five": "28979",
    "data-sort": 3,
    "data-one": "Herding",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain Free",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zohoexternal.com/image/WD/euwhmdeacbcb8a82749ec875ec39e54e2492b?version=1.0&width=600",
    "previewAlttag": "Herding Dog Food Bag",
    "cf_description": "",
    "data-faqType": "sf",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "Herding Dog",
    "sd-data-fives": [
      "3A9NE",
      "DNXWW",
      "71Q6Z"
    ],
    "ing-data-fives": [
      "C6HRL",
      "K5VFA",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-five": "28979",
    "va-data-fives": [
      "NG6TL",
      "VYSPN",
      "1UH7O",
      "M3BBO",
      "F9VGP",
      "MZQRJ",
      "PSAC9",
      "0PA9E",
      "DUKQO",
      "80FEX",
      "CPQ7X",
      "5T46P",
      "63DFT",
      "VELOJ",
      "RD1V9",
      "0CSHM",
      "KLFNM",
      "D1SQF",
      "JV9J9",
      "SKYQA",
      "MBUVJ",
      "HP3UR",
      "EZB40",
      "JZ8D8",
      "TQRAE",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "MXQV1",
      "GKJX3",
      "ZIFVT",
      "F2O7T"
    ],
    "dog-data-fives": [
      "J5GHM",
      "9CDZC",
      "CEZHB",
      "VMXSF",
      "KCDKK",
      "HWZH0",
      "KC9UL",
      "LESYJ",
      "UT6SQ",
      "TQ87J",
      "N6M4B"
    ],
    "Product ID": "084282928979",
    "specs_in_stock": "",
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.4,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3603,
    "ga_kcals_per_cup": 460,
    "calc_price_per_lb": 3.26,
    "calc_cups_per_day": 2.8,
    "calc_cups_in_bag": 107,
    "calc_days_in_bag": 37,
    "calc_cost_per_day": 2.6,
    "calc_cost_per_cup": 0.92,
    "based_on_grams_per_cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "dynamic_weight_input": "",
    "conditional_results_days_per_bag": 1,
    "conditional_results_cost_per_day": 2,
    "conditional_results_cups_per_day": 3,
    "conditional_sport_herding_selected": 460,
    "conditional_sport_cub_selected": 526,
    "conditional_sport_dock_selected": 460,
    "conditional_thisFood_selected": 460,
    "conditional_activity_selected": "active",
    "conditional_life_selected": "adult",
    "based_on_typical": 1300,
    "based_on_active": 1492,
    "based_on_working": 2088,
    "based_on_highlyactive": 1799,
    "based_on_heavy_duty": 2984,
    "ga_carbs_%": 39,
    "ga_omega_6_fatty_acids_%": 1.42,
    "ga_omega_3_fatty_acids_%": 0.4,
    "ga_animal_protein_%": 89,
    "ga_ash_%": 8,
    "ga_calcium_%": 1.2,
    "ga_phosphorous_%": 0.9,
    "ga_vitamin_d3_ui_per_kg": 681,
    "ga_vitamin_e_ui_per_kg": 132,
    "ga_vitamin_b12_ui_per_kg": 0,
    "calc_cal_phos_ratio": 1.4,
    "calc_display_cal_phos_ratio": "2001-01-01T04:01:00.000Z",
    "aafco-options": "Formulated to meet the nutritional levels established by the AAFCO Dog Food Nutrient Profiles for All Life Stages, including growth of large size dogs (70 lb. or more as an adult).",
    "aafco-short": "For all life stages"
  }
]
