[
  {
    "Name": "Cub Puppy",
    "Slug": "cub-puppy",
    "Collection ID": "647ddb9037101ce399b331bb",
    "Item ID": "647ddb9037101ce399b34500",
    "canonical": "cub-puppy-poultry-free-dog-food-analysis",
    "recordId": "reclUqppjWPAEzGDY",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "cub-puppy",
    "itemId": "29280",
    "item-subtitle": "Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "item-status": "",
    "itemName": "Cub Puppy Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "data-five": "29280",
    "data-sort": 1,
    "data-one": "Cub",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zohoexternal.com/image/WD/euwhm685fd378c91d4139913bebff1c172e1b?version=1.0&width=600",
    "previewAlttag": "Cub Dog Food Bag",
    "data-faqType": "sf",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "cf_description": "",
    "br-data-five": "1000",
    "img-data-five": "Cub Puppy",
    "si-data-five": "29280",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_kcals_per_kg": 3847.7,
    "ga_kcals_per_cup": 526,
    "calc_price_per_lb": 3.26,
    "calc_cups_per_day": 2.5,
    "calc_cups_in_bag": 99,
    "calc_days_in_bag": 40,
    "calc_cost_per_day": 2.43,
    "calc_cost_per_cup": 0.99,
    "based_on_grams_per_cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "dynamic_weight_input": "",
    "conditional_results_days_per_bag": 1,
    "conditional_results_cost_per_day": 2,
    "conditional_results_cups_per_day": 3,
    "conditional_sport_herding_selected": 460,
    "conditional_sport_cub_selected": 526,
    "conditional_sport_dock_selected": 460,
    "conditional_thisFood_selected": 526,
    "conditional_activity_selected": "active",
    "conditional_life_selected": "adult",
    "based_on_typical": 1300,
    "based_on_active": 1492,
    "based_on_working": 2088,
    "based_on_highlyactive": 1799,
    "based_on_heavy_duty": 2984
  },
  {
    "Name": "Dock Dog",
    "Slug": "dock-dog",
    "Collection ID": "647ddb9037101ce399b331bb",
    "Item ID": "647ddb9037101ce399b34501",
    "canonical": "dock-dog-poultry-free-dog-food-analysis",
    "recordId": "recYfCuMd4nkKSWYO",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "dock-dog",
    "itemId": "29099",
    "item-subtitle": "Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "item-status": "",
    "itemName": "Dock Dog Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "data-five": "29099",
    "data-sort": 2,
    "data-one": "Dock",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zohoexternal.com/image/WD/euwhmbb227f31208a4a0cbbcbf498723b3ab8?version=1.0&width=600",
    "previewAlttag": "Dock Dog Food Bag",
    "data-faqType": "sf",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "cf_description": "",
    "br-data-five": "1000",
    "img-data-five": "Dock Dog",
    "si-data-five": "29099",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_kcals_per_kg": 3579.35,
    "ga_kcals_per_cup": 460,
    "calc_price_per_lb": 3.26,
    "calc_cups_per_day": 2.8,
    "calc_cups_in_bag": 105,
    "calc_days_in_bag": 37,
    "calc_cost_per_day": 2.62,
    "calc_cost_per_cup": 0.93,
    "based_on_grams_per_cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "dynamic_weight_input": "",
    "conditional_results_days_per_bag": 1,
    "conditional_results_cost_per_day": 2,
    "conditional_results_cups_per_day": 3,
    "conditional_sport_herding_selected": 460,
    "conditional_sport_cub_selected": 526,
    "conditional_sport_dock_selected": 460,
    "conditional_thisFood_selected": 460,
    "conditional_activity_selected": "active",
    "conditional_life_selected": "adult",
    "based_on_typical": 1300,
    "based_on_active": 1492,
    "based_on_working": 2088,
    "based_on_highlyactive": 1799,
    "based_on_heavy_duty": 2984
  },
  {
    "Name": "Herding Dog",
    "Slug": "herding-dog",
    "Collection ID": "647ddb9037101ce399b331bb",
    "Item ID": "647ddb9037101ce399b344fb",
    "canonical": "herding-dog-poultry-free-dog-food-analysis",
    "recordId": "recL4C3ECWQNbFehc",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "herding-dog",
    "itemId": "28979",
    "item-subtitle": "Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "item-status": "",
    "itemName": "Herding Dog Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "data-five": "28979",
    "data-sort": 3,
    "data-one": "Herding",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain Free",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zohoexternal.com/image/WD/euwhmdeacbcb8a82749ec875ec39e54e2492b?version=1.0&width=600",
    "previewAlttag": "Herding Dog Food Bag",
    "data-faqType": "sf",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "cf_description": "",
    "br-data-five": "1000",
    "img-data-five": "Herding Dog",
    "si-data-five": "28979",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_kcals_per_kg": 3603,
    "ga_kcals_per_cup": 460,
    "calc_price_per_lb": 3.26,
    "calc_cups_per_day": 2.8,
    "calc_cups_in_bag": 107,
    "calc_days_in_bag": 37,
    "calc_cost_per_day": 2.6,
    "calc_cost_per_cup": 0.92,
    "based_on_grams_per_cup": 105.6,
    "based_on_1300_kcal_daily": 1300,
    "based_on_active_60_dog": 60,
    "dynamic_weight_input": "",
    "conditional_results_days_per_bag": 1,
    "conditional_results_cost_per_day": 2,
    "conditional_results_cups_per_day": 3,
    "conditional_sport_herding_selected": 460,
    "conditional_sport_cub_selected": 526,
    "conditional_sport_dock_selected": 460,
    "conditional_thisFood_selected": 460,
    "conditional_activity_selected": "active",
    "conditional_life_selected": "adult",
    "based_on_typical": 1300,
    "based_on_active": 1492,
    "based_on_working": 2088,
    "based_on_highlyactive": 1799,
    "based_on_heavy_duty": 2984
  }
]
