export const SI_DATA =

 [
  {
    "Name": "Cub Puppy",
    "Slug": "premium-cub-puppy-peas-free-dog-food",
    "Collection ID": "647ddb9037101ce399b33184",
    "Item ID": "647ddb9037101ce399b344e8",
    "canonical": "premium-cub-puppy-peas-free-dog-food",
    "recordId": "recZ0C3ZTWsZk37zW",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "cub-puppy",
    "itemId": 29280,
    "item-subtitle": "Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "item-status": "",
    "itemName": "Cub Puppy Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "data-legumes": "Legumes Free",
    "data-poultry": "Poultry Free",
    "data-grain": "",
    "data-five": "29280",
    "data-sort": 1,
    "data-one": "Cub",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": [
      "https://previewengine-accl.zoho.com/image/WD/iph9xb6de6ad0806e49c182dbf11c72cb5bb2?version=1.0&width=2046&height=1536",
      "nosrc"
    ],
    "previewAlttag": "Cub Dog Food Bag",
    "cf_description": "",
    "data-faqType": "si",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "Cub Puppy",
    "sd-data-fives": [
      "YOIPL",
      "DNXWW",
      "71Q6Z"
    ],
    "dogBr-fives": [
      "NTOHN",
      "2ZREE",
      "VJYZS",
      "4TIL1",
      "IPVOO"
    ],
    "dogKeys_ac": "Tracking, Agility, Dock Diving",
    "dogKeys_gp": "K9 Dogs, Working Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs",
    "dogKeys_jb": "Patrol, Protection, Detection",
    "ing-data-fives": [
      "C6HRL",
      "KEB4Z",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "not-data-fives": [
      "XE8IL",
      "K5VFA",
      "7YYYV",
      "PJZGH",
      "WOT9J",
      "VQ8Y7",
      "BS8EA",
      "ZOEIR",
      "YHSJR",
      "G9HW5",
      "XAGFV",
      "SR2TH",
      "VM56I",
      "UEJQ0",
      "CBJVQ",
      "4RIOW",
      "TDPRO",
      "FIVTY",
      "HJJWJ",
      "2HFZQ",
      "QY3IX",
      "ZAEEW",
      "QJO9S",
      "4GGMJ",
      "ES2BJ",
      "ZYKY5",
      "6GX4D",
      "YJSLD",
      "PSCOG",
      "RPNUO",
      "DONFW",
      "EQ1IW",
      "FLMRA",
      "GZJHS",
      "ARHPV",
      "PUVNB",
      "CQCMT",
      "GSJWC",
      "BSARH",
      "RR0IK",
      "1VEVT",
      "VF4WM",
      "QJDEF",
      "ZX5FX",
      "UHTXD",
      "K8DK5",
      "T6W2R",
      "993B1",
      "2NZMY",
      "RUMCD",
      "RH9L7",
      "U3RU8",
      "CBOFC",
      "LNDRX",
      "JECBD",
      "GL5KA",
      "E9MIY",
      "RTYGD",
      "7H3VG",
      "KZC6H",
      "AWE1M",
      "CDODO",
      "SCYOC",
      "UIC8H",
      "7TSVX",
      "MICCW",
      "XROAQ",
      "5Q7AU",
      "CQSJS",
      "RI3OR",
      "TNJ5K",
      "WG5DM",
      "92UMI",
      "WJEHA",
      "E5GD0",
      "IULX1",
      "GAMG6",
      "OEXO1",
      "IQEVA",
      "XMHNC",
      "OEKKH",
      "IQCTZ",
      "CEVBH",
      "GTA4T",
      "SS0IU",
      "GVE6I",
      "XQLSB",
      "9WQMN",
      "KE2JS",
      "5XOBR",
      "WJG4W",
      "WWJWN",
      "N3IGS",
      "JRLXE",
      "CIPVY",
      "DKVU1",
      "4BJJX",
      "K3WTW",
      "555IX",
      "OAYON",
      "OK30H",
      "NLWI3",
      "GMKSI",
      "CSYLS",
      "6XYWL",
      "UTGPV",
      "IQK4Z",
      "SIPQU",
      "CKYLP",
      "H8HEP",
      "WSBE2",
      "DH0D2",
      "8KBDY",
      "Z1DXF",
      "XC0BR",
      "8ALHU",
      "CAIRD",
      "RSKUH",
      "XLF7R",
      "MDZEZ",
      "P2NVN",
      "VT96P",
      "VEYMA",
      "2LCAZ",
      "EJMRL",
      "ZTWXV",
      "4GUVA",
      "U6HWJ",
      "UQT4S",
      "JVSIW",
      "GVKK6",
      "DLHTR",
      "RANER",
      "FSMSV",
      "IPPTH",
      "V43XM",
      "EXOJP",
      "N7TQB",
      "K4SWZ",
      "Z16PM",
      "NCLGW",
      "UNEJR",
      "GUYLG",
      "HT5ZK",
      "Z7Z8A",
      "BCPGM",
      "GHQD5",
      "QT1FJ",
      "90DOH",
      "PJ2YC",
      "ECLSM",
      "CWRAH",
      "X5FFT",
      "DL4MS",
      "1THAG",
      "KZYKM",
      "QISOK",
      "COFRG",
      "AG2D0",
      "7SZIB",
      "C2TWM",
      "B9RZP",
      "HW3FD",
      "MFUQY",
      "CTQW9",
      "JLM8P",
      "DJLBW",
      "AN02K",
      "JZHRB",
      "TRFPO",
      "6LJTN",
      "VDCDU",
      "BWNCE",
      "NRX8Q",
      "LDMXN",
      "QGLWJ",
      "LILLF",
      "ZI96X",
      "7CKMM",
      "HQCHY",
      "MEEDO",
      "YXPAM",
      "LQRGM",
      "K0VR7",
      "SASQ6",
      "2BQ0H",
      "VJD3I",
      "DO7ZH",
      "K4IZA",
      "QUDFT",
      "NVIZZ",
      "TGSYE",
      "Z384X",
      "ORXDE",
      "7JYFL",
      "759SV",
      "OWEO0",
      "4T3AI",
      "Y70QF",
      "PFLZ3",
      "G62TE",
      "DZYA6",
      "FU4BY",
      "PZN5Y",
      "FVSVS",
      "G9XH8",
      "D32VQ",
      "TMVGB",
      "QPH0N",
      "Y3TAF",
      "6IAGO",
      "ZREDX",
      "LZTRD",
      "GKFYQ",
      "GMEKJ",
      "TB00X",
      "PNLKQ",
      "TSXY8",
      "XEZVD",
      "TMOP3",
      "ZUJDK",
      "FKP0A",
      "QYXQO",
      "SHJRO",
      "C6L27",
      "JPLVH",
      "FOBGF",
      "17ZQK",
      "5S0XF",
      "MVXMR",
      "COBUK",
      "REAIP",
      "PLMTN",
      "PD7TZ",
      "M1LGJ",
      "QELPS",
      "PRW8L",
      "NHHPN",
      "OF1IY",
      "8M28G",
      "RL7DV",
      "OTNQP",
      "GYPF8",
      "1B69X",
      "I1O6K",
      "THZVQ",
      "Y7ODL",
      "LHLHB",
      "ZCSMT",
      "6INDN",
      "WCSKI",
      "ELNMS",
      "IRLYG",
      "BQATH",
      "UHYTS",
      "SFO7X",
      "PSOWE",
      "XVC1B",
      "GJA6Y",
      "OQE8V",
      "AJI2E",
      "INGB4",
      "GE6GU",
      "QMALN",
      "WM4N5",
      "LVJ4H",
      "BNNWS",
      "XUG35",
      "KUOBW",
      "ZATJI",
      "G4ZMU",
      "YBH0A",
      "QLXDB",
      "17YZ3",
      "CAL2I",
      "JGAKK",
      "YU0EB",
      "0NLPZ",
      "OS8O5",
      "M0BM4",
      "MLJ43",
      "LH12E",
      "R7JU0",
      "MRZ1K",
      "36UON",
      "Y3ETC",
      "UNGGH",
      "NZA1U",
      "W0HAM",
      "PGEOT",
      "SHEJX",
      "OJBBE",
      "FEBFL",
      "9DX7S",
      "6KQTC",
      "KQB77",
      "UYDPF",
      "0ANOA",
      "74YBP",
      "CWFIK",
      "DNNWR",
      "NA2WG",
      "0UPPM",
      "PDJ3U",
      "XZBDL",
      "JJTVJ",
      "VMT2Y",
      "DLYJA",
      "IJG6H",
      "AYV0F",
      "2SX0Z",
      "OHG1C",
      "MBU30",
      "ZPGID",
      "XGGOP",
      "UCMJH",
      "SYGQB",
      "XJAAA",
      "RD1WV",
      "5KHTT",
      "FXO5C",
      "1JDZJ",
      "HDFQP",
      "9FK4M",
      "HQGYF",
      "NCE9F",
      "ZTMYL",
      "GKL4J",
      "LJBTO",
      "I1FXE",
      "MDIZK",
      "JGOFI",
      "VUYIW",
      "72Y0R",
      "TDEIO",
      "8OTUY",
      "QVQOL",
      "YPL1J",
      "FZR9B",
      "JUDBS",
      "IQTT3",
      "3HWIO",
      "GOURU",
      "MYRTC",
      "CDQCK",
      "R8PIF",
      "SZ9O3",
      "Q99OM",
      "G0IOG",
      "HWIWE",
      "WHF79",
      "B2WBK",
      "NQ4LR",
      "QHDUJ",
      "VFUPE",
      "G2YVH",
      "LNUMU",
      "BSL2E",
      "LCALN",
      "HNLVZ",
      "PG8TP",
      "OOUXY"
    ],
    "sf-data-five": "29280",
    "va-data-fives": [
      "NG6TL",
      "VYSPN",
      "1UH7O",
      "SKYQA",
      "MBUVJ",
      "TQRAE",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "GKJX3",
      "ZIFVT",
      "F2O7T",
      "VDTXI",
      "WREGA",
      "VTQGN"
    ],
    "Product ID": "084282929280",
    "specs_in_stock": "",
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3847.7000000000003,
    "ga_kcals_per_cup": 526,
    "ga_omega_6_fatty_acids_%": 3.39,
    "ga_omega_3_fatty_acids_%": 0.46,
    "ga_animal_protein_%": 86,
    "ga_ash_%": 8,
    "ga_calcium_%": 1.2,
    "ga_vitamin_d3_ui_per_kg": 726,
    "ga_vitamin_e_ui_per_kg": 143,
    "ga_vitamin_b12_ui_per_kg": 0,
    "aafco-options": "Formulated to meet the nutritional levels established by the AAFCO Dog Food Nutrient Profiles for All Life Stages including puppies and pregnant or lactating female dogs.",
    "aafco-short": "For all life stages"
  },
  {
    "Name": "Dock Dog",
    "Slug": "premium-dock-dog-peas-free-dog-food",
    "Collection ID": "647ddb9037101ce399b33184",
    "Item ID": "647ddb9037101ce399b344e3",
    "canonical": "premium-dock-dog-peas-free-dog-food",
    "recordId": "recJnPxkGb1ZUaEPI",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "dock-dog",
    "itemId": 29099,
    "item-subtitle": "Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "item-status": "",
    "itemName": "Dock Dog Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "data-legumes": "Legumes Free",
    "data-poultry": "Poultry Free",
    "data-grain": "",
    "data-five": "29099",
    "data-sort": 2,
    "data-one": "Dock",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": [
      "https://previewengine-accl.zoho.com/image/WD/iph9x174a1af7a0684e1a906476d12fd3c21d?version=1.0&width=2046&height=1536",
      "nosrc"
    ],
    "previewAlttag": "Dock Dog Food Bag",
    "cf_description": "",
    "data-faqType": "si",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "Dock Dog",
    "sd-data-fives": [
      "YOIPL",
      "DNXWW",
      "71Q6Z"
    ],
    "dogBr-fives": [
      "HGW3D",
      "ME0KB",
      "GF0GP",
      "8KTYX",
      "MLXGP",
      "UQ7MN",
      "MOVBB"
    ],
    "dogKeys_ac": "Field Trials, Tracking, Agility, Dock Diving",
    "dogKeys_gp": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs, Working Dogs",
    "dogKeys_jb": "Detection",
    "ing-data-fives": [
      "C6HRL",
      "KEB4Z",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "not-data-fives": [
      "XE8IL",
      "K5VFA",
      "7YYYV",
      "PJZGH",
      "WOT9J",
      "VQ8Y7",
      "BS8EA",
      "ZOEIR",
      "YHSJR",
      "G9HW5",
      "XAGFV",
      "SR2TH",
      "VM56I",
      "UEJQ0",
      "CBJVQ",
      "4RIOW",
      "TDPRO",
      "FIVTY",
      "HJJWJ",
      "2HFZQ",
      "QY3IX",
      "ZAEEW",
      "QJO9S",
      "4GGMJ",
      "ES2BJ",
      "ZYKY5",
      "6GX4D",
      "YJSLD",
      "PSCOG",
      "RPNUO",
      "DONFW",
      "EQ1IW",
      "FLMRA",
      "GZJHS",
      "ARHPV",
      "PUVNB",
      "CQCMT",
      "GSJWC",
      "BSARH",
      "RR0IK",
      "1VEVT",
      "VF4WM",
      "QJDEF",
      "ZX5FX",
      "UHTXD",
      "K8DK5",
      "T6W2R",
      "993B1",
      "2NZMY",
      "RUMCD",
      "RH9L7",
      "U3RU8",
      "CBOFC",
      "LNDRX",
      "JECBD",
      "GL5KA",
      "E9MIY",
      "RTYGD",
      "7H3VG",
      "KZC6H",
      "AWE1M",
      "CDODO",
      "SCYOC",
      "UIC8H",
      "7TSVX",
      "MICCW",
      "XROAQ",
      "5Q7AU",
      "CQSJS",
      "RI3OR",
      "TNJ5K",
      "WG5DM",
      "92UMI",
      "WJEHA",
      "E5GD0",
      "IULX1",
      "GAMG6",
      "OEXO1",
      "IQEVA",
      "XMHNC",
      "OEKKH",
      "IQCTZ",
      "CEVBH",
      "GTA4T",
      "SS0IU",
      "GVE6I",
      "XQLSB",
      "9WQMN",
      "KE2JS",
      "5XOBR",
      "WJG4W",
      "WWJWN",
      "N3IGS",
      "JRLXE",
      "CIPVY",
      "DKVU1",
      "4BJJX",
      "K3WTW",
      "555IX",
      "OAYON",
      "OK30H",
      "NLWI3",
      "GMKSI",
      "CSYLS",
      "6XYWL",
      "UTGPV",
      "IQK4Z",
      "SIPQU",
      "CKYLP",
      "H8HEP",
      "WSBE2",
      "DH0D2",
      "8KBDY",
      "Z1DXF",
      "XC0BR",
      "8ALHU",
      "CAIRD",
      "RSKUH",
      "XLF7R",
      "MDZEZ",
      "P2NVN",
      "VT96P",
      "VEYMA",
      "2LCAZ",
      "EJMRL",
      "ZTWXV",
      "4GUVA",
      "U6HWJ",
      "UQT4S",
      "JVSIW",
      "GVKK6",
      "DLHTR",
      "RANER",
      "FSMSV",
      "IPPTH",
      "V43XM",
      "EXOJP",
      "N7TQB",
      "K4SWZ",
      "Z16PM",
      "NCLGW",
      "UNEJR",
      "GUYLG",
      "HT5ZK",
      "Z7Z8A",
      "BCPGM",
      "GHQD5",
      "QT1FJ",
      "90DOH",
      "PJ2YC",
      "ECLSM",
      "CWRAH",
      "X5FFT",
      "DL4MS",
      "1THAG",
      "KZYKM",
      "QISOK",
      "COFRG",
      "AG2D0",
      "7SZIB",
      "C2TWM",
      "B9RZP",
      "HW3FD",
      "MFUQY",
      "CTQW9",
      "JLM8P",
      "DJLBW",
      "AN02K",
      "JZHRB",
      "TRFPO",
      "6LJTN",
      "VDCDU",
      "BWNCE",
      "NRX8Q",
      "LDMXN",
      "QGLWJ",
      "LILLF",
      "ZI96X",
      "7CKMM",
      "HQCHY",
      "MEEDO",
      "YXPAM",
      "LQRGM",
      "K0VR7",
      "SASQ6",
      "2BQ0H",
      "VJD3I",
      "DO7ZH",
      "K4IZA",
      "QUDFT",
      "NVIZZ",
      "TGSYE",
      "Z384X",
      "ORXDE",
      "7JYFL",
      "759SV",
      "OWEO0",
      "4T3AI",
      "Y70QF",
      "PFLZ3",
      "G62TE",
      "DZYA6",
      "FU4BY",
      "PZN5Y",
      "FVSVS",
      "G9XH8",
      "D32VQ",
      "TMVGB",
      "QPH0N",
      "Y3TAF",
      "6IAGO",
      "ZREDX",
      "LZTRD",
      "GKFYQ",
      "GMEKJ",
      "TB00X",
      "PNLKQ",
      "TSXY8",
      "XEZVD",
      "TMOP3",
      "ZUJDK",
      "FKP0A",
      "QYXQO",
      "SHJRO",
      "C6L27",
      "JPLVH",
      "FOBGF",
      "17ZQK",
      "5S0XF",
      "MVXMR",
      "COBUK",
      "REAIP",
      "PLMTN",
      "PD7TZ",
      "M1LGJ",
      "QELPS",
      "PRW8L",
      "NHHPN",
      "OF1IY",
      "8M28G",
      "RL7DV",
      "OTNQP",
      "GYPF8",
      "1B69X",
      "I1O6K",
      "THZVQ",
      "Y7ODL",
      "LHLHB",
      "ZCSMT",
      "6INDN",
      "WCSKI",
      "ELNMS",
      "IRLYG",
      "BQATH",
      "UHYTS",
      "SFO7X",
      "PSOWE",
      "XVC1B",
      "GJA6Y",
      "OQE8V",
      "AJI2E",
      "INGB4",
      "GE6GU",
      "QMALN",
      "WM4N5",
      "LVJ4H",
      "BNNWS",
      "XUG35",
      "KUOBW",
      "ZATJI",
      "G4ZMU",
      "YBH0A",
      "QLXDB",
      "17YZ3",
      "CAL2I",
      "JGAKK",
      "YU0EB",
      "0NLPZ",
      "OS8O5",
      "M0BM4",
      "MLJ43",
      "LH12E",
      "R7JU0",
      "MRZ1K",
      "36UON",
      "Y3ETC",
      "UNGGH",
      "NZA1U",
      "W0HAM",
      "PGEOT",
      "SHEJX",
      "OJBBE",
      "FEBFL",
      "9DX7S",
      "6KQTC",
      "KQB77",
      "UYDPF",
      "0ANOA",
      "74YBP",
      "CWFIK",
      "DNNWR",
      "NA2WG",
      "0UPPM",
      "PDJ3U",
      "XZBDL",
      "JJTVJ",
      "VMT2Y",
      "DLYJA",
      "IJG6H",
      "AYV0F",
      "2SX0Z",
      "OHG1C",
      "MBU30",
      "ZPGID",
      "XGGOP",
      "UCMJH",
      "SYGQB",
      "XJAAA",
      "RD1WV",
      "5KHTT",
      "FXO5C",
      "1JDZJ",
      "HDFQP",
      "9FK4M",
      "HQGYF",
      "NCE9F",
      "ZTMYL",
      "GKL4J",
      "LJBTO",
      "I1FXE",
      "MDIZK",
      "JGOFI",
      "VUYIW",
      "72Y0R",
      "TDEIO",
      "8OTUY",
      "QVQOL",
      "YPL1J",
      "FZR9B",
      "JUDBS",
      "IQTT3",
      "3HWIO",
      "GOURU",
      "MYRTC",
      "CDQCK",
      "R8PIF",
      "SZ9O3",
      "Q99OM",
      "G0IOG",
      "HWIWE",
      "WHF79",
      "B2WBK",
      "NQ4LR",
      "QHDUJ",
      "VFUPE",
      "G2YVH",
      "LNUMU",
      "BSL2E",
      "LCALN",
      "HNLVZ",
      "PG8TP",
      "OOUXY"
    ],
    "sf-data-five": "29099",
    "va-data-fives": [
      "VYSPN",
      "1UH7O",
      "SKYQA",
      "MBUVJ",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "GKJX3",
      "ZIFVT",
      "F2O7T",
      "VDTXI"
    ],
    "Product ID": "084282929099",
    "specs_in_stock": "",
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.4,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3579,
    "ga_kcals_per_cup": 460,
    "ga_omega_6_fatty_acids_%": 3.36,
    "ga_omega_3_fatty_acids_%": 0.39,
    "ga_animal_protein_%": 85,
    "ga_ash_%": 8,
    "ga_calcium_%": 1.2,
    "ga_vitamin_d3_ui_per_kg": 681,
    "ga_vitamin_e_ui_per_kg": 134,
    "ga_vitamin_b12_ui_per_kg": 0,
    "aafco-options": "Formulated to meet the nutritional levels established by the AAFCO Dog Food Nutrient Profiles for All Life Stages, including growth of large size dogs (70 lb. or more as an adult).",
    "aafco-short": "For all life stages"
  },
  {
    "Name": "Herding Dog",
    "Slug": "premium-herding-dog-peas-free-dog-food",
    "Collection ID": "647ddb9037101ce399b33184",
    "Item ID": "647ddb9037101ce399b344e5",
    "canonical": "premium-herding-dog-peas-free-dog-food",
    "recordId": "rec6Cala1YCUDphpx",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "herding-dog",
    "itemId": 28979,
    "item-subtitle": "Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "item-status": "",
    "itemName": "Herding Dog Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "data-legumes": "Legumes Free",
    "data-poultry": "Poultry Free",
    "data-grain": "Grain Free",
    "data-five": "28979",
    "data-sort": 3,
    "data-one": "Herding",
    "data-brand": "Sport Dog Food",
    "data-diet": "Grain Free",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": [
      "https://previewengine-accl.zoho.com/image/WD/iph9x2e8c0d5fb67944a181f11640ec49ee51?version=1.0&width=2046&height=1536",
      "nosrc"
    ],
    "previewAlttag": "Herding Dog Food Bag",
    "cf_description": "",
    "data-faqType": "si",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "br-data-five": "1000",
    "img-data-five": "Herding Dog",
    "sd-data-fives": [
      "3A9NE",
      "DNXWW",
      "71Q6Z"
    ],
    "dogBr-fives": [
      "HGW3D",
      "ME0KB",
      "NTOHN",
      "GF0GP",
      "8KTYX",
      "MLXGP",
      "2ZREE",
      "VJYZS",
      "4TIL1",
      "UQ7MN",
      "MOVBB",
      "IPVOO"
    ],
    "dogKeys_ac": "Field Trials, Tracking, Agility, Dock Diving",
    "dogKeys_gp": "Field Dogs, Gun Dogs, Bird Dogs, Sporting Dogs, Active Dogs, Performance Dogs, Tracking Dogs, Agility Dogs, K9 Dogs, Working Dogs",
    "dogKeys_jb": "Detection, Patrol, Protection",
    "ing-data-fives": [
      "C6HRL",
      "K5VFA",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "not-data-fives": [
      "KEB4Z",
      "7YYYV",
      "PJZGH",
      "WOT9J",
      "VQ8Y7",
      "BS8EA",
      "ZOEIR",
      "YHSJR",
      "G9HW5",
      "XAGFV",
      "SR2TH",
      "VM56I",
      "UEJQ0",
      "CBJVQ",
      "4RIOW",
      "TDPRO",
      "FIVTY",
      "HJJWJ",
      "2HFZQ",
      "QY3IX",
      "ZAEEW",
      "QJO9S",
      "4GGMJ",
      "ES2BJ",
      "ZYKY5",
      "6GX4D",
      "YJSLD",
      "PSCOG",
      "RPNUO",
      "DONFW",
      "EQ1IW",
      "FLMRA",
      "GZJHS",
      "ARHPV",
      "PUVNB",
      "CQCMT",
      "GSJWC",
      "BSARH",
      "RR0IK",
      "1VEVT",
      "VF4WM",
      "QJDEF",
      "ZX5FX",
      "UHTXD",
      "K8DK5",
      "T6W2R",
      "993B1",
      "2NZMY",
      "RUMCD",
      "RH9L7",
      "U3RU8",
      "CBOFC",
      "LNDRX",
      "JECBD",
      "GL5KA",
      "E9MIY",
      "RTYGD",
      "7H3VG",
      "KZC6H",
      "AWE1M",
      "CDODO",
      "SCYOC",
      "UIC8H",
      "7TSVX",
      "MICCW",
      "XROAQ",
      "5Q7AU",
      "CQSJS",
      "RI3OR",
      "TNJ5K",
      "WG5DM",
      "92UMI",
      "WJEHA",
      "E5GD0",
      "IULX1",
      "GAMG6",
      "OEXO1",
      "IQEVA",
      "XMHNC",
      "OEKKH",
      "IQCTZ",
      "CEVBH",
      "GTA4T",
      "SS0IU",
      "GVE6I",
      "XQLSB",
      "9WQMN",
      "KE2JS",
      "5XOBR",
      "WJG4W",
      "WWJWN",
      "N3IGS",
      "JRLXE",
      "CIPVY",
      "DKVU1",
      "4BJJX",
      "K3WTW",
      "555IX",
      "OAYON",
      "OK30H",
      "NLWI3",
      "GMKSI",
      "CSYLS",
      "6XYWL",
      "UTGPV",
      "IQK4Z",
      "SIPQU",
      "CKYLP",
      "H8HEP",
      "WSBE2",
      "DH0D2",
      "8KBDY",
      "Z1DXF",
      "XC0BR",
      "8ALHU",
      "CAIRD",
      "RSKUH",
      "XLF7R",
      "MDZEZ",
      "P2NVN",
      "VT96P",
      "VEYMA",
      "2LCAZ",
      "EJMRL",
      "ZTWXV",
      "4GUVA",
      "U6HWJ",
      "UQT4S",
      "JVSIW",
      "GVKK6",
      "DLHTR",
      "RANER",
      "FSMSV",
      "IPPTH",
      "V43XM",
      "EXOJP",
      "N7TQB",
      "K4SWZ",
      "Z16PM",
      "NCLGW",
      "UNEJR",
      "GUYLG",
      "HT5ZK",
      "Z7Z8A",
      "BCPGM",
      "GHQD5",
      "QT1FJ",
      "90DOH",
      "PJ2YC",
      "ECLSM",
      "CWRAH",
      "X5FFT",
      "DL4MS",
      "1THAG",
      "KZYKM",
      "QISOK",
      "COFRG",
      "AG2D0",
      "7SZIB",
      "C2TWM",
      "B9RZP",
      "HW3FD",
      "MFUQY",
      "CTQW9",
      "JLM8P",
      "DJLBW",
      "AN02K",
      "JZHRB",
      "TRFPO",
      "6LJTN",
      "VDCDU",
      "BWNCE",
      "NRX8Q",
      "LDMXN",
      "QGLWJ",
      "LILLF",
      "ZI96X",
      "7CKMM",
      "HQCHY",
      "MEEDO",
      "YXPAM",
      "LQRGM",
      "K0VR7",
      "SASQ6",
      "2BQ0H",
      "VJD3I",
      "DO7ZH",
      "K4IZA",
      "QUDFT",
      "NVIZZ",
      "TGSYE",
      "Z384X",
      "ORXDE",
      "7JYFL",
      "759SV",
      "OWEO0",
      "4T3AI",
      "Y70QF",
      "PFLZ3",
      "G62TE",
      "DZYA6",
      "FU4BY",
      "PZN5Y",
      "FVSVS",
      "G9XH8",
      "D32VQ",
      "TMVGB",
      "QPH0N",
      "Y3TAF",
      "6IAGO",
      "ZREDX",
      "LZTRD",
      "GKFYQ",
      "GMEKJ",
      "TB00X",
      "PNLKQ",
      "TSXY8",
      "XEZVD",
      "TMOP3",
      "ZUJDK",
      "FKP0A",
      "QYXQO",
      "SHJRO",
      "C6L27",
      "JPLVH",
      "FOBGF",
      "17ZQK",
      "5S0XF",
      "MVXMR",
      "COBUK",
      "REAIP",
      "PLMTN",
      "PD7TZ",
      "M1LGJ",
      "QELPS",
      "PRW8L",
      "NHHPN",
      "OF1IY",
      "8M28G",
      "RL7DV",
      "OTNQP",
      "GYPF8",
      "1B69X",
      "I1O6K",
      "THZVQ",
      "Y7ODL",
      "LHLHB",
      "ZCSMT",
      "6INDN",
      "WCSKI",
      "ELNMS",
      "IRLYG",
      "BQATH",
      "UHYTS",
      "SFO7X",
      "PSOWE",
      "XVC1B",
      "GJA6Y",
      "OQE8V",
      "AJI2E",
      "INGB4",
      "GE6GU",
      "QMALN",
      "WM4N5",
      "LVJ4H",
      "BNNWS",
      "XUG35",
      "KUOBW",
      "ZATJI",
      "G4ZMU",
      "YBH0A",
      "QLXDB",
      "17YZ3",
      "CAL2I",
      "JGAKK",
      "YU0EB",
      "0NLPZ",
      "OS8O5",
      "M0BM4",
      "MLJ43",
      "LH12E",
      "R7JU0",
      "MRZ1K",
      "36UON",
      "Y3ETC",
      "UNGGH",
      "NZA1U",
      "W0HAM",
      "PGEOT",
      "SHEJX",
      "OJBBE",
      "FEBFL",
      "9DX7S",
      "6KQTC",
      "KQB77",
      "UYDPF",
      "0ANOA",
      "74YBP",
      "CWFIK",
      "DNNWR",
      "NA2WG",
      "0UPPM",
      "PDJ3U",
      "XZBDL",
      "JJTVJ",
      "VMT2Y",
      "DLYJA",
      "IJG6H",
      "AYV0F",
      "2SX0Z",
      "OHG1C",
      "MBU30",
      "ZPGID",
      "XGGOP",
      "UCMJH",
      "SYGQB",
      "XJAAA",
      "RD1WV",
      "5KHTT",
      "FXO5C",
      "1JDZJ",
      "HDFQP",
      "9FK4M",
      "HQGYF",
      "NCE9F",
      "ZTMYL",
      "GKL4J",
      "LJBTO",
      "I1FXE",
      "MDIZK",
      "JGOFI",
      "VUYIW",
      "72Y0R",
      "TDEIO",
      "8OTUY",
      "QVQOL",
      "YPL1J",
      "FZR9B",
      "JUDBS",
      "IQTT3",
      "3HWIO",
      "GOURU",
      "MYRTC",
      "CDQCK",
      "R8PIF",
      "SZ9O3",
      "Q99OM",
      "G0IOG",
      "HWIWE",
      "WHF79",
      "B2WBK",
      "NQ4LR",
      "QHDUJ",
      "VFUPE",
      "G2YVH",
      "LNUMU",
      "BSL2E",
      "LCALN",
      "HNLVZ",
      "PG8TP",
      "OOUXY"
    ],
    "sf-data-five": "28979",
    "va-data-fives": [
      "VYSPN",
      "SKYQA",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "GKJX3",
      "ZIFVT",
      "F2O7T",
      "KFWMD",
      "VDTXI"
    ],
    "Product ID": "084282928979",
    "specs_in_stock": true,
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3603.0500000000006,
    "ga_kcals_per_cup": 460,
    "ga_omega_6_fatty_acids_%": 1.42,
    "ga_omega_3_fatty_acids_%": 0.4,
    "ga_animal_protein_%": 89,
    "ga_ash_%": 8,
    "ga_calcium_%": 1.2,
    "ga_vitamin_d3_ui_per_kg": 681,
    "ga_vitamin_e_ui_per_kg": 132,
    "ga_vitamin_b12_ui_per_kg": 0,
    "aafco-options": "Formulated to meet the nutritional levels established by the AAFCO Dog Food Nutrient Profiles for All Life Stages, including growth of large size dogs (70 lb. or more as an adult).",
    "aafco-short": "For all life stages"

  }
];
