[
  {
    "Name": "Cub Puppy",
    "Slug": "premium-cub-puppy-peas-free-dog-food",
    "Collection ID": "647ddb9037101ce399b33184",
    "Item ID": "647ddb9037101ce399b344e8",
    "canonical": "premium-cub-puppy-peas-free-dog-food",
    "recordId": "recZ0C3ZTWsZk37zW",
    "calcSlug": "cub-puppy",
    "itemId": 29280,
    "itemName": "Cub Puppy Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "item-subtitle": "Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "item-status": "",
    "data-five": "29280",
    "data-sort": 1,
    "data-one": "Cub",
    "data-diet": "Grain",
    "data-brand": "Sport Dog Food",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": [
      "https://previewengine-accl.zoho.com/image/WD/iph9xb6de6ad0806e49c182dbf11c72cb5bb2?version=1.0&width=2046&height=1536",
      "nosrc"
    ],
    "previewAlttag": "Cub Dog Food Bag",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3847.7000000000003,
    "ga_kcals_per_cup": 526,
    "data-faqType": "si",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "Cub Puppy",
    "br-data-five": "1000",
    "sd-data-fives": [
      "YOIPL",
      "DNXWW",
      "71Q6Z"
    ],
    "ing-data-fives": [
      "C6HRL",
      "KEB4Z",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "va-data-fives": [
      "NG6TL",
      "VYSPN",
      "1UH7O",
      "M3BBO",
      "F9VGP",
      "MZQRJ",
      "PSAC9",
      "0PA9E",
      "DUKQO",
      "80FEX",
      "CPQ7X",
      "5T46P",
      "63DFT",
      "VELOJ",
      "RD1V9",
      "0CSHM",
      "KLFNM",
      "D1SQF",
      "JV9J9",
      "SKYQA",
      "MXQV1",
      "MBUVJ",
      "HP3UR",
      "EZB40",
      "JZ8D8",
      "TQRAE",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "GKJX3",
      "ZIFVT",
      "F2O7T"
    ],
    "Product ID": "084282929280",
    "specs_in_stock": "",
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "diets-legume-free": true,
    "diets-poultry-free": true,
    "diets-grain-free": "",
    "sf-data-five": "29280",
    "dog-data-fives": [
      "J5GHM",
      "9CDZC",
      "CEZHB",
      "VMXSF",
      "KCDKK",
      "HWZH0",
      "MELSK",
      "KC9UL"
    ]
  },
  {
    "Name": "Dock Dog",
    "Slug": "premium-dock-dog-peas-free-dog-food",
    "Collection ID": "647ddb9037101ce399b33184",
    "Item ID": "647ddb9037101ce399b344e3",
    "canonical": "premium-dock-dog-peas-free-dog-food",
    "recordId": "recJnPxkGb1ZUaEPI",
    "calcSlug": "dock-dog",
    "itemId": 29099,
    "itemName": "Dock Dog Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "item-subtitle": "Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "item-status": "",
    "data-five": "29099",
    "data-sort": 2,
    "data-one": "Dock",
    "data-diet": "Grain",
    "data-brand": "Sport Dog Food",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": [
      "https://previewengine-accl.zoho.com/image/WD/iph9x174a1af7a0684e1a906476d12fd3c21d?version=1.0&width=2046&height=1536",
      "nosrc"
    ],
    "previewAlttag": "Dock Dog Food Bag",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.4,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3579,
    "ga_kcals_per_cup": 460,
    "data-faqType": "si",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "Dock Dog",
    "br-data-five": "1000",
    "sd-data-fives": [
      "YOIPL",
      "DNXWW",
      "71Q6Z"
    ],
    "ing-data-fives": [
      "C6HRL",
      "KEB4Z",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "va-data-fives": [
      "NG6TL",
      "VYSPN",
      "1UH7O",
      "M3BBO",
      "F9VGP",
      "MZQRJ",
      "PSAC9",
      "0PA9E",
      "DUKQO",
      "80FEX",
      "CPQ7X",
      "5T46P",
      "63DFT",
      "VELOJ",
      "RD1V9",
      "0CSHM",
      "KLFNM",
      "D1SQF",
      "JV9J9",
      "SKYQA",
      "MXQV1",
      "MBUVJ",
      "HP3UR",
      "EZB40",
      "JZ8D8",
      "TQRAE",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "GKJX3",
      "ZIFVT",
      "F2O7T"
    ],
    "Product ID": "084282929099",
    "specs_in_stock": "",
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "diets-legume-free": true,
    "diets-poultry-free": true,
    "diets-grain-free": "",
    "sf-data-five": "29099",
    "dog-data-fives": [
      "LESYJ",
      "UT6SQ",
      "TQ87J",
      "N6M4B",
      "LNJLR"
    ]
  },
  {
    "Name": "Herding Dog",
    "Slug": "premium-herding-dog-peas-free-dog-food",
    "Collection ID": "647ddb9037101ce399b33184",
    "Item ID": "647ddb9037101ce399b344e5",
    "canonical": "premium-herding-dog-peas-free-dog-food",
    "recordId": "rec6Cala1YCUDphpx",
    "calcSlug": "herding-dog",
    "itemId": 28979,
    "itemName": "Herding Dog Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "item-subtitle": "Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "item-status": "",
    "data-five": "28979",
    "data-sort": 3,
    "data-one": "Herding",
    "data-diet": "Grain Free",
    "data-brand": "Sport Dog Food",
    "brandId": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": [
      "https://previewengine-accl.zoho.com/image/WD/iph9x2e8c0d5fb67944a181f11640ec49ee51?version=1.0&width=2046&height=1536",
      "nosrc"
    ],
    "previewAlttag": "Herding Dog Food Bag",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "specs_primary_flavor": "Meat",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3603.0500000000006,
    "ga_kcals_per_cup": 460,
    "data-faqType": "si",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "img-data-five": "Herding Dog",
    "br-data-five": "1000",
    "sd-data-fives": [
      "3A9NE",
      "DNXWW",
      "71Q6Z"
    ],
    "ing-data-fives": [
      "C6HRL",
      "K5VFA",
      "5E1NB",
      "NVHW0",
      "H0NSG",
      "U9EU7",
      "REAUC",
      "MDI1T",
      "9UMLW",
      "Z9I0H",
      "OWC0W",
      "UQ30T",
      "8CBAD",
      "QKPNY",
      "AH4GG",
      "PN28C",
      "JEBP3",
      "QFRJN",
      "EK1NU",
      "4CQVY",
      "IIDS9",
      "XORST",
      "XUUYO",
      "KSOUF",
      "MRSTT",
      "BOL4J",
      "J76F7",
      "XV780",
      "5ELBD",
      "YRWGG",
      "3U0K4",
      "SQ0XJ",
      "ABJVI",
      "81XCU",
      "XGD4Z",
      "YD8CG",
      "UDMZM",
      "ZAPVO",
      "NVUQ6",
      "MBFOA",
      "L5O6A",
      "AGJPT",
      "YLNYF",
      "AYYHZ",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "va-data-fives": [
      "NG6TL",
      "VYSPN",
      "1UH7O",
      "M3BBO",
      "F9VGP",
      "MZQRJ",
      "PSAC9",
      "0PA9E",
      "DUKQO",
      "80FEX",
      "CPQ7X",
      "5T46P",
      "63DFT",
      "VELOJ",
      "RD1V9",
      "0CSHM",
      "KLFNM",
      "D1SQF",
      "JV9J9",
      "SKYQA",
      "MBUVJ",
      "HP3UR",
      "EZB40",
      "JZ8D8",
      "TQRAE",
      "JDRWK",
      "VFKR6",
      "9QHMW",
      "KJCYZ",
      "MXQV1",
      "GKJX3",
      "ZIFVT",
      "F2O7T"
    ],
    "Product ID": "084282928979",
    "specs_in_stock": true,
    "Price": 98,
    "weight": 30,
    "quantity": 1,
    "diets-legume-free": true,
    "diets-poultry-free": true,
    "diets-grain-free": true,
    "sf-data-five": "28979",
    "dog-data-fives": [
      "J5GHM",
      "9CDZC",
      "CEZHB",
      "VMXSF",
      "KCDKK",
      "HWZH0",
      "MELSK",
      "KC9UL",
      "LESYJ",
      "UT6SQ",
      "TQ87J",
      "N6M4B",
      "LNJLR"
    ]
  }
]
