
[
  {
    "Name": "Cub Puppy",
    "Slug": "cub-puppy",
    "collection-api": "",
    "itemID_api": "64790371013993450",
    "calcSlug": 29280,
    "itemId": 29280,
    "itemName": "Cub Puppy Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "item-subtitle": "Grain Inclusive, Poultry Free, Active Dog and Puppy",
    "itemRecordId": "recMhYpP2XVmh4k8f",
    "data-faqType": "cub",
    "data-sort": 1,
    "data-one": "Cub",
    "data-alt": 29280,
    "data-diet": "Grain",
    "data-brand": "Sport Dog Food",
    "brandId": "1000",
    "brands": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9xb6de6ad0806e49c182dbf11c72cb5bb2?version=1.0&width=2046&height=1536",
    "previewAlttag": "Cub Dog Food Bag",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3603.0500000000006,
    "ga_kcals_per_cup": 460,
    "diets_slugs": [
      "grain-inclusive",
      "legumes-free",
      "poultry-free"
    ],
    "ing_calcSlugs": [
      "buffalo-meal",
      "oatmeal",
      "sweet-potatoes",
      "coconut-oil",
      "pork-meal",
      "catfish-meal",
      "cassava-root",
      "yeast-cultures",
      "salt",
      "natural-flavors",
      "salmon-oil",
      "kelp-meal",
      "calcium-propionate",
      "choline-chloride",
      "potassium-chloride",
      "zinc-amino-acids-complex",
      "iron-amino-acids-complex",
      "chicory-root",
      "vitamin-e",
      "pumpkin",
      "carrots",
      "blueberries",
      "cranberries",
      "zinc-sulfate",
      "manganese-amino-acids-complex",
      "ferrous-sulfate",
      "copper-amino-acids-complex",
      "selenium-yeast",
      "thiamine",
      "niacin",
      "l-carnitine",
      "d-calcium-pantothenate",
      "pyridoxine",
      "riboflavin",
      "vitamin-a",
      "biotin",
      "vitamin-d3",
      "vitamin-b12",
      "green-tea-extract",
      "folic-acid",
      "rosemary-extract",
      "mixed-tocopherols",
      "yucca-schidigera-extract",
      "iron-sulfate",
      "bifido-bacterium-bifidium-fermentation",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "lactobacillus-casei-fermentation"
    ]
  },
  {
    "Name": "Dock Dog",
    "Slug": "dock-dog",
    "collection-api": "",
    "itemID_api": "64790371013993440",
    "calcSlug": 29099,
    "itemId": 29099,
    "itemName": "Dock Dog Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "item-subtitle": "Grain Inclusive, Poultry Free, Buffalo and Oatmeal",
    "itemRecordId": "recIiFxL49tR5lB1d",
    "data-faqType": "dock",
    "data-sort": 2,
    "data-one": "Dock",
    "data-alt": 29099,
    "data-diet": "Grain",
    "data-brand": "Sport Dog Food",
    "brandId": "1000",
    "brands": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9x174a1af7a0684e1a906476d12fd3c21d?version=1.0&width=2046&height=1536",
    "previewAlttag": "Dock Dog Food Bag",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 20,
    "ga_crude_fiber_%": 3.3,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3579.3499999999995,
    "ga_kcals_per_cup": 460,
    "diets_slugs": [
      "grain-inclusive",
      "legumes-free",
      "poultry-free"
    ],
    "ing_calcSlugs": [
      "buffalo-meal",
      "oatmeal",
      "sweet-potatoes",
      "coconut-oil",
      "pork-meal",
      "catfish-meal",
      "cassava-root",
      "yeast-cultures",
      "salt",
      "natural-flavors",
      "salmon-oil",
      "kelp-meal",
      "calcium-propionate",
      "choline-chloride",
      "potassium-chloride",
      "zinc-amino-acids-complex",
      "iron-amino-acids-complex",
      "chicory-root",
      "vitamin-e",
      "pumpkin",
      "carrots",
      "blueberries",
      "cranberries",
      "zinc-sulfate",
      "manganese-amino-acids-complex",
      "ferrous-sulfate",
      "copper-amino-acids-complex",
      "selenium-yeast",
      "thiamine",
      "niacin",
      "l-carnitine",
      "d-calcium-pantothenate",
      "pyridoxine",
      "riboflavin",
      "vitamin-a",
      "biotin",
      "vitamin-d3",
      "vitamin-b12",
      "green-tea-extract",
      "folic-acid",
      "rosemary-extract",
      "mixed-tocopherols",
      "yucca-schidigera-extract",
      "iron-sulfate",
      "bifido-bacterium-bifidium-fermentation",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "lactobacillus-casei-fermentation"
    ]
  },
  {
    "Name": "Herding Dog",
    "Slug": "herding-dog",
    "collection-api": "",
    "itemID_api": "64790371013993450",
    "calcSlug": 28979,
    "itemId": 28979,
    "itemName": "Herding Dog Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "item-subtitle": "Grain Free, Poultry Free, Buffalo and Sweet Potato",
    "itemRecordId": "recdyXxbsNTkH3mke",
    "data-faqType": "herding",
    "data-sort": 3,
    "data-one": "Herding",
    "data-alt": 28979,
    "data-diet": "Grain Free",
    "data-brand": "Sport Dog Food",
    "brandId": "1000",
    "brands": "Sport Dog Food",
    "brandDisplay": "Sport Dog Food",
    "previewengine": "https://previewengine-accl.zoho.com/image/WD/iph9x2e8c0d5fb67944a181f11640ec49ee51?version=1.0&width=2046&height=1536",
    "previewAlttag": "Herding Dog Food Bag",
    "specs_price_per_bag": 98,
    "specs_bag-size_lbs": 30,
    "item-status": "",
    "specs_primary_flavor": "Meat",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "ga_crude_protein_%": 30,
    "ga_crude_fat_%": 15,
    "ga_crude_fiber_%": 3.4,
    "ga_moisture_%": 8,
    "ga_kcals_per_kg": 3847.7000000000003,
    "ga_kcals_per_cup": 526,
    "diets_slugs": [
      "grain-free",
      "legumes-free",
      "poultry-free"
    ],
    "ing_calcSlugs": [
      "buffalo-meal",
      "potatoes",
      "sweet-potatoes",
      "coconut-oil",
      "pork-meal",
      "catfish-meal",
      "cassava-root",
      "yeast-cultures",
      "salt",
      "natural-flavors",
      "salmon-oil",
      "kelp-meal",
      "calcium-propionate",
      "choline-chloride",
      "potassium-chloride",
      "zinc-amino-acids-complex",
      "iron-amino-acids-complex",
      "chicory-root",
      "vitamin-e",
      "pumpkin",
      "carrots",
      "blueberries",
      "cranberries",
      "zinc-sulfate",
      "manganese-amino-acids-complex",
      "ferrous-sulfate",
      "copper-amino-acids-complex",
      "selenium-yeast",
      "thiamine",
      "niacin",
      "l-carnitine",
      "d-calcium-pantothenate",
      "pyridoxine",
      "riboflavin",
      "vitamin-a",
      "biotin",
      "vitamin-d3",
      "vitamin-b12",
      "green-tea-extract",
      "folic-acid",
      "rosemary-extract",
      "mixed-tocopherols",
      "yucca-schidigera-extract",
      "iron-sulfate",
      "bifido-bacterium-bifidium-fermentation",
      "enterococcus-faecium-fermentation",
      "lactobacillus-acidophilus-fermentation",
      "lactobacillus-casei-fermentation"
    ]
  }
]
