
 export const VA_DATA = {
  "VYSPN": {
    "Name": "Calorie Dense",
    "Slug": "calorie-dense-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f145136c964c6524fa",
    "canonical": "calorie-dense-dry-dog-food",
    "recordId": "recQfn6qgHGxVYspn",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Calorie Dense",
    "data-five": "VYSPN",
    "data-sort": 1,
    "data-one": "Calorie Dense",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "calorie-packed dog food, high-calorie formula, dense energy dog food, food for weight gain in dogs, fuel-rich kibble, dog food with more calories per cup",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "EP5IL",
      "9V6Z8",
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "SOG9C",
      "PEG2O",
      "MNLTS",
      "HKAHU",
      "CSIRP",
      "ZM6ZC",
      "ZZP8A",
      "ADGHC",
      "DSFXG",
      "HNNKP",
      "RNAPM"
    ]
  },
  "NG6TL": {
    "Name": "High Energy",
    "Slug": "high-energy-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f1a40f61a2f41b9b81",
    "canonical": "high-energy-dry-dog-food",
    "recordId": "recIOo1CWqg5NG6TL",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "High Energy",
    "data-five": "NG6TL",
    "data-sort": 2,
    "data-one": "High Energy",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "energy-boosting dog food, food for active dogs, performance dog food, food for dogs that burn a lot of energy, dog food for high activity levels, working dog fuel",
    "ing-data-fives": [
      "C6HRL",
      "H0NSG",
      "5E1NB",
      "JEBP3",
      "SQ0XJ",
      "MBFOA",
      "ZAPVO",
      "5ELBD",
      "YRWGG",
      "ABJVI",
      "81XCU"
    ],
    "si-data-fives": [
      "29280"
    ],
    "sf-data-fives": [
      "29280"
    ],
    "dog-data-fives": [
      "GAQ7O",
      "EP5IL",
      "WBT8X",
      "LCCV8",
      "MM5SK",
      "OSXWL",
      "SOG9C",
      "ZZP8A",
      "ADGHC",
      "BRTGB"
    ]
  },
  "TQRAE": {
    "Name": "High Fat",
    "Slug": "high-fat-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f1362af349d6d17581",
    "canonical": "high-fat-dry-dog-food",
    "recordId": "recfavtINYZsTQrae",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "High Fat",
    "data-five": "TQRAE",
    "data-sort": 3,
    "data-one": "High Fat",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "high-fat content dog food, dog food with extra fat, fat-rich performance kibble, food for dogs needing more calories, high fat for endurance dogs",
    "ing-data-fives": [
      "OWC0W",
      "NVHW0"
    ],
    "si-data-fives": [
      "29280"
    ],
    "sf-data-fives": [
      "29280"
    ],
    "dog-data-fives": "9V6Z8"
  },
  "SKYQA": {
    "Name": "Highly Digestible",
    "Slug": "highly-digestible-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f174b391ba4c49dbb0",
    "canonical": "highly-digestible-dry-dog-food",
    "recordId": "reccQ4fsCPYdSkyQa",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Highly Digestible",
    "data-five": "SKYQA",
    "data-sort": 4,
    "data-one": "Highly Digestible",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "easy-to-digest dog food, gentle on digestion, sensitive digestion dog food, stomach-friendly dog food, gut-friendly formula",
    "ing-data-fives": [
      "U9EU7",
      "5E1NB",
      "4CQVY",
      "QFRJN",
      "YLNYF",
      "KEB4Z",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "WBT8X",
      "Y6PGF",
      "LCCV8",
      "HKAHU",
      "UTHHC",
      "ZM6ZC",
      "B9REG",
      "RNAPM"
    ]
  },
  "ZIFVT": {
    "Name": "Legumes Free",
    "Slug": "legumes-free-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f256d9af76dc9ac275",
    "canonical": "legumes-free-dry-dog-food",
    "recordId": "recnTjjHDOotZiFvt",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Legumes Free",
    "data-five": "ZIFVT",
    "data-sort": 5,
    "data-one": "Legumes Free",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "no peas or lentils, legume-free dog food, pea-free kibble, no chickpeas or beans, excludes legumes, excludes peas and lentils, dry dog food with no legumes, free of legumes, lentil- and pea-free formula, no legumes, without legumes",
    "ing-data-fives": [],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": ""
  },
  "F2O7T": {
    "Name": "Poultry Free",
    "Slug": "poultry-free-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2fe3cb8e054c438c7",
    "canonical": "poultry-free-dry-dog-food",
    "recordId": "rectV2Yy6Cf7f2O7T",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Poultry Free",
    "data-five": "F2O7T",
    "data-sort": 6,
    "data-one": "Poultry Free",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "chicken-free dog food, no turkey or chicken, poultry-free kibble, non-poultry protein formula, excludes poultry ingredients, excludes poultry proteins, dry dog food without poultry, free of chicken and turkey, no chicken or turkey, poultry-sensitive formula, without poultry, legume-free recipe, non-poultry recipe",
    "ing-data-fives": [],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": ""
  },
  "1UH7O": {
    "Name": "Allergy Relief",
    "Slug": "premium-dog-food-for-allergy-relief",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2953555bd342aa82a",
    "canonical": "premium-dog-food-for-allergy-relief",
    "recordId": "recmYvVCvOPM1UH7O",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Allergy Relief",
    "data-five": "1UH7O",
    "data-sort": 7,
    "data-one": "Allergy Relief",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "limited ingredient for allergies, allergy-friendly kibble, food for itchy dogs, dog food for skin sensitivities, anti-allergy formula",
    "ing-data-fives": [
      "C6HRL",
      "U9EU7",
      "H0NSG",
      "OWC0W",
      "4CQVY"
    ],
    "si-data-fives": [
      "29280",
      "29099"
    ],
    "sf-data-fives": [
      "29280",
      "29099"
    ],
    "dog-data-fives": ""
  },
  "JDRWK": {
    "Name": "Healthy Skin and Coat",
    "Slug": "premium-dog-food-for-healthy-skin-and-coat",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f15554b3b3ad185abb",
    "canonical": "premium-dog-food-for-healthy-skin-and-coat",
    "recordId": "recxYVtefKYaJDrWK",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Healthy Skin and Coat",
    "data-five": "JDRWK",
    "data-sort": 9,
    "data-one": "Healthy Skin and Coat",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "shiny coat dog food, for dry or itchy skin, skin-supportive kibble, improves coat condition, nourishes skin and fur",
    "ing-data-fives": [
      "U9EU7",
      "OWC0W",
      "NVHW0",
      "PN28C",
      "YD8CG",
      "XGD4Z"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "EP5IL",
      "ZZP8A"
    ]
  },
  "MBUVJ": {
    "Name": "Sensitive Stomachs",
    "Slug": "premium-dog-food-for-sensitive-stomachs",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f21771c456280d7ce2",
    "canonical": "premium-dog-food-for-sensitive-stomachs",
    "recordId": "recudqLfYraQmBuVJ",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Sensitive Stomachs",
    "data-five": "MBUVJ",
    "data-sort": 10,
    "data-one": "Sensitive Stomachs",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "dog food for upset stomach, food for dogs with digestion issues, gentle stomach formula, tummy-sensitive kibble, for dogs with GI sensitivity",
    "ing-data-fives": [
      "5E1NB",
      "4CQVY",
      "QFRJN",
      "YLNYF",
      "KEB4Z",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "29099"
    ],
    "sf-data-fives": [
      "29280",
      "29099"
    ],
    "dog-data-fives": ""
  },
  "VFKR6": {
    "Name": "Natural Antioxidants",
    "Slug": "premium-dog-food-with-natural-antioxidants",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2b0683e7055faffbf",
    "canonical": "premium-dog-food-with-natural-antioxidants",
    "recordId": "recuO0ZYQNjJVFKR6",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Natural Antioxidants",
    "data-five": "VFKR6",
    "data-sort": 11,
    "data-one": "Natural Antioxidants",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "immune-boosting dog food, natural preservative formula, antioxidant-rich dog food, supports immune health, dog food with superfoods",
    "ing-data-fives": [
      "OWC0W",
      "IIDS9",
      "XORST",
      "XUUYO",
      "EK1NU",
      "NVUQ6",
      "L5O6A",
      "XV780"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "LCCV8",
      "MNLTS",
      "HNNKP"
    ]
  },
  "KJCYZ": {
    "Name": "Performance Minerals",
    "Slug": "premium-dog-food-with-performance-minerals",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2f4067a1fbef30c91",
    "canonical": "premium-dog-food-with-performance-minerals",
    "recordId": "recTWktGF6EoKJcYZ",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Performance Minerals",
    "data-five": "KJCYZ",
    "data-sort": 12,
    "data-one": "Performance Minerals",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "dog food with added minerals, supports muscle recovery and strength, mineral-enriched formula, fortified for performance dogs, electrolyte-balanced nutrition",
    "ing-data-fives": [
      "UQ30T",
      "PN28C",
      "MRSTT",
      "JEBP3",
      "J76F7",
      "XV780"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "EP5IL",
      "WBT8X",
      "9V6Z8",
      "MM5SK",
      "B5JOI",
      "SOG9C",
      "CSIRP",
      "ZM6ZC",
      "ZZP8A",
      "ADGHC",
      "DSFXG"
    ]
  },
  "GKJX3": {
    "Name": "Probiotics Added",
    "Slug": "premium-dog-food-with-probiotics-added",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2d159789b09ea5a83",
    "canonical": "premium-dog-food-with-probiotics-added",
    "recordId": "rec3XPgfMFKCgkJx3",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Probiotics Added",
    "data-five": "GKJX3",
    "data-sort": 13,
    "data-one": "Probiotics Added",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "gut health dog food, digestive support formula, includes probiotics, dog food with live cultures, promotes good bacteria",
    "ing-data-fives": [
      "QFRJN",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "GAQ7O",
      "EP5IL",
      "Y6PGF",
      "PEG2O",
      "HKAHU",
      "UTHHC",
      "CSIRP",
      "ZM6ZC",
      "B9REG",
      "ZZP8A",
      "DSFXG",
      "RNAPM",
      "BRTGB"
    ]
  },
  "9QHMW": {
    "Name": "Upgraded Vitamins",
    "Slug": "premium-dog-food-with-upgraded-vitamins",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2eab59a30c363cc05",
    "canonical": "premium-dog-food-with-upgraded-vitamins",
    "recordId": "recW9nf4O63p9QHMw",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Upgraded Vitamins",
    "data-five": "9QHMW",
    "data-sort": 14,
    "data-one": "Upgraded Vitamins",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "enriched with vitamins, vitamin-packed formula, dog food with added nutrients, supports immune and joint health, fortified dog food",
    "ing-data-fives": [
      "IIDS9",
      "XORST",
      "XUUYO",
      "UQ30T",
      "EK1NU",
      "PN28C",
      "MRSTT",
      "JEBP3",
      "J76F7",
      "SQ0XJ",
      "YD8CG",
      "MBFOA",
      "UDMZM",
      "ZAPVO",
      "5ELBD",
      "YRWGG",
      "ABJVI",
      "81XCU",
      "XGD4Z"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "GAQ7O",
      "Y6PGF",
      "B5JOI",
      "MNLTS",
      "UTHHC",
      "B9REG",
      "HNNKP",
      "BRTGB"
    ]
  },
  "WREGA": {
    "Name": "500+ kcals per cup",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recgg1zXuljBwRegA",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "",
    "data-five": "WREGA",
    "data-sort": "",
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "",
    "ing-data-fives": [],
    "si-data-fives": [
      "29280"
    ],
    "sf-data-fives": [
      "29280"
    ],
    "dog-data-fives": ""
  },
  "KFWMD": {
    "Name": "Grain Free",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "rec8oOoSgF2lkFwmD",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "",
    "data-five": "KFWMD",
    "data-sort": "",
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "",
    "ing-data-fives": [],
    "si-data-fives": [
      "28979"
    ],
    "sf-data-fives": [
      "28979"
    ],
    "dog-data-fives": ""
  },
  "VTQGN": {
    "Name": "Grain Inclusive",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recFotuVKC83VtqGN",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "",
    "data-five": "VTQGN",
    "data-sort": "",
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "",
    "ing-data-fives": [],
    "si-data-fives": [
      "29280"
    ],
    "sf-data-fives": [
      "29280"
    ],
    "dog-data-fives": ""
  },
  "VDTXI": {
    "Name": "Peas Free",
    "Slug": "",
    "Collection ID": "",
    "Item ID": "",
    "canonical": "",
    "recordId": "recwTn9BzItwVdTxi",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "",
    "data-five": "VDTXI",
    "data-sort": "",
    "data-one": "",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "va",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "data-keys": "",
    "ing-data-fives": [],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": ""
  }
};

