export const VA_DATA = [ 
  {
    "Name": "Calorie Dense",
    "Slug": "calorie-dense-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f145136c964c6524fa",
    "canonical": "calorie-dense-dry-dog-food",
    "recordId": "recQfn6qgHGxVYspn",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Calorie Dense",
    "data-five": "VYSPN",
    "data-sort": 1,
    "data-one": "calories",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "NVHW0"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "EP5IL",
      "9V6Z8",
      "MM5SK",
      "OSXWL",
      "B5JOI",
      "SOG9C",
      "PEG2O",
      "MNLTS",
      "HKAHU",
      "CSIRP"
    ]
  },
  {
    "Name": "High Energy",
    "Slug": "high-energy-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f1a40f61a2f41b9b81",
    "canonical": "high-energy-dry-dog-food",
    "recordId": "recIOo1CWqg5NG6TL",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "High Energy",
    "data-five": "NG6TL",
    "data-sort": 2,
    "data-one": "energy",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "H0NSG",
      "5E1NB",
      "JEBP3",
      "SQ0XJ",
      "MBFOA",
      "ZAPVO",
      "5ELBD",
      "YRWGG",
      "ABJVI",
      "81XCU"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "GAQ7O",
      "EP5IL",
      "WBT8X",
      "LCCV8",
      "MM5SK",
      "OSXWL",
      "SOG9C",
      "LESYJ",
      "N6M4B",
      "KC9UL",
      "HWZH0",
      "TQ87J",
      "UT6SQ",
      "GVJDB",
      "VMXSF",
      "EA62U",
      "9CDZC",
      "J5GHM"
    ]
  },
  {
    "Name": "High Fat",
    "Slug": "high-fat-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f1362af349d6d17581",
    "canonical": "high-fat-dry-dog-food",
    "recordId": "recfavtINYZsTQrae",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "High Fat",
    "data-five": "TQRAE",
    "data-sort": 3,
    "data-one": "fat",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "OWC0W",
      "NVHW0"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "9V6Z8",
      "CEZHB"
    ]
  },
  {
    "Name": "Highly Digestible",
    "Slug": "highly-digestible-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f174b391ba4c49dbb0",
    "canonical": "highly-digestible-dry-dog-food",
    "recordId": "reccQ4fsCPYdSkyQa",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Highly Digestible",
    "data-five": "SKYQA",
    "data-sort": 4,
    "data-one": "digestible",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "U9EU7",
      "5E1NB",
      "4CQVY",
      "QFRJN",
      "YLNYF",
      "KEB4Z",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "5PFWE",
      "WBT8X",
      "Y6PGF",
      "LCCV8",
      "OP4RY",
      "HKAHU",
      "UTHHC",
      "LESYJ",
      "N6M4B",
      "HWZH0",
      "CEZHB"
    ]
  },
  {
    "Name": "Legumes Free",
    "Slug": "legumes-free-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f256d9af76dc9ac275",
    "canonical": "legumes-free-dry-dog-food",
    "recordId": "recnTjjHDOotZiFvt",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Legumes Free",
    "data-five": "ZIFVT",
    "data-sort": 5,
    "data-one": "legumes-free",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": ""
  },
  {
    "Name": "Poultry Free",
    "Slug": "poultry-free-dry-dog-food",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2fe3cb8e054c438c7",
    "canonical": "poultry-free-dry-dog-food",
    "recordId": "rectV2Yy6Cf7f2O7T",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Poultry Free",
    "data-five": "F2O7T",
    "data-sort": 6,
    "data-one": "poultry-free",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": ""
  },
  {
    "Name": "Allergy Relief",
    "Slug": "premium-dog-food-for-allergy-relief",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2953555bd342aa82a",
    "canonical": "premium-dog-food-for-allergy-relief",
    "recordId": "recmYvVCvOPM1UH7O",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Allergy Relief",
    "data-five": "1UH7O",
    "data-sort": 7,
    "data-one": "allergy",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "C6HRL",
      "U9EU7",
      "H0NSG",
      "OWC0W",
      "4CQVY"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": "OP4RY"
  },
  {
    "Name": "Balanced Nutrition",
    "Slug": "premium-dog-food-for-balanced-nutrition",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f22feae61b10b78904",
    "canonical": "premium-dog-food-for-balanced-nutrition",
    "recordId": "rec6X7GHmvXeMxqV1",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Balanced Nutrition",
    "data-five": "MXQV1",
    "data-sort": 8,
    "data-one": "balanced",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "IIDS9",
      "KEB4Z",
      "UQ30T",
      "UDMZM"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "GAQ7O",
      "5PFWE",
      "WBT8X",
      "OSXWL",
      "PEG2O",
      "OP4RY",
      "HKAHU",
      "UTHHC",
      "LESYJ",
      "KC9UL",
      "HWZH0",
      "TQ87J",
      "UT6SQ",
      "GVJDB",
      "VMXSF",
      "CEZHB",
      "EA62U",
      "9CDZC",
      "J5GHM"
    ]
  },
  {
    "Name": "Healthy Skin and Coat",
    "Slug": "premium-dog-food-for-healthy-skin-and-coat",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f15554b3b3ad185abb",
    "canonical": "premium-dog-food-for-healthy-skin-and-coat",
    "recordId": "recxYVtefKYaJDrWK",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Healthy Skin and Coat",
    "data-five": "JDRWK",
    "data-sort": 9,
    "data-one": "skincoat",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "U9EU7",
      "OWC0W",
      "NVHW0",
      "PN28C",
      "YD8CG",
      "XGD4Z"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "EP5IL",
      "N6M4B",
      "HWZH0",
      "UT6SQ"
    ]
  },
  {
    "Name": "Sensitive Stomachs",
    "Slug": "premium-dog-food-for-sensitive-stomachs",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f21771c456280d7ce2",
    "canonical": "premium-dog-food-for-sensitive-stomachs",
    "recordId": "recudqLfYraQmBuVJ",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Sensitive Stomachs",
    "data-five": "MBUVJ",
    "data-sort": 10,
    "data-one": "sensitive",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "5E1NB",
      "4CQVY",
      "QFRJN",
      "YLNYF",
      "KEB4Z",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": "OP4RY"
  },
  {
    "Name": "Natural Antioxidants",
    "Slug": "premium-dog-food-with-natural-antioxidants",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2b0683e7055faffbf",
    "canonical": "premium-dog-food-with-natural-antioxidants",
    "recordId": "recuO0ZYQNjJVFKR6",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Natural Antioxidants",
    "data-five": "VFKR6",
    "data-sort": 11,
    "data-one": "antioxidants",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "OWC0W",
      "IIDS9",
      "XORST",
      "XUUYO",
      "EK1NU",
      "NVUQ6",
      "L5O6A",
      "AGJPT",
      "XV780"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "LCCV8",
      "MNLTS",
      "KC9UL",
      "UT6SQ",
      "J5GHM"
    ]
  },
  {
    "Name": "Performance Minerals",
    "Slug": "premium-dog-food-with-performance-minerals",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2f4067a1fbef30c91",
    "canonical": "premium-dog-food-with-performance-minerals",
    "recordId": "recTWktGF6EoKJcYZ",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Performance Minerals",
    "data-five": "KJCYZ",
    "data-sort": 12,
    "data-one": "minerals",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "UQ30T",
      "PN28C",
      "MRSTT",
      "JEBP3",
      "J76F7",
      "XV780"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "EP5IL",
      "WBT8X",
      "9V6Z8",
      "MM5SK",
      "B5JOI",
      "SOG9C",
      "CSIRP",
      "LESYJ",
      "KC9UL",
      "TQ87J",
      "GVJDB",
      "VMXSF",
      "CEZHB",
      "EA62U"
    ]
  },
  {
    "Name": "Probiotics Added",
    "Slug": "premium-dog-food-with-probiotics-added",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2d159789b09ea5a83",
    "canonical": "premium-dog-food-with-probiotics-added",
    "recordId": "rec3XPgfMFKCgkJx3",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Probiotics Added",
    "data-five": "GKJX3",
    "data-sort": 13,
    "data-one": "probiotics",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "QFRJN",
      "JTSRY",
      "HFCYR",
      "RUAPK",
      "UQHTP"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "KCDKK",
      "GAQ7O",
      "5PFWE",
      "EP5IL",
      "Y6PGF",
      "PEG2O",
      "OP4RY",
      "HKAHU",
      "UTHHC",
      "CSIRP",
      "TQ87J",
      "VMXSF",
      "9CDZC",
      "J5GHM"
    ]
  },
  {
    "Name": "Upgraded Vitamins",
    "Slug": "premium-dog-food-with-upgraded-vitamins",
    "Collection ID": "647ddb9037101ce399b331ed",
    "Item ID": "6852c5f2eab59a30c363cc05",
    "canonical": "premium-dog-food-with-upgraded-vitamins",
    "recordId": "recW9nf4O63p9QHMw",
    "recordType": "",
    "recordStatus": "",
    "calcSlug": "",
    "vaName": "Upgraded Vitamins",
    "data-five": "9QHMW",
    "data-sort": 14,
    "data-one": "vitamins",
    "previewengine": "",
    "previewAlttag": "",
    "cf_description": "",
    "data-faqType": "",
    "typed_intro": "",
    "manual_faq_enabled": "",
    "tone_override_tagline": "",
    "tone_override_subtitle": "",
    "section-h1": "",
    "section-name": "",
    "section-p": "",
    "section-prompt": "",
    "persona_context": "",
    "ing-data-fives": [
      "IIDS9",
      "XORST",
      "XUUYO",
      "UQ30T",
      "EK1NU",
      "PN28C",
      "MRSTT",
      "JEBP3",
      "J76F7",
      "SQ0XJ",
      "YD8CG",
      "MBFOA",
      "UDMZM",
      "ZAPVO",
      "5ELBD",
      "YRWGG",
      "ABJVI",
      "81XCU",
      "XGD4Z"
    ],
    "si-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "sf-data-fives": [
      "29280",
      "29099",
      "28979"
    ],
    "dog-data-fives": [
      "GAQ7O",
      "Y6PGF",
      "B5JOI",
      "MNLTS",
      "UTHHC",
      "N6M4B",
      "GVJDB",
      "EA62U",
      "9CDZC"
    ]
  }
];
